### DISCUSSION TITLE
How to force TRV fully open during hot seasons

### DISCUSSION THREAD

**Discussion by nicola-spreafico** [jmcollin78/versatile_thermostat#1000] [General]
Hello everyone,
I am probably drowning in an inch of water, but in order not to risk messing things up, I prefer to ask the community.

The heating period is now over, using the central entity select.central_mode I have disabled all VTherm so that no more room heating is done.
![image](https://github.com/user-attachments/assets/a9c8b64e-cb92-4655-abba-5fa6628447ba)

At the moment all the valves underneath are completely closed, however since they will have to be idle for several months until next fall/winter, as long as the boiler remains idle I would like to open all of them forcibly so as not to ruin the internal mechanism and leave it at “rest”.

The open valve allows the shutter not to get stuck if it sits idle for long periods of time.

My problem is that I can't force the valves open as long as the thermostat stays on off. I have also tried changing the value directly from the Zigbee2MQTT interface, but it is my understanding that with Sonoff valves as long as they remain in the “off” state, they do not actually apply the opening percentage change.

So I had thought to briefly turn the valve on heat, reset the opening percentage to maximum and then set it back to off, however the moment I move it to heat, VTherm takes over which sets its own opening value via TPI.

I am therefore asking for advice on how I can do to open all the valves. At the moment, the only idea I can think of is to put all the devices created with VT in the off state, but it seems excessive as an off state.

Thank you to anyone who can give me advice.

EDIT
P.S. I'm on issue number 1000, lol 😅

**Comment by jmcollin78** [comment]
Is that the same point of this one ? https://github.com/jmcollin78/versatile_thermostat/issues/1001 

If yes xan you please vote for #1001 ?

**Reply by nicola-spreafico** [reply]
Thank you for pointing out this other topic, I started to write my issue this morning before it was posted and then I left the draft until now, I guess I had the same idea as the other author. Basically my need is to open to 100% the valve when the heating system is off, reading the description from #999 seems to be the same.

**Reply by AliveDevil** [reply]
Two idiots, one thought 😅

**Comment by nicola-spreafico** [comment]
Hello,
I'm very aware that this is very ugly (to say the least), but in the meantime I haven't found a better method to do so.

The commands to change the opening/closing degree (to force the valve to be fully open) are executed only if the TRV is in heat mode (and need to stay on heat otherwise it closes again. But with the TRV in heat mode, the VTherm come back online (even if central mode is stopped).

So for the moment I made this automation to set the system as "idle":
```
automation:
  - id: central_mode_status_change
    alias: central_mode_status_change
    trigger:
      - platform: state
        entity_id: select.central_mode
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: select.central_mode
                state: "Stopped"
            sequence:
              # Disable VTherm to allow underlying TRV back to climate without start actual heating
              - service: homeassistant.disable_device
                data:
                  device_id:
                    - 0655e39aa99072c9bd774b35b62b9ec2 # casa_p0_bagno_termostato

              # Now that VTherm is disable, I can turn back on the underlying TRV climate without start the actual heating
              - service: climate.turn_on
                target:
                  entity_id:
                    - climate.casa_p0_bagno_radiatore_valvola

              # In order for the TRV to listen for change degrees command, the action need to be heating. If I change the valve degrees while on "off", no change will be applied
              # Also the state need to remain "heat" otherwise the TRV will entirely close
              - service: climate.set_hvac_mode
                target:
                  entity_id:
                    - climate.casa_p0_bagno_radiatore_valvola
                data:
                  hvac_mode: heat

              # All TRV climates are set to 7° temperature as reference for the heating mode
              - service: climate.set_temperature
                target:
                  entity_id:
                    - climate.casa_p0_bagno_radiatore_valvola
                data:
                  temperature: 7

              # Now that the TRV is on, I can force the valve to be open (closing degree at 0)
              - service: number.set_value
                target:
                  entity_id:
                    - number.casa_p0_bagno_radiatore_valvola_valve_closing_degree
                data:
                  value: 0

			  # Now that the TRV is on, I can force the valve to be open (opening degree at 0)
              - service: number.set_value
                target:
                  entity_id:
                    - number.casa_p0_bagno_radiatore_valvola_valve_opening_degree
                data:
                  value: 100
```

If you simply add more entities id to the list you can manage multiple radiators/valves.

Basically it deactivate the VTherm so that when the TRV is set to heat it doesn't restore the actual heating system.
Right now the TRV will remain in heat mode (even if the boiler is off) so that I can keep the valve entirely open as per the original request.

Again, very ugly, but for the moment make the cut
