### DISCUSSION TITLE
Window open state ignored by auto start/stop?

### DISCUSSION THREAD

**Discussion by carlolars** [jmcollin78/versatile_thermostat#1037] [General]
I have the auto start/stop enabled and use a sensor for open window detection. I noticed just now that my heater turned on while the window was open.

![image](https://github.com/user-attachments/assets/0faf1696-685a-46bf-bec2-7bbdb5b1ce32)

I opened the window while the heater was off by auto start/stop but then it turned on again while the window was still open.

After some time it was turned off again by auto start-stop, window still open...

![image](https://github.com/user-attachments/assets/ee19eac2-1bd0-4192-9af8-35b8128cbd23)

Using version 7.3.0 of VT.

**Comment by jmcollin78** [comment]
Hello, what kind of VTherm do you use ? Can you post me your attributes when you reproduce the issue ?

See: https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/reference.md#custom-attributes

**Comment by carlolars** [comment]
I use an over climate.

It just happened now, fairly easy to reproduce: when HVAC is turned off by auto start/stop I open the door and then wait, seems to take about an hour or so.

<details><summary>Attributes during faulty condition:</summary>

```yaml
hvac_modes:
  - cool
  - heat
  - fan_only
  - dry
  - heat_cool
  - "off"
min_temp: 15
max_temp: 25
target_temp_step: 1
fan_modes:
  - quiet
  - low
  - medium_low
  - medium
  - medium_high
  - high
  - auto
  - strong
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
swing_modes:
  - fixedtop
  - fixedmiddletop
  - fixedmiddle
  - fixedmiddlebottom
  - fixedbottom
  - stopped
  - rangefull
swing_horizontal_modes: []
current_temperature: 20.9
temperature: 21
current_humidity: 56.2
fan_mode: auto
hvac_action: idle
preset_mode: comfort
swing_mode: fixedmiddletop
swing_horizontal_mode: ""
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 17
eco_temp: 18
boost_temp: 22
comfort_temp: 21
frost_away_temp: 17
eco_away_temp: 17
boost_away_temp: 17
comfort_away_temp: 17
target_temperature_step: 1
ext_current_temperature: 18.02
ac_mode: true
saved_preset_mode: comfort
saved_target_temp: 21
saved_hvac_mode: "off"
last_temperature_datetime: "2025-06-08T14:43:38.838872+02:00"
last_ext_temperature_datetime: "2025-06-08T14:48:59.180559+02:00"
minimal_activation_delay_sec: 10
minimal_deactivation_delay_sec: 0
total_energy: 0
last_update_datetime: "2025-06-08T14:48:59.194302+02:00"
timezone: Europe/Stockholm
temperature_unit: °C
is_device_active: false
device_actives: []
nb_device_actives: 0
ema_temp: 21.07
is_used_by_central_boiler: false
temperature_slope: -0.41
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
last_change_time_from_vtherm: "2025-06-08T14:43:34.816981+02:00"
presence_sensor_entity_id: binary_sensor.home_occupied
presence_state: "on"
is_presence_configured: true
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: null
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: "on"
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.patio_door_opening
window_delay_sec: 60
window_off_delay_sec: 30
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: "off"
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: true
auto_start_stop_enable: true
auto_start_stop_level: auto_start_stop_medium
auto_start_stop_dtmin: 15
auto_start_stop_accumulated_error: -2.4783321679166663
auto_start_stop_accumulated_error_threshold: 5
auto_start_stop_last_switch_date: "2025-06-07T21:51:23.010493+02:00"
is_over_climate: true
start_hvac_action_date: null
underlying_entities:
  - climate.nedervaning
is_regulated: true
regulated_target_temperature: 21
auto_regulation_mode: auto_regulation_medium
regulation_accumulated_error: -0.7785947391390785
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: false
friendly_name: LLVP
supported_features: 953
```

</details>
