### DISCUSSION TITLE
Is it possible to use an Aqara RTV E1 thermostat in combination with versatile thermostat with a heater switch?

### DISCUSSION THREAD

**Discussion by vrucht** [jmcollin78/versatile_thermostat#213] [Q&A]
Hi all,
I am a newby on Home Assistant and starting to learn the hang of it. I am not a coder so i am mostly dependent on info i get from this community. Please bare with me if i ask stupid questions or don’t exaclty know what the anwer is.

I have the following setup:

Home Assistant (latest version) with an Sonoff Zigbee stick over Z2MQTT.
A smart zigbee Thermostat Aqara E1
A central heater with an on/off switch
Use of versatile Thermostat with Window Sensor
A 4 channel zigbee switch (For every room one switch for easy coding) for our central heating
I want the following:

I have two Rooms that i want to heat independently
Every Room has a Aqara E1 thermostat that must be used to set the target temperature on the thermostat itself because the kids don’t have access to HA
Use the Algorithm of versatil thermostat to control my heater and door/window sensors.
If there is no demand for heat in a room, the thermostat must be closed by setting the target temp on the Aqara.
The issue that i am experiencing is, that i can’t make the setup to work in this configuration. The temperature set on the device, must be somehow copied to the verstatile target temperature, so that the versatil thermostat can activate the heater switch.
The other way arround should also work: When setting the target temp on versatile thermostat, the value must be set on the Aqara smart thermostat so the Aqare can close the valve in the radiator if there is no demand for heat. With this mechanism, i can control the heating of the rooms centrally and through automations.

I see that the attribute that i need in Z2mqtt is: “Ïnternal_heating_setpoint”

{
“away_preset_temperature”: “5.0”,
“battery”: 100,
“calibrated”: true,
“child_lock”: “UNLOCK”,
“device_temperature”: 23,
“internal_heating_setpoint”: 29,
“linkquality”: 54,
“local_temperature”: 21.5,
“occupied_heating_setpoint”: 29,
“power_outage_count”: 1,
“preset”: “manual”,
“schedule”: “OFF”,
“schedule_settings”: “mon,sun|0:00,21.0|12:00,17.0|18:00,21.0|23:59,21.0”,
“sensor”: “internal”,
“setup”: false,
“system_mode”: “heat”,
“valve_alarm”: false,
“valve_detection”: “OFF”,
“window_detection”: “OFF”,
“window_open”: false
}

This attribute should somehow be copied to the temperature attribute in versatile thermostat, but that attribute is not available in MQTT, HA and automations. I tried several pieces of code, but this is where my lack of knowledge comes in.
I hope that you all understand what i want, and can help me to get on track.

**Comment by jmcollin78** [comment]
Hello @vrucht ,

> The temperature set on the device, must be somehow copied to the verstatile target temperature, so that the versatil thermostat can activate the heater switch.

This is exactly what does an over_climate VTherm. You don't put the attributes of the VTherm so I can't tell what is wrong but his should work.

> When setting the target temp on versatile thermostat, the value must be set on the Aqara smart thermostat

This is also the behaviour of VTherm.

Please post your VTherm attributes so that I will be able to check if something is wrong (Development Tools / states / click on your VTherm / copy-paste the attributes with the code settings (button <> in the edit box).

EDIT: sorry I thinlk I don'y understand clearly you original post. The VTHerm is control the central switch and not the Aqara TRV itself. Is that true ? If yes with this setting nobody is controling the TRV. You should have a VTherm for each Aqara TRV you want to control and another mecanism to pilot the central heating switch. You can for example, have an automation that turn on the central heater when one the VTherm is heating. This can be done by checking the hvac_action of the VTherm (if 'heating', you turn on the central heater switch).

**Reply by vrucht** [reply]
Hello @jmcollin78 
Thanks for reaching out!

At first i had the VTHerm in "switch mode" to control the heating switch, but that didn;t work in combination with the TRV.
Now i am a bit further that i changed the VTHerm to "climate mode" and now i can control the VTH temperature with the TRV! So that works like you said.
For every TRV per room i will create a VTHerm with his own heating switch, thats why i bought a 4ch zigbee switch. Just to be fully independent in code per room. Those channels will be parallel with each other to control the heater.

Now, i have a working VTHerm, but now i have to write an automation that switches on the heater switch. Thanks to OpenIA i managed to create this code:

```
- id: '1700491064526'
  alias: Bram heater operation switch off/on
  description: ''
  trigger:
  - platform: state
    entity_id: climate.bram_slimme_thermostaat_aqara, sensor.bram_thermo_hygrometer_temperature
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ state_attr(''climate.bram_slimme_thermostaat_aqara'',
          ''temperature'') | float > states(''sensor.bram_thermo_hygrometer_temperature'')
          | float}}'
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.planken_lamp
        data: {}
      alias: 'Call a service ''Switch: Turn on'' on Planken lamp'
    - conditions:
      - condition: template
        value_template: '{{ state_attr(''climate.bram_slimme_thermostaat_aqara'',
          ''temperature'') | float < states(''sensor.bram_thermo_hygrometer_temperature'')
          | float }}'
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.planken_lamp
        data: {}
      alias: 'Call a service ''Switch: Turn off'' on Planken lamp'
  mode: single
```
It looks like it works, but i think ill stress my heater with going on/of to much in a short time when the target temp has been reached. Is this the way to go? Or am i bypassing the whole heating logic of VTHerm?

**VTherm attributes:**
```
hvac_modes:
  - "off"
  - heat
min_temp: 7
max_temp: 30
target_temp_step: 0.5
preset_modes:
  - none
  - eco
  - comfort
  - boost
current_temperature: 20.3
temperature: 16
preset_mode: none
is_on: true
hvac_action: null
hvac_mode: heat
type: null
eco_temp: 18
boost_temp: 20
comfort_temp: 19
eco_away_temp: null
boost_away_temp: null
comfort_away_temp: null
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: 9.9
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 20
saved_hvac_mode: null
window_state: "off"
motion_state: null
overpowering_state: null
presence_state: null
window_auto_state: "off"
window_bypass_state: false
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2023-11-21T09:39:00.861840+01:00"
last_ext_temperature_datetime: "2023-11-21T09:42:37.874034+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 0
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2023-11-21T09:42:37.881931+01:00"
timezone: Europe/Amsterdam
window_sensor_entity_id: binary_sensor.bram_raam_sensor_contact
window_delay_sec: 30
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: null
presence_sensor_entity_id: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
temperature_unit: °C
is_device_active: true
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.bram_slimme_thermostaat_aqara
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
friendly_name: Bram thermostaat
supported_features: 17
```

**Attributes TRV:**
```
hvac_modes:
  - "off"
  - heat
min_temp: 5
max_temp: 30
target_temp_step: 0.5
preset_modes:
  - none
  - manual
  - away
  - auto
current_temperature: 20.1
temperature: 16
preset_mode: manual
friendly_name: Bram slimme thermostaat Aqara
supported_features: 17
```

**Identity external temperature sensor in the room:**
`sensor.bram_thermo_hygrometer_temperature`

**Identity room sensor**
`binary_sensor.bram_raam_sensor_contact`

**Temporary switch for tesing heater switch**
`switch.planken_lamp`

Could you confirm my code is correct of help me finetune this setup?

Many thanks in advance.

**EDIT**
I compared the attributes of the VTherm when he is heating and when the VTherm is at for example 7 degrees. The only attribute that changes is "Temperature" so thats the only attribute that i can use to trigger a heating switch. The Hvac mode stays in "heat" mode even when there is no demand. 
See below, no demand for heat, RTV stil says HVAC "heat"
![noheat](https://github.com/jmcollin78/versatile_thermostat/assets/52583662/b207506a-4c58-4447-82b0-159cc0b400f6)

I would rather see that there were an attribute from the VTherm itself that is asking for heat. So that for example the burner stops 0,5 degrees before the room reaches target temperature. In my script the burner is being activated if the room is 0.1 degrees colder than the set temp, cause of the rough compare of two temperatures. So i would like to use the intelligence of VTherm, for controling the burner than a simple script. Or are my thaughts wrong?
