### DISCUSSION TITLE
temperature smoothing: ema implementation vs ha-average sensor

### DISCUSSION THREAD

**Discussion by maia** [jmcollin78/versatile_thermostat#250] [Show and tell]
I've compared the current EMA implementation of versatile_thermostat with the implementation being used in https://github.com/Limych/ha-average (installed via HACS) which creates sensors for average values. This implementation is better than the HA statistics sensor, as this will cause issues when the sensor does not report any new data for longer than the defined average time span (instead of assuming the temperature simply didn't change).

The `average` sensor is more exact and I wonder if this could help in improving versatile_thermostat too:

<img width="724" alt="Bildschirmfoto 2023-12-07 um 08 49 38" src="https://github.com/jmcollin78/versatile_thermostat/assets/9836/26c16b32-6298-4df8-9edf-f44f581640d4">

Here's the configuration I've been using:
```
sensor:
  - platform: average
    name: "bedroom smoothed temperature"
    unique_id: "bedroom_smoothed_temperature"
    entities:
      - sensor.bedroom_govee_temperature
    duration:
      minutes: 2
    precision: 2
```
