### DISCUSSION TITLE
Setting preset mode from a script?

### DISCUSSION THREAD

**Discussion by nimonimonimo** [jmcollin78/versatile_thermostat#262] [Q&A] [answered]
Hi,

In my setup I have configured 3 different thermostats each one with the same two presets:
 - Eco: temperature at 10C
 - Comfort: temperature at 20C

On the dashboard I have created two buttons:
 - Set all thermostats to Eco
 - Set all thermostats to Comfort

These buttons I have setup to activate a script. I have figured out how to set temperature of "Eco"-mode to any given temperature from a script -- but I cannot figure out how to change which preset mode that are in effect for a given thermostat via a script.

Could anyone point me in the right direction?

Thanks in advance!

**Comment by diplix** [comment, marked as answer]
```
      - service: climate.set_preset_mode
        data:
          preset_mode: comfort # or eco or boost
        target:
          entity_id: climate.your_climate_device
```
