### DISCUSSION TITLE
Automatic fanmode

### DISCUSSION THREAD

**Discussion by Edwintenhaaf** [jmcollin78/versatile_thermostat#394] [Show and tell]
I had some issues maintaining a steady temperature during heating with the versatile thermostat in combination with our airconditioners.

Using 'auto regulation' with expert settings and using 'Use internal temperature of the underlying' 
```
versatile_thermostat:
      auto_regulation_expert:
          kp: 0.25
          ki: 0.05
          k_ext: 0.1
          offset_max: 1
          stabilization_threshold: 0.1
          accumulated_error_threshold: 20
```
<img width="421" alt="image" src="https://github.com/jmcollin78/versatile_thermostat/assets/51457250/eec39b0b-d03f-431d-b947-9be681ee329b">

The fanmode I used was Auto
Before I used the versatile thermostat I had experimented with auto fanmode to adjust the mode based on the temperature offset.
I decided to reintroduce this and it helped a lot to keep a steady temperature.

The script itself is triggered when the room temperature changes
```
platform: state
entity_id:
  - sensor.toon_room_temp_for_ac_woonkamer
id: temp-change
```
First it calculates the fanmode based on the diffrence between the target temperature and the room temperature.
```
variables:
  fanmode: >-
    {% set ac_temp = state_attr('climate.woonkamer', 'temperature') %}   {% set
    room_temp = states('sensor.woonkamer_climate_temp') | float %}   {% set diff
    = (room_temp - ac_temp) | round(1) %} {% set fanmode = 'Auto' %} {% if
    states('select.woonkamer_ac_openhaard_modus') | contains('fireplace_1') %}
        {% set fanmode = 'Medium' %}
    {% elif diff <= -1.0 %}
        {% set fanmode = 'High' %}
    {% elif diff <= -0.5 %}
        {% set fanmode = 'Medium High' %}
    {% elif diff <= -0.1 %}
        {% set fanmode = 'Medium' %}
    {% elif diff >= 0.5 %}
        {% set fanmode = 'Quiet' %}
    {% elif diff >= 0.3 %}
        {% set fanmode = 'Low' %}
    {% elif diff >= 0 %}
        {% set fanmode = 'Medium Low' %}
    {% endif %} {{ fanmode }}
```
it should look like this in your automation:
<img width="1002" alt="image" src="https://github.com/jmcollin78/versatile_thermostat/assets/51457250/de166656-1abc-45c8-9ece-24c2acca5cc7">

Change the defined fanmodes with the one's used with your ac
Check the attribute fanmode of you're real ac device (Developer tools > States)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/51457250/80e8d8f7-61cc-43e8-b6d1-7d63c7f09073)

You can test the variable in Developer tools > template

Based on this variable a service action is used to set the fanmode
```
alias: Fanmode
if:
  - condition: template
    value_template: "{{ state_attr('climate.woonkamer','fan_mode') != fanmode}}"
    alias: Apply only if diffrent
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.woonkamer
        state: "off"
  - condition: template
    value_template: "{{ state_attr('climate.woonkamer','fan_mode') != 'Auto'}}"
    enabled: true
then:
  - service: climate.set_fan_mode
    data:
      fan_mode: "{{ fanmode }}"
    target:
      entity_id: climate.woonkamer
enabled: true
```
<img width="998" alt="image" src="https://github.com/jmcollin78/versatile_thermostat/assets/51457250/198ddfdf-bec8-4691-acce-432e95f75c73">

AC with fanmode automation
<img width="416" alt="image" src="https://github.com/jmcollin78/versatile_thermostat/assets/51457250/d804cc45-ebe8-430c-bcaa-e61c16159b28">

Hope this will help you too.

**Comment by jmcollin78** [comment]
Hello @Edwintenhaaf ,

Thank you for sharing.

I wonder why the native 'auto-fan mode' of VTherm doesn't work. It does exactly the same kind of calculation but with fewer cases.
Do you think, adding more cases does a significant change ?

Other thing : this will not work in Cool mode (if your device is able to do it).

**Reply by Edwintenhaaf** [reply]
Hi @jmcollin78 , 

Because then I have to set the airconditioner in auto mode and it will calculate the fan speed based on the offset between the device target temperature and measured temperature.
The response when using auto mode on the device was also to slow so I had lots of oscilation. Now it's more stable.
I think that users with airconditioners could benefit when adding more cases to the native fanmode but it depends on you're specific situation.

I also noticed that when the airconditioner stops heating because target temperature is reached the outside unit stops heating.
If the room temperature drops and it is triggered to start heating this can take some time before warm air is coming out of the unit.
So the challenge is to heat just enough to keep the outside unit running.

Defrosts are also a challenge because there is a significant temperature drop.
Currently I am setting the central heating we have 0.5 below the climate device target temperature to solve this.
Don't want to use to much gas because it's much more expensive than heating with electricity(solar and grid)

I had turned the native fanmode on but I never seen it been triggered. 
What is the offset before it kicks in ?

I understand that this does not work in cool mode but that's another challenge I will face when summer arrives.
Allready built-in in the auto fanmode automation as a condition that it will not run.
```
condition: or
conditions:
  - condition: state
    entity_id: sensor.season
    state: autumn
  - condition: state
    entity_id: sensor.season
    state: winter
```
