### DISCUSSION TITLE
Using VT with Diyless Opentherm controller

### DISCUSSION THREAD

**Discussion by johnbur1** [jmcollin78/versatile_thermostat#450] [Q&A] [answered]
Hi, I currently use VT central boiler to switch a Shelly relay to control the boiler on/off. To avoid too much modulating, I would really like to control the boiler by OpenTherm instead.
I have purchased one of these:
[https://diyless.com/product/opentherm-thermostat2#connection]
Before I start trying to work it out, has anyone got the two integrations working together already?

**Comment by tbrasser** [comment, marked as answer]
I am using opentherm on esphome, what I do is take all vtherms (with attribute used_by_central_boiler=true) and get the one with the highest demand (biggest delta between current and target temperature) and set those current & target temperature on my central boiler opentherm esphome thermostat. 
So I actually don't use the other functionality provided by versatile thermostat when it comes to the central boiler, just to filter which ones I should consider for using as a reference for my central boiler thermostat settings.

I also use motion/acticity to toggle between climate/eco (20/15 degrees C).

**Reply by johnbur1** [reply]
@tbrasser - that makes perfect sense - many thanks for saving me a few headaches.

**Reply by tbrasser** [reply]
No worries, still optimizing myself. I've trying to limit the output power of my ch boiler to 50% (because I'm trying to verify my feeling that the thing is way too big, in preperation for dimensioning a full electric heatpump system) by limiting the output of the opentherm / pid climate heat output signal to 50%, but it's not working. Also since the boiler already modulates based on return temperature, and the vtherms (and maybe some of the underlyings) have some minimum cycle, I set to 0 the integral and derivative terms on the opemtherm/pid esphome thermostat, leaving only the proportional term (0.4 as of writing).

currently using https://github.com/rsciriano/ESPHome-OpenTherm 

But I think https://github.com/FreeBear-nc/esphome-opentherm should be better, allthough I had reboot & no-sustained-dhw issues trying that out a couple of months ago.

**Reply by alibaba56734** [reply]
@tbrasser 

> what I do is take all vtherms (with attribute used_by_central_boiler=true) and get the one with the highest demand (biggest delta between current and target temperature) and set those current & target temperature on my central boiler opentherm esphome thermostat.

Did you write an automation for this? Would you mind sharing the code? I am now using an integration called zoned heating, but it is not functioning properly.

**Reply by tbrasser** [reply]
I use 2 template sensors (helpers):

current:

```jinja2
{% set source = states.climate | selectattr('attributes.ema_temp','defined') | list %}
{% set ns = namespace(result=[]) %}
{% for item in source %}
  {% set delta = item.attributes.temperature - item.attributes.current_temperature %} 
  {% set ns.result = ns.result + [[item.entity_id, delta, item.attributes.current_temperature ]] %}
{% endfor %}
{{ ns.result | sort(attribute=1) | last | last }}
```

target:

```jinja2
{% set source = states.climate | selectattr('attributes.ema_temp','defined') | list %}
{% set ns = namespace(result=[]) %}
{% for item in source %}
  {% set delta = item.attributes.temperature - item.attributes.current_temperature %} 
  {% set ns.result = ns.result + [[item.entity_id, delta, item.attributes.temperature ]] %}
{% endfor %}
{{ ns.result | sort(attribute=1) | last | last }}
```

**Reply by tbrasser** [reply]
The current temperature one is directly used by the esphome opemtherm thermostat:

```yaml
sensor:
  - platform: homeassistant
    id: temperature_sensor
    entity_id: sensor.current_for_cv
    filters: 
      # Push room temperature every second to update PID parameters
      - heartbeat: 1s  
    name: "Actual temperature"
    unit_of_measurement: °C
```

The target one I created an automation that triggers on the template sensor then sets that value on the central thermostat:

```yaml
alias: sync cv
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.target_for_cv
condition: []
action:
  - service: climate.set_temperature
    target:
      entity_id: climate.opentherm_central_heating
    data:
      temperature: "{{ states('sensor.target_for_cv') }}"
mode: single

```
