### DISCUSSION TITLE
Question on security_state internal operating / Comment fonctionne le basculement de security_state ?

### DISCUSSION THREAD

**Discussion by fguiet** [jmcollin78/versatile_thermostat#456] [Q&A]
Hi / Bonjour,

Not an issue but rather a question / pas un problème mais plutôt une question

Not sure to understand how security_state goes from false to true / Pas sur d'avoir compris comment security_state passe de faux à vrai

Current date/time is 16h24 pm so I was thinking that security_false would be true... / Il est 16h24 j'aurai pensé que security_state voudrait true car on a dépassé les 5 minutes dans nouvelles du capteur de température

What I am missing ? / Qu'est ce que je ne comprends pas?

```yaml
security_delay_min: 5
last_temperature_datetime: 2024-05-02T15:38:37.527386+02:00 
security_state: false
```

Current values

```yaml
hvac_modes: heat, off
min_temp: 7
max_temp: 25
target_temp_step: 0.1
preset_modes: none, frost, eco, comfort, boost
current_temperature: 20.2
temperature: 19
hvac_action: idle
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 7
eco_temp: 7
boost_temp: 7
comfort_temp: 7
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 11.5
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 17
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 5
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-05-02T15:38:37.527386+02:00
last_ext_temperature_datetime: 2024-05-02T16:16:58.099108+02:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1000
mean_cycle_power: 0
total_energy: 7898.32
last_update_datetime: 2024-05-02T16:16:58.099676+02:00
timezone: Europe/Paris
temperature_unit: °C
is_device_active: false
ema_temp: 20.26
is_used_by_central_boiler: false
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_switch_0: switch.office_heater_switch
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
friendly_name: Thermostat radiateur Bureau
supported_features: 401
```

Merci,
frederic
