### DISCUSSION TITLE
Max duration for Boost preset

### DISCUSSION THREAD

**Discussion by phd1963** [jmcollin78/versatile_thermostat#495] [Ideas]
Is it possible to add a 'max_boost_time' or equivalent to boost preset ?
This to avoid forgetting to return to previous preset and continue heating indefinitely.

Thanks

**Comment by thejob78** [comment]
I have the same need!
thanks!

**Comment by lordcoxis** [comment]
I also have the same need and implemented an automation for this, but it sure would be nice to have it built-in...

**Reply by jmcollin78** [reply]
> I also have the same need and implemented an automation for this, but it sure would be nice to have it built-in...

If you can share your automation it could be great for the others.

**Comment by lordcoxis** [comment]
Sure, it's not much - it doesn't work if HA is restarted in the middle, for example:

```
alias: Climate Boost OFF TIMER
description: 30 mins Boost Timer
triggers:
  - trigger: state
    entity_id:
      - climate.suite
      - climate.wc_suite
      - climate.living_room
      - climate.dining_room
      - climate.kitchen
      - climate.hall
      - climate.office
    attribute: preset_mode
    to: boost
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - if:
      - condition: template
        value_template: "{{ is_state_attr(trigger.entity_id, 'preset_mode', 'boost') }}"
    then:
      - data:
          entity_id: "{{ trigger.entity_id }}"
          preset_mode: "{{ trigger.from_state.attributes.preset_mode }}"
        action: climate.set_preset_mode
mode: parallel
```
