### DISCUSSION TITLE
Thermostat continue its heating cycle whatever the setpoint is,  even when disabled.

### DISCUSSION THREAD

**Discussion by KipK** [jmcollin78/versatile_thermostat#547] [Q&A] [answered]
## Configuration

Using Versatile with electric heaters using pilot wire modules.
I have a switch template for each device, going from antifrost to confort.

My VTherm attributes are the following:
```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 23
target_temp_step: 0.5
friendly_name: Thermostat SdB
supported_features: 401
current_temperature: 19.6
temperature: 7
hvac_action: heating
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
preset_mode: frost
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 7
eco_temp: 18
boost_temp: 21
comfort_temp: 19
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: 15
target_temperature_step: 0.5
ext_current_temperature: 16.05
ac_mode: false
current_power: 400
current_power_max: 9000
saved_preset_mode: frost
saved_target_temp: 7
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: sensor.linky_puissance_inst_no_evse
max_power_sensor_entity_id: sensor.linky_pcoup_marge_evse
overpowering_state: false
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: binary_sensor.ouverture_sdb
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
window_action: window_frost_temp
security_delay_min: 30
security_min_on_percent: 0.1
security_default_on_percent: 0
last_temperature_datetime: "2024-10-11T14:44:19.356048+02:00"
last_ext_temperature_datetime: "2024-10-11T14:35:32.771625+02:00"
security_state: false
minimal_activation_delay_sec: 60
device_power: 560
mean_cycle_power: 0
total_energy: 71.86
last_update_datetime: "2024-10-11T14:49:12.189119+02:00"
timezone: Europe/Paris
temperature_unit: °C
is_device_active: true
ema_temp: 19.58
is_used_by_central_boiler: false
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_switch_0: switch.switch_rad_sdb
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 420
cycle_min: 7
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.02
```
I got this problem 3 times with 3 different thermostat this week. ( I have only started to test Versatile Therm this week ) 

Sometime, the thermostat still continue the heating cycle and never stop. 
When it's in this bugged state, I try to put the setpoint to a really low temperature, or set anti frost mode, the thermostat instantely cut off the heating. But a few mn later, I can see the heater is back on. 
It's the same if I set it to OFF. Heating continue in cycling state to a previously setted temperature ( on the example below it was 19.5°C )

Here on the screenshot below you can see at the beginning it was already still maintaining a 19.5°C temp on the room with a 18°C setpoint on the thermostat. ( it was already in this bugged state ) .
At 13h20 I set the thermostat to anti-frost mode. 
But the heating cycle continue whatever the temperature was set.

![versatile](https://github.com/user-attachments/assets/96378b95-a0f0-49f0-8e8d-43d6006db990)

Disabling the integration and enabling it don't solve the problem. 
But restarting Home assistant does.

## Debug log

The related thermosatt is "thermosatt_sdb"

Complete log for the timeframe  here:
[home-assistant_versatile_thermostat_2024-10-11T12-39-35.156Z.txt](https://github.com/user-attachments/files/17342952/home-assistant_versatile_thermostat_2024-10-11T12-39-35.156Z.txt)

**Comment by KipK** [comment]
As I'm in a testing phase for now, there's chance this issue wakes up after I've modifed some Versatile settings. But I can't confirm that yet. Perhaps a home assistant restart each time I change a parameter would avoid this.

**Comment by jmcollin78** [comment]
> As I'm in a testing phase for now, there's chance this issue wakes up after I've modifed some Versatile settings. But I can't confirm that yet. Perhaps a home assistant restart each time I change a parameter would avoid this.

No don't do this. That is not necessary.

What I see the first post, is that VTherm is not heating:
```
on_percent: 0
power_percent: 0
on_time_sec: 0
```
your heater is still heating I think you have to look at your virtual switch `switch.switch_rad_sdb`. I guess this is virtual switch ?

> It's the same if I set it to OFF.

With OFF, this is not possible for VTherm to send command to the underlying. You have to look elsewhere.

**Comment by KipK** [comment]
The template switch works ok. I've double checked and tested it first before using it 
But in bugued state , even with the thermostat disabled, the zigbee module still continue to receive ON/OFF commands from hass and regulates the temperature like you can see in the screen capture in orange, but locked on a previous setted temp. 
There's nothing else that can send switch commands to z2m than versatile on my setup. 

Also when removed the Versatile integration, the heaters stopped to received those ghost commands.  It clearly comes from it.

**edit**: you can also see the temp is well regulated at 19.5° ( when in anti frost mode in bugued state ), if it was randomly switching the curve wouldn't look  this stable.

**Comment by KipK** [comment]
However, I was using the normal switch from the pilot wire zigbee device before and got the same issue. I've changed to the template switch as I plan to mods my Lexman module with NodOn firmware ( those have no such switch internally but just climate commands )

**Comment by jmcollin78** [comment]
I guess the change of parameter have created another VTherm leave the old running in background.
I can't even thing how it is possible due to HA config entry behavior, but it seems to be the case.

Is this issue still present after a restart ? Does this reproduce after each change of parameters ?

**Comment by KipK** [comment]
That has sense and is coherent with what I've observed. I don't know well enough HASS code structure yet, but I'd like to add some debug trace on the different Versatile functions to track down what's happening in the background. 

Will take me a bit of time to be comfortable with your codebase first.

Yes a home assistant restart solve the issue, not a restart of the integration ( disabling, enabling all the thermostats )

It doesn't seems to be systematic at each conf change ( not sure yet, but I haven't noticed that ) btw, so won't be an easy find.

**Comment by jmcollin78** [comment]
> debug trace on the different Versatile functions to track down what's happening in the background

Be careful, the debug mode is very verbose. It could degrade you sd-card if you have one.

I transform this issue into conversation to have a follow up.

**Comment by KipK** [comment]
Sure that, but all my logs are recorded on a HDD to prevent SSD wearsout.  SSD is never used for that. I have a proxmox server with different vms and lxc, but all my containers and vm have an hdd mount points for frequent writes ( mostly /var on vms, and logs + databases for containers.

**Comment by KipK** [comment]
Après quelques tests succins en 6.3.4, ca m'a l'air beaucoup mieux. 
Bon il faut chaud alors je peux pas tester sur de longues durées, mais ca va se rafraichir dans les jours à venir.

**Reply by jmcollin78** [reply]
Je pense que ça n'a rien à voir avec la 6.3.4 mais avec un restart complet. J'ai rien corrigé qui pourrait expliquer ton cas

**Comment by candale** [comment]
I think I might be experiencing something similar. I have the folliwing thermostat configuration:
**Thermostat config**
<details>

```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 35
target_temp_step: 0.1
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 22.2
temperature: 21
hvac_action: idle
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 7
eco_temp: 21
boost_temp: 27
comfort_temp: 22
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 14.7
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 22.2
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 180
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-10-17T14:58:08.433710+03:00"
last_ext_temperature_datetime: "2024-10-17T14:57:32.829408+03:00"
security_state: false
minimal_activation_delay_sec: 180
device_power: 1
mean_cycle_power: 0
total_energy: 10.86
last_update_datetime: "2024-10-17T14:58:08.449641+03:00"
timezone: Europe/Bucharest
temperature_unit: °C
is_device_active: false
ema_temp: 22.26
is_used_by_central_boiler: false
is_over_switch: true
is_inversed: false
keep_alive_sec: 60
underlying_switch_0: input_boolean.small_bedroom_heating_switch
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 1800
cycle_min: 30
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0
friendly_name: Small Bedroom Virtual Thermostat
supported_features: 401
```
</details>

Even though the setpoint is way lower than the actual temperature in the room, the thermostat periodically runs: https://imgur.com/Iy79OkI.png. Way more visible here: https://imgur.com/ShTkzfl.png

There are the logs for one of the recent events:
```
2024-10-17 13:59:27.421 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Master Bedroom Virtual Thermostat-input_boolean.master_bedroom_heating_switch - stop heating (2) for 30 min 0 sec
2024-10-17 14:00:00.002 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Small Bedroom Virtual Thermostat - Set target temp: 21.0
2024-10-17 14:08:36.160 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Master Bedroom Virtual Thermostat-input_boolean.master_bedroom_heating_switch - stop heating for 20 min 51 sec
2024-10-17 14:16:00.175 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Small Bedroom Virtual Thermostat-input_boolean.small_bedroom_heating_switch - stop heating for 12 min 9 sec
2024-10-17 14:28:09.177 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Small Bedroom Virtual Thermostat-input_boolean.small_bedroom_heating_switch - start heating for 17 min 50 sec
2024-10-17 14:28:54.638 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Small Bedroom Virtual Thermostat-input_boolean.small_bedroom_heating_switch - stop heating (2) for 30 min 0 sec
```

**Comment by bwip** [comment]
First, thank you for the awesome work you did here. 

I had a similar situation during the cooldown over night, the thermostat keeps activating.:

First I thought this may be related to the external boost term in the proportional algorithm, which is added always, regardless if delta_temp is below zero (no heating required) :

![image](https://github.com/user-attachments/assets/3cac69a6-259d-4ef2-9fde-1eb4b9cf3e57)


            if self._function == PROPORTIONAL_FUNCTION_TPI:
                self._calculated_on_percent = (
                    self._tpi_coef_int * delta_temp
                    + self._tpi_coef_ext * delta_ext_temp
                )

e.g: delta_temp = -1
delt_ext_temp = 7 
_tpi_coef_int  = 0.6
_tpi_coef_ext = 0.01
calculated_on_percent = -1 * 0.6 + 7 * 0.01 = -0.53

But in my case the on percent is way below 0. 

I played around in HA a lot this day, so I keep watching for now.

**Reply by jmcollin78** [reply]
the `on_percent` is 0 when we don't need to heat. Where is the issue ?

**Comment by jmcollin78** [comment]
Hello all,

If you experience this, you should post the following attributes (Development Tools / State):
```
current_temperature: 21
temperature: 20
ext_current_temperature: 13.4
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 420
cycle_min: 7
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
```

All of these parameters are used for TPI calculation and you have the TPI calculation result in `on_percent` value.

Then you should be able to do as @bwip does, do the calculation yourself and check if it the result is good.
You can use this formula: tpi_coef_int * (temperature - current_temperature) + tpi_coef_ext * (temperature - ext_current_temperature)

When this occurs please check also that the VTherm is not in 'safety mode'(badly named security state with the attributes:
```
security_delay_min: 60
security_min_on_percent: 0.7
security_default_on_percent: 0.4
last_temperature_datetime: "2024-10-26T10:18:30.460035+02:00"
last_ext_temperature_datetime: "2024-10-26T10:08:01.058713+02:00"
security_state: false
```
If the VTherm is in a safety, then a minimal `security_default_on_percent` is applied. This can explain what you observe.

**Reply by deeploz** [reply]
I'm facing a very similar situation.
![image](https://github.com/user-attachments/assets/51434d9d-5e1e-4fbb-91fe-37c9d93f725f)

The VTherm triggers a heating cycle at 19:00 (which is normal, actual T°< VTherm T°), but the cycle then continue perpetually, even after the change of the T° target at 22:00, going from 19°C to 17°C (so with an actual T° more than 2°C above the target), and despite the fact that `on_percent` is null. Cycles are never ending, until I manually switch off the VTherm.

TPI Formula result in a negative value (-1,488) which make sense : there is no need to heat the room.

The periodicity is 30 min, which is the value of `cycle_min`. So it may looks like the "safety mode" cycle, however the `security_state` is `false`.

Important note : I've 8 other VTherm configured (all are based on physical sensors : SonOff SNZB-02D). All of them works perfectly most of the time. But each day, one or two of them, randomly (not always the sames each time), are entering in this neverending cycles.

here is the conf :
```
hvac_modes: heat, off
min_temp: 7
max_temp: 21
target_temp_step: 0.5
preset_modes: none, frost, eco, comfort, boost
current_temperature: 18.9
temperature: 17
hvac_action: idle
preset_mode: eco
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 7
eco_temp: 17
boost_temp: 21
comfort_temp: 19
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: 15.4
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 19
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: 30
window_auto_enabled: true
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-10-28T10:58:52.827207+01:00
last_ext_temperature_datetime: 2024-10-28T11:09:04.532444+01:00
security_state: false
minimal_activation_delay_sec: 60
device_power: 2000
mean_cycle_power: 0
total_energy: 1010
last_update_datetime: 2024-10-28T11:31:09.932148+01:00
timezone: Europe/Paris
temperature_unit: °C
is_device_active: false
ema_temp: 18.86
is_used_by_central_boiler: false
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_switch_0: switch.fp_sejour_sam
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 1800
cycle_min: 30
function: tpi
tpi_coef_int: 0.8
tpi_coef_ext: 0.02
friendly_name: Thermostat_sejour_sam
supported_features: 401
```

**Reply by jmcollin78** [reply]
> I'm facing a very similar situation.

Even after a restart ?

**Reply by deeploz** [reply]
I've restarted many times. A restart is resetting the existing neverending cycles, if any. However it does not prevent the apparition of another neverending cycle, somewhen after this restart.

**Reply by KipK** [reply]
That I haven't tested long enough to notice this as I had to switch back temporarly to my previoius setup awaiting to find a solution for my load shedding ( délestage ).  Current load shed versatile implementation doesn't fit my needs and I'm still on study phase on how I will do that with HA.

**Reply by jmcollin78** [reply]
> I've restarted many times. A restart is resetting the existing neverending cycles, if any. However it does not prevent the apparition of another neverending cycle, somewhen after this restart.

Do you mean that even if you don't change any configuration of VTherm the "Ghost" VTherm reappears itself ?
I think (and I hope) not. The case seems to be, when you change a configuration of a VTherm, the "old" is still running with the old parameters. Without any changes in configuration, you should not experience this.

**Reply by deeploz** [reply]
> Do you mean that even if you don't change any configuration of VTherm the "Ghost" VTherm reappears itself ? I think (and I hope) not. The case seems to be, when you change a configuration of a VTherm, the "old" is still running with the old parameters. Without any changes in configuration, you should not experience this.

I'm not sure I understand what you mean by "Ghost VTherm reappears itself". I do not have any Ghost VTherm. I have a set of VTherm (one by room), and some of them are, randomly, entering in a state where the radiator is heating in a never-ending cycle, which is not required as the Target Temp is way below the actual Temp (as per the screen capture [in my post above](https://github.com/jmcollin78/versatile_thermostat/discussions/547#discussioncomment-11073606)). And I meant that if I restart HA, it reset the behaviour of the defective VTherm to a normal state (the expected one).

So restarting is fixing the symptom, but not the root cause : eventually theses unexpected heat cycles will reappear.

**Reply by jmcollin78** [reply]
@deeploz , @KipK 

there was a non reproductible bug that let a Vtherm running in background after a reconfiguration. The symptoms are exactly the same as you describe:  event of the target temp is reach, the Vtherm continue to heat at each cycle.
But after a restart this "ghost" vtherm disappear.
So if you have restarted, this is not your case.

@deeploz when I look at your graph and at your attributes this seems not in correspondance. Temperatures in attributes are:
```
current_temperature: 18.9
temperature: 17
```
but not in the graph.
Are you sure you take the attributes during the issue ? In the right Vtherm ?
It is important for diag to have the attribute WHEN the issue occurs.

To have more informations, you can activate the logs in debug in the TPI algorithm with this lines in the logger.yaml file:
```
default: warning
logs:
  custom_components.versatile_thermostat.prop_algorithm: debug
  custom_components.versatile_thermostat: info
```

This should enable logs in the TPI algo and please send me this logs when the problems occurs
