### DISCUSSION TITLE
Thermostat heating while being well above target temperature already

### DISCUSSION THREAD

**Discussion by blemasle** [jmcollin78/versatile_thermostat#682] [Q&A] [answered]
Hi,

I set up versatile thermostat in my bathroom. For a few days, everything seems to go according to plan / schedule. Then this evening it decided to heat despite being well above the target temperature
![image](https://github.com/user-attachments/assets/2a9ac307-fab8-47ea-bdd6-73db625c63d5)

Could someone explain to me what's going on ? Why is it heating when it is already 2°C above the target temperature ? Is it because of the previous down slope and it tries to prevent such a slope to induce oscillations around the target temperature ?

![image](https://github.com/user-attachments/assets/45169114-6605-48a1-a449-6a2fc6b8ead3)
![image](https://github.com/user-attachments/assets/e393a7c6-8ef5-41c2-9dbd-0b377276ecae)

Thanks !

**Comment by jmcollin78** [comment]
Hello @blemasle ,

We will need you configuration and setup. Please gives what is described here: https://github.com/jmcollin78/versatile_thermostat/blob/main/README.md#custom-attributes

and here: https://github.com/jmcollin78/versatile_thermostat/blob/main/README.md#even-better-with-plotly-to-tune-your-thermostat

**Reply by blemasle** [reply, marked as answer]
Hi,

Here you are :) 

```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 35
target_temp_step: 0.1
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 19.4
temperature: 19.5
hvac_action: idle
preset_mode: comfort
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: Auto
frost_temp: 7
eco_temp: 18.5
boost_temp: 22
comfort_temp: 19.5
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 6.5
ac_mode: false
current_power: 4014
current_power_max: 10000
saved_preset_mode: comfort
saved_target_temp: 22
saved_hvac_mode: heat
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: sensor.heating_power
max_power_sensor_entity_id: input_number.max_power_consumption
overpowering_state: false
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 70
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-12-03T20:04:52.181615+01:00"
last_ext_temperature_datetime: "2024-12-03T20:07:33.236359+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: 0.19
total_energy: 16.96
last_update_datetime: "2024-12-03T20:41:09.125393+01:00"
timezone: Europe/Paris
temperature_unit: °C
is_device_active: false
ema_temp: 19.32
is_used_by_central_boiler: false
temperature_slope: 0.04
hvac_off_reason: null
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_entities:
  - input_boolean.heater_bathroom
on_percent: 0.19
power_percent: 19
on_time_sec: 57
off_time_sec: 242
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
friendly_name: Bathroom thermostat
supported_features: 401
```

![image](https://github.com/user-attachments/assets/0804a973-adec-4cba-ae88-19298800191f)

If I'm reading this right, as far as the thermostat is concerned the heater is off (no `Power percent` on the 3 distinct periods). I also noticed that the faulty heating periods (past 12:30) does not match the usual heating strategy of versatile thermostat (6:00 to 9:30). 🤔 .

![image](https://github.com/user-attachments/assets/469b16ed-0201-4623-a701-fdcb157c47fc)


Maybe the control module didn't actually set the pilot wire to "off", and the heater staid on "comfort" during all that time ?
Thanks
