### DISCUSSION TITLE
Switching Vterm from Manual mode to Schedule mode

### DISCUSSION THREAD

**Discussion by tgerardy** [jmcollin78/versatile_thermostat#695] [Q&A]
Hi, first of all, kudos to JM for the amazing work on this integration. I started using it with some of my electric heaters using the VT over switch setup. It worked great. My main heating system runs with a gas boiler and 10 water radiators, 8 with with TRVs. My TRVs being Sonoff TRVZB, I was still using BT integration since I felt the temperature adjustment of the underlying thermostat via calibration offset was a cleaner way to manage these TRVs. The latest release of VT developped with some specifics for TRVZBs made me switch to VT for all TRVs as well. I have been using it for few days and I love the ability to control these TRVs via valve opening %. This, plus the inflight temperature calibration offset are making me very happy about the setup so far. Really great work and thank you.

My question:
In my setup, I am using the VT climate card and the scheduler card. All my VTs are following schedules using presets. When using the VT climate card, is there a way to see if the VT is currently in manual mode or following schedule? Example: If I am adjusting the temperature with +/-, the preset gets unselected (normal behavior). But if I want to switch back to schedule mode, I need to remember what is the schedule preset for the current time and select it. I thought the Auto mode was designed for that but one, I don't have auto mode for VT over switch and second, Auto mode for over climate switch TRVZBs in their own Auto mode which make them follow a schedule that is coded within the TRV. Any idea?

Regards

Thomas

**Comment by jmcollin78** [comment]
Hello @tgerardy ,

First, thank you for the compliments. It is always a pleasure.

> see if the VT is currently in manual mode

You can see that in the VTherm UI card when no preset are highlighted. That mean you are in manual mode.

The preset will be set by the Scheduler, the next time there is a change. That is how, you can use it.
If you want to restore the old preset, you should have an attribute named 'saved_preset_mode' with the old preset mode. Then you should be able to restore it via an automation.

**Comment by tgerardy** [comment]
Understood. A 2 way interaction with scheduler would be super nice but I understand this is not straight forward.
In a different subject you explain the way to set a boost in a simple way, starting with disabling schedule. The only problem I see is that, typically, a schedule is set for several thermostats in same type of rooms (bathrooms, bedrooms, office rooms, living rooms,…). When disabling a schedule, you are likely to disable it for several rooms while the boost is for the specific room. But this is more a sheduler card discussion which would benefit from having a central config setup (like you have for VT)+ each room their own schedule based on central schedule.
My point is, you have developped a very sophisticated thermostat that works for most cases. A better integration with schedule would make it a killer integration. What we miss in Home Assistant at the moment for thermostat and heating system in general is the user friendly interface that allow anyone at home to control the system (room temp, boost timer, schedule,..) without a degree in automation. Tado is the benchmark for this aspect but pricy, only covering water radiator and of course not open source. Anyhow, easy to say and we are getting there. You certainly contribute to that. Thank you.

**Reply by jmcollin78** [reply]
> A better integration with schedule would make it a killer integration.

This is something oftenly asked but very, very difficult and the result will be poor compared to what Scheduler offers.

**Comment by kvanbiesen** [comment]
i made something for that. Its an automation: If you change the thermostat by manually switching the knob, after 15 minutes, it reverts to the latest preset. Addjust time as needed and change devices at the top

```
alias: Reset ManualVTherm Change
description: ""
triggers:
  - trigger: state
    entity_id:
      - climate.bedroom_vtherm
      - climate.living_room_vtherm
      - climate.bedroom_2_vtherm
      - climate.bathroom_vtherm
      - climate.kitchen_vtherm
    attribute: preset_mode
    to: none
    for:
      hours: 0
      minutes: 15
      seconds: 0
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
    enabled: false
  - metadata: {}
    data:
      preset_mode: "{{state_attr(trigger.entity_id,'saved_preset_mode')}}"
    target:
      entity_id: "{{ trigger.entity_id }}"
    action: climate.set_preset_mode
mode: queued
max: 10
```


for better integration with the scheduler; create a input select helper. On chhange of that, update all vtherms with the same preset. Works fine with schedular card. With the inclusion of the on/off feature in VTherm, i can easiely udpate as needed.
