### DISCUSSION TITLE
Boiler is on but valves are closed (on_climate with valve control)

### DISCUSSION THREAD

**Discussion by PokePango** [jmcollin78/versatile_thermostat#723] [Q&A] [answered]
Hello everyone!

As the title suggests, I'm encountering issues my setup. I'm a new user so this is a first installation for me !

I have TRV on my radiators (sonoff TRVZB) and my heater is an old gas boiler (1990) so I'm using it with a switch, it's not a climate entity.

As suggested in the documentation I have setup the TRV using valve control as the underlying. It's been 2 days and what I noticed is that sometimes the boiler will heat although none of the TRV is asking for heat (especially during the night).

I'm not sure how my boiler behave in this situation, as I said it's old and it's hard to guess how it will self regulate with all radiators closed and it's a situation I'd like to avoid.

It might be linked to my setup but I'm unsure what parameters to look at, do you have any suggestions? What logs should I look at to understand what triggered the switch event? Thanks!

**Comment by jmcollin78** [comment]
Hello @PokePango ,

The first think you should do is to inform us how you have configured your installation. I understand you have Sonoff TRVZB with Valve regulation.
Do you have configured the central boiler feature ? If yes, give us your configuration attributes (Dev Tools / States)
How is you central boiler supposed to work ? Was it working fine before VTherm ?

**Comment by PokePango** [comment]
Thank you Jean-Marc for your quick reply.

Yes I have configured central boiler. I'm not sure which entity to look for but I've dumped some examples below.

My boiler still works, it's just that VTherm triggers the heater (`switch.chaudiere_switch`) although no VTherm TRV have met their targeted temperature to trigger `hvac_mode = on` and when I look at the logs none of the valves were opened.

Couldn't find all the values in state but I have configured the central boiler as a switch with `switch.chaudiere_switch/switch.turn_on` action. My heater doesn't have any form of self regulation so it's not a central boiler in the form, it's either on or off and I have dedicated temperature sensors in the rooms.

```
- number.boiler_activation_threshold
  - min: 1
  - max: 9
  - step: 1
  - mode: auto
- sensor.nb_device_active_for_boiler
  - device_class: running
- climate.vtherm-salon
  - hvac_modes: off, heat
  - min_temp: 7
  - max_temp: 26
  - target_temp_step: 0.1
  - preset_modes: none, frost, eco, comfort, boost
  - current_temperature: 15.3
  - temperature: 15
  - hvac_action: off
  - preset_mode: comfort
  - is_on: true
  - hvac_mode: heat
  - type: null
  - is_controlled_by_central_mode: true
  - last_central_mode: null
  - frost_temp: 7
  - eco_temp: 13
  - boost_temp: 17
  - comfort_temp: 15
  - frost_away_temp: 0
  - eco_away_temp: 0
  - boost_away_temp: 0
  - comfort_away_temp: 0
  - power_temp: null
  - target_temperature_step: 0.1
  - ext_current_temperature: 8
  - ac_mode: false
  - current_power: null
  - current_power_max: null
  - saved_preset_mode: comfort
  - saved_target_temp: 7
  - saved_hvac_mode: null
  - motion_sensor_entity_id: null
  - motion_state: null
  - power_sensor_entity_id: null
  - max_power_sensor_entity_id: null
  - overpowering_state: null
  - presence_sensor_entity_id: null
  - presence_state: null
  - window_state: off
  - window_auto_state: off
  - window_bypass_state: false
  - window_sensor_entity_id: null
  - window_delay_sec: null
  - window_auto_enabled: false
  - window_auto_open_threshold: null
  - window_auto_close_threshold: null
  - window_auto_max_duration: null
  - window_action: window_turn_off
  - security_delay_min: 60
  - security_min_on_percent: 0.7
  - security_default_on_percent: 0.4
  - last_temperature_datetime: 2024-12-21T09:09:02.274341+01:00
  - last_ext_temperature_datetime: 2024-12-21T08:00:00.010655+01:00
  - security_state: false
  - minimal_activation_delay_sec: 300
  - device_power: 1
  - mean_cycle_power: null
  - total_energy: 0.01
  - last_update_datetime: 2024-12-21T09:54:06.842354+01:00
  - timezone: Europe/Paris
  - temperature_unit: °C
  - is_device_active: false
  - nb_device_actives: 0
  - ema_temp: 15.26
  - is_used_by_central_boiler: true
  - temperature_slope: 0
  - hvac_off_reason: null
  - max_on_percent: null
  - have_valve_regulation: true
  - is_over_climate: true
  - start_hvac_action_date: null
  - underlying_entities: climate.robinet_entree_thermostat_2, climate.robinet_television_thermostat_3, climate.robinet_cuisine_thermostat, climate.robinet_chemine_thermostat
  - is_regulated: true
  - regulated_target_temperature: null
  - auto_regulation_mode: auto_regulation_valve
  - regulation_accumulated_error: 0
  - auto_fan_mode: auto_fan_none
  - current_auto_fan_mode: auto_fan_none
  - auto_activated_fan_mode: null
  - auto_deactivated_fan_mode: null
  - auto_regulation_use_device_temp: true
  - auto_start_stop_enable: false
  - auto_start_stop_level: auto_start_stop_none
  - auto_start_stop_dtmin: null
  - auto_start_stop_accumulated_error: 0
  - auto_start_stop_accumulated_error_threshold: null
  - auto_start_stop_last_switch_date: null
  - follow_underlying_temp_change: false
  - friendly_name: VTherm salon
  - supported_features: 401
  - underlyings_valve_regulation: 
  - - - number.robinet_entree_valve_opening_degree_2
  -   - number.robinet_entree_valve_closing_degree_2
  -   - number.robinet_entree_local_temperature_offset_2
  - - - number.robinet_television_valve_opening_degree_3
  -   - number.robinet_television_valve_closing_degree_3
  -   - number.robinet_television_local_temperature_offset_3
  - - - number.robinet_cuisine_valve_opening_degree
  -   - number.robinet_cuisine_valve_closing_degree
  -   - number.robinet_cuisine_local_temperature_offset
  - - - number.sonoff_trvzb_valve_opening_degree
  -   - number.sonoff_trvzb_valve_closing_degree
  -   - number.robinet_chemine_local_temperature_offset
  - 
  - on_percent: 0
  - power_percent: 0
  - on_time_sec: 0
  - off_time_sec: 300
  - cycle_min: 5
  - function: tpi
  - tpi_coef_int: 0.6
  - tpi_coef_ext: 0.01
  - valve_open_percent: 0
  - auto_regulation_dpercent: 0.5
  - auto_regulation_period_min: 5
  - last_calculation_timestamp: 2024-12-21T08:24:03.254666+01:00
```
