### DISCUSSION TITLE
Expose auto_fan_mode to be controllable?

### DISCUSSION THREAD

**Discussion by d96moe** [jmcollin78/versatile_thermostat#740] [Ideas]
I'm having 2 HVAC units as heaters and using versatile thermostat for both of them with great results. I have one issue though. As the HVCS can get a bit noicy, using auto_fan_mode: high disturbes the night sleep. I would still like to use this feature during daytime and then control it with an automation and set it to auto or even disable it during night-time. I haven't figured out a way to do that now. 
If it was an exposed entity or a service I could control it. Or did I miss anything?

**Comment by jmcollin78** [comment]
Hello,

Yes the correct way is to add a service (called action now). If someone wants to do a PR, it is an easy task to do.

**Reply by d96moe** [reply]
Ah, I just figured out by using the versatile thermostat card that the service call (action) already exists!
```
action: versatile_thermostat.set_auto_fan_mode
data:
  auto_fan_mode: None
target:
  entity_id: climate.your_entity
```
