### DISCUSSION TITLE
Heating debug dashboard

### DISCUSSION THREAD

**Discussion by simoncozens** [jmcollin78/versatile_thermostat#784] [Show and tell]
I made a dashboard page to help me understand what Versatile Thermostat is doing, why the boiler is going on or off, why things are or are not updating, and so on. It looks like this:

<img width="542" alt="Screenshot 2025-01-06 at 09 40 04" src="https://github.com/user-attachments/assets/178cb11d-9994-427b-9b42-bc0695919966" />

Here's the dashboard code I use; it needs the Apex Charts, Auto Entities, and Mushroom Template Card custom elements:

```yaml
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: custom:auto-entities
            card:
              type: entities
              title: Sluggish Sensors
              state_color: false
            filter:
              include:
                - entity_id: sensor.*_last_temperature_date
              exclude:
                - last_changed: < 25
            sort:
              method: last_changed
              numeric: false
              reverse: false
            show_empty: true
            grid_options:
              columns: full
          - type: custom:mushroom-template-card
            primary: >-
              Device{% if states("sensor.nb_device_active_for_boiler") !=
              1%}s{%endif%} using boiler
            secondary: >
              {% for entity in state_attr("sensor.nb_device_active_for_boiler",
              "active_device_ids") %}{{ device_attr(device_id(entity),
              "name_by_user").replace(" TRV", "") }}{% if not loop.last %}, {%
              endif %}{% endfor %}
            icon: mdi:water-boiler
            badge_icon: mdi:numeric-{{states("sensor.nb_device_active_for_boiler")}}
            icon_color: ''
            badge_color: >-
              {% if int(states("sensor.nb_device_active_for_boiler")) > 0
              %}red{%endif%}
            grid_options:
              columns: full
          # Repeat this section for each thermo you have
          - type: custom:apexcharts-card
            graph_span: 60min
            header:
              show: true
              # Customize with your title here
              title: Study
              show_states: true
              colorize_states: true
              title_actions:
                tap_action:
                  action: navigate
                  # Customize with path to the device info page of the Versatile Thermostat device
                  navigation_path: /config/devices/device/43971b88f040c4af44bee9ff3c803de5
            series:
                # Customize with entity name of external temperature monitor
              - entity: sensor.study_air_monitor_temperature
                yaxis_id: temp
                name: Actual
                group_by:
                  func: avg
                  duration: 5m
                # Customize with entity name of Versatile Thermostat device
              - entity: climate.study
                attribute: temperature
                unit: °C
                yaxis_id: temp
                name: Set
                # Customize with entity name of TRV opening degree
              - entity: number.study_trv_valve_opening_degree
                yaxis_id: percent
                type: line
                stroke_width: 2
                curve: stepline
                name: Open%
            yaxis:
              - id: temp
                min: ~15
                max: ~20
              - id: percent
                opposite: true
                min: 0
                max: 100
                decimals: 0
          # And finally something about the boiler itself
          - type: tile
            entity: climate.boiler_thermostat
            features:
              - type: climate-hvac-modes
              - type: target-temperature
            grid_options:
              columns: full
              rows: 3

**Comment by jmcollin78** [comment]
Hello, this is great and useful. Thanks for sharing. 

Please share your Heating dashboard if you think this can be interested for others.

**Comment by jmcollin78** [comment]
Conversation have been pined.

**Comment by jmcollin78** [comment]
On my side, I have something like that :

<img width="252" alt="Capture d’écran 2025-01-06 à 22 06 07" src="https://github.com/user-attachments/assets/99837f05-d871-4787-8e1a-502f35eae7e8" />

The card is collapsable and if expanded I get this:

<img width="250" alt="Capture d’écran 2025-01-06 à 22 07 03" src="https://github.com/user-attachments/assets/d18831fd-a6cc-40d5-940e-070cd45ea4a2" />

If someone is interested I could share my code.

**Reply by Fab-62** [reply]
For me It's the perfect card to add to your Versatile Thermostat project, please share the code.

**Reply by jmcollin78** [reply]
The code of my card:
```
streamline_templates:
  thermostat:
    default: null
    card:
      type: custom:expander-card
      expanded: false
      title-card-button-overlay: true
      title-card:
        type: custom:versatile-thermostat-ui-card
        entity:
          - '[[climate]]'
        powerEntity: '[[power]]'
        set_current_as_main: true
        disable_menu: true
        disable_buttons: true
        disable_cool: true
        disable_name: false
        disable_circle: true
      cards:
        - type: glance
          show_name: true
          show_icon: true
          show_state: true
          entities:
            - entity: '[[energy]]'
            - entity: '[[last_external_temperature_date]]'
            - entity: '[[last_temperature_date]]'
            - entity: '[[mean_power_cycle]]'
            - entity: '[[off_time]]'
            - entity: '[[on_time]]'
            - entity: '[[overpowering]]'
            - entity: '[[power_percent]]'
            - entity: '[[presence]]'
            - entity: '[[security]]'
            - entity: '[[window]]'
            - entity: '[[slope]]'
          columns: 4
          theme: versatile_thermostat_theme
        - type: history-graph
          entities:
            - entity: '[[switch]]'
          refresh_interval: 1
          hours_to_show: 2
        - type: history-graph
          entities:
            - entity: '[[total_puissance]]'
            - entity: '[[temperature]]'
          refresh_interval: 1
          hours_to_show: 12
        - type: custom:plotly-graph
          entities:
            - entity: '[[climate]]'
              attribute: temperature
              yaxis: y1
              name: Consigne
            - entity: '[[climate]]'
              attribute: current_temperature
              yaxis: y1
              name: T°
            - entity: '[[climate]]'
              attribute: ema_temp
              yaxis: y1
              name: Ema
            - entity: '[[climate]]'
              attribute: on_percent
              yaxis: y2
              name: Power percent
              fill: tozeroy
              fillcolor: rgba(200, 10, 10, 0.3)
              line:
                color: rgba(200, 10, 10, 0.9)
            - entity: '[[slope]]'
              name: Slope
              fill: tozeroy
              yaxis: y9
              fillcolor: rgba(100, 100, 100, 0.3)
              line:
                color: rgba(100, 100, 100, 0.9)
          hours_to_show: 4
          refresh_interval: 10
          height: 800
          config:
            scrollZoom: true
          layout:
            margin:
              r: 50
            legend:
              x: 0
              'y': 1.2
              groupclick: togglegroup
              title:
                side: top right
            yaxis:
              visible: true
              position: 0
            yaxis2:
              visible: true
              position: 0
              fixedrange: true
              range:
                - 0
                - 1
            yaxis9:
              visible: true
              fixedrange: false
              range:
                - -2
                - 2
              position: 1
            xaxis:
              rangeselector:
                'y': 1.1
                x: 0.7
                buttons:
                  - count: 1
                    step: hour
                  - count: 12
                    step: hour
                  - count: 1
                    step: day
                  - count: 7
                    step: day
  thermostat_over_climate:
    default: null
    card:
      type: custom:expander-card
      expanded: false
      title-card-button-overlay: true
      title-card:
        type: custom:versatile-thermostat-ui-card
        entity:
          - '[[climate]]'
        powerEntity: '[[power_entity]]'
        autoStartStopEnableEntity: '[[auto_start_stop_enable_entity]]'
        set_current_as_main: true
        disable_menu: true
        disable_buttons: true
        disable_cool: false
        disable_name: false
        disable_circle: true
        disable_heat_cool: true
        disable_auto: true
        disable_dry: true
        disable_fan_only: true
      cards:
        - type: glance
          show_name: true
          show_icon: true
          show_state: true
          entities:
            - entity: '[[energy]]'
            - entity: '[[last_external_temperature_date]]'
            - entity: '[[last_temperature_date]]'
            - entity: '[[overpowering]]'
            - entity: '[[presence]]'
            - entity: '[[security]]'
            - entity: '[[window]]'
            - entity: '[[slope]]'
            - entity: '[[regulated]]'
          columns: 4
          theme: versatile_thermostat_theme
        - type: history-graph
          entities:
            - entity: '[[switch]]'
          refresh_interval: 1
          hours_to_show: 2
        - type: history-graph
          entities:
            - entity: '[[total_puissance]]'
            - entity: '[[temperature]]'
          refresh_interval: 1
          hours_to_show: 12
        - type: custom:plotly-graph
          entities:
            - entity: '[[climate]]'
              attribute: temperature
              yaxis: y1
              name: Consigne
            - entity: '[[climate]]'
              attribute: current_temperature
              yaxis: y1
              name: T°
            - entity: '[[climate]]'
              attribute: ema_temp
              yaxis: y1
              name: Ema
            - entity: '[[climate]]'
              attribute: regulated_target_temperature
              yaxis: y1
              name: Regulated T°
            - entity: '[[climate]]'
              attribute: temperature_slope
              name: Slope
              fill: tozeroy
              yaxis: y9
              fillcolor: rgba(100, 100, 100, 0.3)
              line:
                color: rgba(100, 100, 100, 0.9)
          hours_to_show: 4
          refresh_interval: 10
          height: 800
          config:
            scrollZoom: true
          layout:
            margin:
              r: 50
            legend:
              x: 0
              'y': 1.2
              groupclick: togglegroup
              title:
                side: top right
            yaxis:
              visible: true
              position: 0
            yaxis9:
              visible: true
              fixedrange: false
              range:
                - -2
                - 2
              position: 1
            xaxis:
              rangeselector:
                'y': 1.1
                x: 0.7
                buttons:
                  - count: 1
                    step: hour
                  - count: 12
                    step: hour
                  - count: 1
                    step: day
                  - count: 7
                    step: day
```


Note that this is a strealine template (like declutering-card). You should install streamline UI integration.
