### DISCUSSION TITLE
Wait before closing TRV to rely on heating inertia

### DISCUSSION THREAD

**Discussion by PokePango** [jmcollin78/versatile_thermostat#813] [Ideas]
Hello,

I have a suggestion that may be achievable by tweaking some entities, for example by creating an intermediate entity or setup automations.

My setup is as follow:

* An uncontrolled boiler on which I've plugged a switch to enable/disable heating. Water is always flowing thrgouh the circuit. In VTherm it is setup in the central configuration and activates when at least 1 Vtherm needs heating.
* 10 radiators with a TRV and a central temperature sensor in each room, each of them are setup with valve control.

Ideally, I'd like to be able to optimize the heating inertia of the flowing water and to avoid a situation where all the TRV are closed just after the boiler has been activated.

I can imagine 2 methods in achieving this behavior:

* When the TRV reaches a certain % of opening, preemptively stop the boiler to rely on the inertia
* When specified temperature is reached, keep the TRV opened until another room (another VTherm) needs heating

What do you think about those scenarios? Maybe inertia isn't that benefical to the overall heating setup in most cases so feel free to comment this suggestion from a pure thermostat point of view.

**UPDATE**

In order to replicate this behavior I've currently setup 3 VTherm per room:

- The first one controls the switch from the boiler, relative to the current room temperature
- The second one controls the valves, also relative to the current room temperature
- The third one controls the 2 previous VTherm (I call it central room control), also relative to the current room temperature

It seems to be working fine, currently just testing with 3 rooms to check for possible conflicts and I'll extend it to the whole house if it goes well. I've enabled temperature regulation from the central room control VTherm and it seems to behave as I wanted: the boiler progressively turns off long before the valves are fully closed. The next thing I'll check is the target temperature deviation, having multiple TPI algorithms layered might be weird. Please feel free to comment on this implementation @jmcollin78

From my own testing I think I need to be careful about 2 things:

- Conflict values on the main boiler switch (no central control of the boiler anymore)
- The main boiler being trigger by a VTherm while the valves are closed by another VTherm (valves and boiler aren't linked by VTherm anymore)

In order to avoid those 2 issues, I've created an automation that triggers the main boiler switch only if at least 1 virtual boolean value from `on_switch` VTherm is set to 1, along with a check of the open_percent of the valves:

```
alias: Gestion de la chaudière via les chauffages
description: >-
  Active ou désactive switch.chaudiere_switch en fonction des chauffages
  individuels.
triggers:
  - entity_id:
      - input_boolean.chauffage_salon
      - input_boolean.chauffage_bureau
      - input_boolean.chauffage_chambre
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.chauffage_salon
                    state: "on"
                  - condition: numeric_state
                    entity_id: sensor.vtherm_valve_salon_valve_open_percent
                    above: 0
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.chauffage_bureau
                    state: "on"
                  - condition: numeric_state
                    entity_id: sensor.vtherm_valve_bureau_valve_open_percent
                    above: 0
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.chauffage_chambre
                    state: "on"
                  - condition: numeric_state
                    entity_id: sensor.vtherm_valve_chambre_valve_open_percent
                    above: 0
        sequence:
          - target:
              entity_id: switch.chaudiere_switch
            action: switch.turn_on
            data: {}
    default:
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: switch.chaudiere_switch
mode: single
```
