### DISCUSSION TITLE
Sonoff TRVZB heater stops heating long before target temperature with direct valve control

### DISCUSSION THREAD

**Discussion by chaptergy** [jmcollin78/versatile_thermostat#860] [Q&A] [answered]
## Version of the custom_component
7.1.5

## Configuration

<details><summary>Versatile thermostat entity</summary>

```yaml
hvac_modes: off, auto, heat
min_temp: 7
max_temp: 35
target_temp_step: 0.1
current_temperature: 20
temperature: 22
hvac_action: off
friendly_name: Thermostat Arbeitszimmer
supported_features: 401
is_on: true
hvac_mode: heat
preset_mode: comfort
type: null
is_controlled_by_central_mode: true
last_central_mode: Auto
frost_temp: 12
eco_temp: 17
boost_temp: 24
comfort_temp: 22
frost_away_temp: 12
eco_away_temp: 17
boost_away_temp: 17
comfort_away_temp: 17
target_temperature_step: 0.1
ext_current_temperature: -1.6
ac_mode: false
saved_preset_mode: comfort
saved_target_temp: 22
saved_hvac_mode: heat
last_temperature_datetime: 2025-01-21T11:04:46.602531+01:00
last_ext_temperature_datetime: 2025-01-21T11:04:03.169972+01:00
minimal_activation_delay_sec: 10
total_energy: 0.72
last_update_datetime: 2025-01-21T11:04:47.978737+01:00
timezone: Europe/Berlin
temperature_unit: °C
is_device_active: false
device_actives: 
nb_device_actives: 0
ema_temp: 20
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: 2025-01-21T11:04:46.612792+01:00
presence_sensor_entity_id: binary_sensor.bewohner
presence_state: on
is_presence_configured: true
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: 0
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: off
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.fenster_arbeitszimmer
window_delay_sec: 300
window_off_delay_sec: 30
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
is_safety_configured: true
safety_state: off
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.heizung_arbeitszimmer
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: true
preset_modes: none, frost, eco, comfort, boost
underlyings_valve_regulation: 
- - number.heizung_arbeitszimmer_valve_opening_degree
  - number.heizung_arbeitszimmer_valve_closing_degree
  - number.heizung_arbeitszimmer_local_temperature_calibration

on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
min_opening_degrees: 
valve_open_percent: 0
auto_regulation_dpercent: 0.5
auto_regulation_period_min: 5
last_calculation_timestamp: 2025-01-21T11:04:03.177349+01:00
```
</details>

<details><summary>Underlying climate entity</summary>

```yaml
hvac_modes: off, auto, heat
min_temp: 4
max_temp: 35
target_temp_step: 0.5
supported_features: 385
friendly_name: Heizung Arbeitszimmer
current_temperature: 19.8
temperature: 22
hvac_action: idle
```
</details>

Here is a graph from yesterday (where it suddenly stopped working and I turned off versatile thermostat in the evening in favor of manual control because it was too cold) up until now.

![Image](https://github.com/user-attachments/assets/0bfa56bc-9c5f-4c1f-9074-1ce8b018a98b)

Theoretically it should heat to 22 degrees between 7 AM and 10:30 PM.

## Describe the bug
I'm trying to:
- heat the room to a specific temperature

And I expect:
- the heater to heat until the target temperature is reached

But I observe this ....
- the heater stops heating quite a bit below the target temperature
- yesterday even setting the target temperature very high did not cause the heater to heat
- it happened to at least multiple of my heaters
- but it also started working yesterday evening once again for the other heaters
- generally hard to pinpoint, why it stops or to reproduce

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log
I do not have debug logs, since it's hard to know when it won't work and I do not have much storage space allowing me to keep the logs enabled for an extended period of time.  
But I have observed this warning in the logs when reloading the integration, not sure if this is normal for both restarts and reloads. If it is, disregard this:
```
Proportional algorithm: calculation is not possible cause target_temp (22.0) or current_temp (None) is null. Heating/cooling will be disabled. This could be normal at startup
```

**Comment by apydo** [comment]
I can see similar behavior on over_switch thermostat. It always worked fine but now in current version (or maybe in the previous one as well) it fails.

What I can see is that a VTherm once created (or recreated) starts working 100% of time and approach the target temp and then quickly the working time falls to 10% and does not change any more.
10% working time is not enough to reach the target temp and the temperature is droping.
Stop/Start action on VTherm does not restore the working time.
This is what I can see this morning while I started the VTherm (target temp 10°): 

![Image](https://github.com/user-attachments/assets/12f19304-9647-4351-9bfe-e014ab935ba2)

I add this night history. I played a little bit with the target temp to see if working time % will change but it didn't.

![Image](https://github.com/user-attachments/assets/327e109b-86b1-4a43-b60d-e859ae1f22e3)

**Comment by petosak** [comment]
Same problem here

**Comment by jmcollin78** [comment]
Hello @chaptergy ,

With Sonoff TRVZB you should not configure the Closing degree as documented. This lead to a bug in the Sonoff climate havec_action.

**Reply by hipp0o** [reply]
Is this still correct for Sonoff-firmware 1.3.0/versatile 7.2.4?

**Comment by jmcollin78** [comment]
Hello @apydo 

> I can see similar behavior on over_switch thermostat. It always worked fine but now in current version (or maybe in the previous one as well) it fails.

In `over_switch` the behavior is different and it cannot be the same issue (as far I know). Please open a new issue and follow the issue template to give me the attributes, ,some logs when the issue occurs and if possible some regulation curves as described here: https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/fr/additions.md#courbes-de-r%C3%A9gulattion-avec-plotly

Thank you

Same for you @petosak if you don't have a Sonoff TRVZB.

**Comment by chaptergy** [comment]
Thanks for the prompt reply! Unfortunately I did not stumble across this notice for the Sonoff TRVs, so thanks for the hint. I removed the closing degree everywhere, but unfortunately I am still experiencing these issues, this time the heater running far beyond the target temperature. To be fair, it is one of the other heaters now, but the problem seems to be very similar. So I assume the root cause is likely the same.

<details>
<summary>
Thermostat 
</summary>

```yaml
hvac_modes: off, auto, heat
min_temp: 7
max_temp: 35
target_temp_step: 0.1
preset_modes: none, frost, eco, comfort, boost
current_temperature: 25.3
temperature: 17
hvac_action: off
preset_mode: eco
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 12
eco_temp: 17
boost_temp: 24
comfort_temp: 22
frost_away_temp: 12
eco_away_temp: 17
boost_away_temp: 17
comfort_away_temp: 17
target_temperature_step: 0.1
ext_current_temperature: 2.5
ac_mode: false
saved_preset_mode: eco
saved_target_temp: 22
saved_hvac_mode: null
last_temperature_datetime: 2025-01-22T12:39:35.048443+01:00
last_ext_temperature_datetime: 2025-01-22T12:11:01.375286+01:00
minimal_activation_delay_sec: 10
total_energy: 0.59
last_update_datetime: 2025-01-22T12:39:35.049641+01:00
timezone: Europe/Berlin
temperature_unit: °C
is_device_active: false
device_actives: 
nb_device_actives: 0
ema_temp: 25.32
is_used_by_central_boiler: false
temperature_slope: -0.02
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: 2025-01-22T12:35:26.603467+01:00
presence_sensor_entity_id: binary_sensor.bewohner
presence_state: on
is_presence_configured: true
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: 0
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: off
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.fenster_bad
window_delay_sec: 300
window_off_delay_sec: 30
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
is_safety_configured: true
safety_state: off
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.heizung_bad
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: true
friendly_name: Thermostat Bad
supported_features: 401
underlyings_valve_regulation: 
- - number.heizung_bad_valve_opening_degree
  - number.heizung_bad_local_temperature_calibration

on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
min_opening_degrees: 
valve_open_percent: 0
auto_regulation_dpercent: 0.5
auto_regulation_period_min: 5
last_calculation_timestamp: 2025-01-22T07:10:02.179167+01:00
```

</details>

![Image](https://github.com/user-attachments/assets/7c0a7599-ce02-419d-837b-40e9a0c52534)
