### DISCUSSION TITLE
Min Opening Degrees Parameter Not Respected in Direct Valve Control mode

### DISCUSSION THREAD

**Discussion by joshua-lehmann** [jmcollin78/versatile_thermostat#867] [Q&A] [answered]
# Issue Description
I am using the versatile thermostat integration with the Sonoff TRVZB and over climate vTherm (self-regulation with direct valve type). I set the "Min Opening Degrees" parameter to 50, expecting the valve to never open below this value during heating. However, the thermostat still opens the valve to values below 50%, such as 20%.

I have also tested other values for "Min Opening Degrees" (e.g., 40%), but the issue persists. The behavior does not align with the configured "Min Opening Degrees."

## Expected Behaviour
The valve should not open below the configured "Min Opening Degrees" value (e.g., 50%) when heating.
## Observed Behaviour
The valve opens below the configured minimum value. For example:
Valve opening: 20% despite "Min Opening Degrees" being set to 50%.

![Image](https://github.com/user-attachments/assets/f71cbd71-e106-4c5e-8ebf-ea92039885a6)

## Version of the custom_component
I am using version 7.1.4 of the integration, but this issue has also existed in previous versions.

# Configuration

My VTherm attributes are as follows:
```yaml
hvac_modes: off, auto, heat
min_temp: 7
max_temp: 25
target_temp_step: 0.2
preset_modes: none, frost, eco, comfort, boost
current_temperature: 19.7
temperature: 19.6
hvac_action: off
preset_mode: eco
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 7
eco_temp: 19.6
boost_temp: 20.5
comfort_temp: 20
frost_away_temp: 7
eco_away_temp: 18
boost_away_temp: 7
comfort_away_temp: 18.5
target_temperature_step: 0.2
ext_current_temperature: 4.9
ac_mode: false
saved_preset_mode: eco
saved_target_temp: 20.5
saved_hvac_mode: heat
last_temperature_datetime: 2025-01-23T10:56:41.980373+01:00
last_ext_temperature_datetime: 2025-01-23T11:11:45.956154+01:00
minimal_activation_delay_sec: 300
total_energy: 0.07
last_update_datetime: 2025-01-23T11:11:45.956552+01:00
timezone: Europe/Zurich
temperature_unit: °C
is_device_active: false
device_actives: 
nb_device_actives: 0
ema_temp: 19.69
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: 2025-01-23T11:02:43.904309+01:00
presence_sensor_entity_id: person.joshua
presence_state: on
is_presence_configured: true
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: 0.08
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: off
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.fenster_schlafzimmer_contact
window_delay_sec: 20
window_off_delay_sec: 900
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
is_safety_configured: true
safety_state: off
safety_delay_min: 240
safety_min_on_percent: 0.7
safety_default_on_percent: 0.4
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.heizung_schlafzimmer
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: false
friendly_name: Heizung Schlafzimmer VT
supported_features: 401
underlyings_valve_regulation: 
- - number.heizung_schlafzimmer_valve_opening_degree
  - number.heizung_schlafzimmer_valve_closing_degree
  - number.heizung_schlafzimmer_local_temperature_calibration

on_percent: 0.08
power_percent: 8
on_time_sec: 0
off_time_sec: 1500
cycle_min: 25
function: tpi
tpi_coef_int: 0.66
tpi_coef_ext: 0.01
min_opening_degrees: 50
valve_open_percent: 0
auto_regulation_dpercent: 15
auto_regulation_period_min: 10
last_calculation_timestamp: 2025-01-23T08:41:44.955691+01:00
```
I currently do not have debug logs enabled but can provide them if needed. Please let me know if this is required to analyse the issue.

**Comment by jmcollin78** [comment]
Hello @joshua-lehmann ,

Can you please send me a screen copy of the configuration page where you set the min value ? unfortunalty those values are not in the attributes. Thank you.

Other think, for Sonoff TRVZB you should not configure the closing_degree. See here: https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/self-regulation.md#self-regulation-by-direct-valve-control

Can you try without this parameter.

**Comment by joshua-lehmann** [comment]
@jmcollin78 
I think we can see it in the attributes no?
![Image](https://github.com/user-attachments/assets/d85030d2-99fd-402c-8ccb-db99645d37e1)
But anyway here is my configuration:
![Image](https://github.com/user-attachments/assets/56cba42f-efa9-4310-ba18-9dc8ae2f3de7)
I removed the closing_degree entity as you suggested yesterday. Btw. it was not clear for me why to remove it since it worked with having it and in the screenshot in the docs you have set a closing degree entity named "SONOFF Closing Degree 1" so I thought it's needed I did not see the small note below.
But even after removing the closing degree entity it still opens to less than 50%. Anything else I could do?

![Image](https://github.com/user-attachments/assets/6105038d-f693-4099-b1ea-d2b23c351f0d)

**Comment by jmcollin78** [comment, marked as answer]
> [@jmcollin78](https://github.com/jmcollin78) I think we can see it in the attributes no?

Yes you are right, i miss this.

>  was not clear for me why to remove it since it worked

See in documentation why :
`Note: for Sonoff TRVZB you should not configure the "closing degree" parameter. This leads to a bug in the TRV and the hvac_action is no more working.`

I do more test on my env and the behavior is normal:
1.  the open percent will vary from min to 100% when there is need to heat,
2. else the open percent will be set to 0 to force close the valve if we shouldn't heat.


I guess documentation is not clear about that.

EDIt : documentation updated.

**Comment by jmcollin78** [comment]
I transform this into a pinned discussion for others users.

**Reply by joshua-lehmann** [reply]
@jmcollin78 I am sorry I do not agree with your solution or at least I do not understand it. I removed the Closing degree param and still have the same issue/behaviour.
As you saw in my picture and the attributes I have set the min % to 50%. So according to your description I would expect that when I am actually heating, that the valve should be opened between 50% & 100% right?
However for me it also opens on 15% or 30% when it needs to heat (which does not work because my heater does not really provide actual noticeable heating for the roam when the valve is only open that much). See graph below where you can see that the valve is often open below 50% even when we are below target temp and in heating mode. 
![image](https://github.com/user-attachments/assets/ac480908-7214-424f-b1d2-b6b6e08c9b75)

So for me it looks like the "min opening degrees" is ignored which would be a bug no?
Let me know if I misunderstood you or you need any more details.

**Reply by jmcollin78** [reply]
> So according to your description I would expect that when I am actually heating, that the valve should be opened between 50% & 100% right?

Exactly. But I talk about the opening degree and you talk about the power_percent. The min opening degree applies to the "opening degree" and not the power_percent.

The opening degree is calculated from the power_percent but is not. Show the opening degree in your graph and I think you will see  what you are looking for.

**Reply by joshua-lehmann** [reply]
@jmcollin78 Sorry I had the wrong name still on the chart, I actually do display the opening degree in my chart (I tried to also display power percent but somehow it did not work, then I changed it back to the vale opening degree, but forgot to change the name back)

As you see also the valve opening degree goes below 50%. I attached the code for the Plotly I am using (feel free to attach one of yours which displays the opening degree if I did something wrong)
![image](https://github.com/user-attachments/assets/6b328ce0-8936-40ed-a544-0a083dca87da)

<details><summary>Plotly Graph Code</summary>
<p>

```yaml
type: custom:plotly-graph
entities:
  - entity: climate.heizung_schlafzimmer_vt
    attribute: temperature
    yaxis: y1
    name: Target Temp
  - entity: climate.heizung_schlafzimmer_vt
    attribute: current_temperature
    yaxis: y1
    name: Current Temp
  - entity: climate.heizung_schlafzimmer_vt
    attribute: power_percent
    yaxis: y9
    name: Power percent
    fill: tozeroy
    fillcolor: rgba(200, 10, 10, 0.3)
    line:
      color: rgba(200, 10, 10, 0.9)
  - entity: climate.heizung_schlafzimmer_vt
    attribute: valve_open_percent
    yaxis: y9
    name: Valve Open Percent
    fill: tozeroy
    fillcolor: rgba(10, 200, 10, 0.3)
    line:
      color: rgba(10, 200, 10, 0.9)
hours_to_show: 24
refresh_interval: 10
height: 1000
config:
  scrollZoom: true
layout:
  margin:
    r: 50
  legend:
    x: 0
    "y": 1.2
    groupclick: togglegroup
    title:
      side: top right
  yaxis:
    visible: true
    position: 0
  yaxis2:
    visible: true
    position: 0
    fixedrange: true
    range:
      - 0
      - 1
  yaxis9:
    visible: true
    fixedrange: false
    range:
      - 0
      - 100
    position: 1
  xaxis:
    rangeselector:
      "y": 1.1
      x: 0.7
      buttons:
        - count: 1
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day
grid_options:
  columns: full
  rows: 8

```

</p>
</details>
