### DISCUSSION TITLE
my logs are spammed by "Last temperature date" entries, can i disable it?

### DISCUSSION THREAD

**Discussion by kskarlatos** [jmcollin78/versatile_thermostat#876] [Q&A]
Hello, I have been using Vtherm for a while now, and i have a little issue that bothers me. my logs are spammed by "Last temperature date" entries, how can i disable that? my sensors are ruuvitags if that helps

![image](https://github.com/user-attachments/assets/aa5ad150-4e05-45d1-8c94-44883924d27c)

**Comment by jmcollin78** [comment]
Hello, where do you see that ? This is not logs generated by Vtherm's code.

**Comment by kskarlatos** [comment]
At the logbook menu

Jan 30, 2025 23:36:11 Jean-Marc Collin ***@***.***>:

**Comment by jmcollin78** [comment]
It is not controlled directly by VTherm. I don't know how to disable this and even if it is possible.

**Comment by kskarlatos** [comment]
Ah ok i understand. Can i disable these entites?

**Reply by jmcollin78** [reply]
yes. Give it a try.

**Comment by kskarlatos** [comment]
This seems to have resolved my problem, without any obvious setbacks to vtherm
Thanks!

**Comment by KipK** [comment]
@kskarlatos you can add filters to the logbook in configuration.yaml

```
logbook:
  include:
    domains:
      - sensor
      - switch
      - climate
      - light
      - logbook  
  exclude:
    entity_globs:
      - sensor.*_last_seen
      - sensor.*_last_temperature_date
      - sensor.*_last_external_temperature_date
```
