### DISCUSSION TITLE
Behavior of target temp when going away

### DISCUSSION THREAD

**Discussion by mcornillon** [jmcollin78/versatile_thermostat#911] [General]
I wanna start a discussion with expert users : 

I understood from the documentation that it is recommended : 
- to manage "daily schedule" via the "Scheduler" integration, that sets the desired presets [e.g. eco 17°/comfort 19°] at the desired times --> 🆗 
- to manage "Home/Away" behavior by passing the "presence sensor" to the VTherm configuration, so that it switches to the specific "[e.g. eco AWAY 15°/comfort AWAY 15°]" presets, so that everything goes down to 15° without having to touch the Scheduler (it continues to run transparently) --> 🆗 

Do you confirm I have correctly applied the recommendations ?

If yes, then, I'm faced with this situation (as an example) :
if someone (my daughter, my wife) modifies **manually** the target temp to 20° in the morning despite the "eco 17°" that has been set by the Scheduler, and **then we all leave the house** to work/school, it will stay to "Manual 20°" in the corresponding room even if I have the "presence sensor" set to Away, and all other rooms will be at 15°, either eco or comfort. It will then continue to run heat @ 20° in this room until ~17:00 when it will switch back to "Comfort 19°" as scheduled.

What would be your recommendations to manage this case, and avoid heating @20° while we're away ?

I personnaly think about setting an automation **(for each Vtherm, ouch...)** that would do something like that
- trigger : everyone has left home
- condition : if VTherm is ON, AND VTherm Preset is "None" (meaning on Manual)
- action : duh.... don't know what would be the best to do ?
-- Probably set "Eco Preset" ? 
-- or Retrieve from the Scheduler the preset as it was scheduled ? (but not sure how to do that)
-- or have an evolution in the VTherm so that it stores the "previous preset" that was active before "manual" mode ?, and retrieve it from the attributes ?

And is there a **factored** way to do it with a single automation that would apply to all VTherms ? (instead of making as many automations as VTherms ...)

Or even ask @jmcollin78 to make a VTherm evolution to embed it in his integration instead of playing with automations... 😄 

Happy to hear your answers !

**Comment by mcornillon** [comment]
After some additional thoughts, I already found an exception (see second point below) :
- objective : prevent from heating at a manually set high target when away, by automatically modifying the selected preset to Eco when leaving
- exception : leave the manual setting as-is when away when its value is cold, below a given threshold, e.g if manually set at 12°, we can think it is deliberate, so we should let it like this, and not set it to Eco 15°

**Reply by mcornillon** [reply]
I've just implemented an automation that tackles this behavior, and I think it will work !

Here it is :
```
alias: After 15 minutes Away from home, reset the preset to Eco if Vtherm was on manual Temp higher than Eco
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.statut_presence_absence  # to check presence
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 15
      seconds: 0
conditions: []
actions:
  - repeat:
      # "For each" allows, via a regex, to find all climate entities matching the 'climate.vtherm_*" pattern
      for_each: >-
        {{ states.climate | selectattr('object_id', 'search', '^vtherm_') |
        map(attribute= 'entity_id') | list }} 
      sequence:
        - if:
            - condition: template
              # Condition is : Vtherm is ON (not AUTO, not OFF), is on manual (preset none), and target temp is above eco_temp
              value_template: |-
                {{
                  is_state_attr(repeat.item, 'hvac_mode', 'heat')
                  and is_state_attr(repeat.item, 'preset_mode', 'none')
                  and state_attr(repeat.item, 'temperature') > state_attr(repeat.item, 'eco_temp')
                }}
          then:
            - action: climate.set_preset_mode
              # Set preset to eco
              metadata: {}
              data:
                preset_mode: eco
              target:
                entity_id: "{{ repeat.item }}"

mode: single
```
