### DISCUSSION TITLE
TRVZB local temperature is off

### DISCUSSION THREAD

**Discussion by akopachov** [jmcollin78/versatile_thermostat#928] [Q&A] [answered]
Hello, I need some clarification as I feel like either I misunderstand something or there is tricky bug:

I set my VTherm TRV to 22 °C:
![image](https://github.com/user-attachments/assets/bcb26623-2b39-4ebc-a35e-e2f0a940741f)

Occasionally, underlaying entity (Sonoff TRVZB) local temperature may go completely off, by 1-2 °C, which leads to either, entity is heating when unnecessary or staying closed when necessary. VTherm entity correctly shows the current room temperature, the target temperature and the expected running state (heat), while if I check underlaying entity in Z2M, it is in idle state, because local temperature is incorrectly calibrated by VTherm. 

![image](https://github.com/user-attachments/assets/189654c1-608f-4244-87c4-af6d573fdea2)

It may stay like this for a while, and then it usually returns to normalcy. What I'm curious about - if this behavior is expected?

In case if needed - here is vtherm state:

```yaml
hvac_modes:
  - "off"
  - auto
  - heat
min_temp: 7
max_temp: 28
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 21.5
temperature: 22
hvac_action: heating
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 7
eco_temp: 18
boost_temp: 25
comfort_temp: 22
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
target_temperature_step: 0.5
ext_current_temperature: 4.1
ac_mode: false
saved_preset_mode: eco
saved_target_temp: 22
saved_hvac_mode: heat
last_temperature_datetime: "2025-02-24T09:49:30.044792+01:00"
last_ext_temperature_datetime: "2025-02-24T09:04:03.315226+01:00"
minimal_activation_delay_sec: 10
minimal_deactivation_delay_sec: 0
total_energy: 218.44
last_update_datetime: "2025-02-24T09:59:00.048378+01:00"
timezone: Europe/Warsaw
temperature_unit: °C
is_device_active: true
device_actives:
  - number.living_room_trv_valve_opening_degree
nb_device_actives: 1
ema_temp: 21.38
is_used_by_central_boiler: false
temperature_slope: 1.44
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: "2025-02-24T09:54:00.049471+01:00"
presence_sensor_entity_id: null
presence_state: unavailable
is_presence_configured: false
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: 0.61
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: "off"
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.living_room_and_kitchen_any_window_open
window_delay_sec: 15
window_off_delay_sec: 15
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: "off"
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities:
  - climate.living_room_trv
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: false
underlyings_valve_regulation:
  - - number.living_room_trv_valve_opening_degree
    - number.living_room_trv_local_temperature_calibration
on_percent: 0.61
power_percent: 61
on_time_sec: 181
off_time_sec: 118
cycle_min: 5
function: tpi
tpi_coef_int: 0.65
tpi_coef_ext: 0.015
min_opening_degrees: ""
valve_open_percent: 61
auto_regulation_dpercent: 1
auto_regulation_period_min: 5
last_calculation_timestamp: "2025-02-24T09:46:57.714636+01:00"
friendly_name: Living room vtherm
supported_features: 401
```
