### DISCUSSION TITLE
How to control a zone contact when at least one TRV is heating

### DISCUSSION THREAD

**Discussion by nicola-spreafico** [jmcollin78/versatile_thermostat#934] [General]
Hello,
my heating system can be summarized like this:
![Diagramma senza titolo drawio](https://github.com/user-attachments/assets/58a8fd1c-5ab8-4421-9be4-bb3dea4b0899)

- A central heather running which provided hot water
- 3 separate zones, each one controlled by a electrical contact which open or close a motorized valve for the zone
- N radiators for each zone, and on each radiator has a SonOff TRV valve on it

The electrical contact is a 3 channels dry-contact Zigbee switch, already integrated on Home Assistant.

When at least one TRV enters heating action (for each zone), I need to change the state to "on" of the zone switch so that the valve opens and the hot water begins to flow. When the last TRV goes into idle action, the switch can be reverted to off.

For the moment I created a custom management of this, like this:

This sensor defines if at least one TRV is in heating mode
```
template:
  - binary_sensor:
      - name: zone3_heat
        unique_id: zone3_heat
        state: >
          {% set radiators = [
            'climate.radiator1',
            'climate.radiator2'
          ] %}

          {{ radiators | map('state_attr', 'hvac_action') | map(attribute='value') | select('eq', 'heating') | list | count  > 0 }}
```

And then an automation which change the switch to on or off based on condition
```
automation:
  - id: zone3_on_heat_request
    alias: zone3_on_heat_request
    trigger:
      - platform: state
        entity_id: binary_sensor.zone3_heat
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.zone3_heat
                state: "on"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.zigbee_heat_smartswitch_channel3

          - conditions:
              - condition: state
                entity_id: binary_sensor.zone3_heat
                state: "off"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.zigbee_heat_smartswitch_channel3
```

As I'm very new on Versatile Thermostat, I'm opening this discussion to ask you confirmation that this kind of behaviour need to be managed in a custom way like I already did, that there isn't a built-in way to manage the switch. I read in the documentation about the central_boiler, but because I have 3 different zones I'm not sure this can be achieved with only the native functionalities.

The second question I have is: I already know about the "Central configuration" provided by the integration, expecially the "Central mode" which I can use to bulk disable or enable the heating of all the configured TRVs. I'm wondering if I can the central mode split by the single zone, so that I can centrally controll all the TRVs of a specific zone.

Thank you
