### DISCUSSION TITLE
When window is open, preset change may force VTherm to heat

### DISCUSSION THREAD

**Discussion by akopachov** [jmcollin78/versatile_thermostat#939] [Q&A] [answered]
I have an automation that changes different presets (comfort, eco) based on various conditions (part of the day, presence of people at home and etc.). Everything works well, except for one edgy situation:
If I open a window in a room, VTherm correctly closes the valve. But then, if automation changes the preset to "comfort", because some condition reaches - VTherm starts heating again, not respecting the fact that window is still in an open state. Is it supposed to be so by design? I just feel like it will be more logical if window state will always take priority over any other changes, unless window bypass is enabled.

![image](https://github.com/user-attachments/assets/446febdb-f50b-4933-b1d9-6a051d48f162)

Entity state

```yaml
hvac_modes: off, auto, heat
min_temp: 7
max_temp: 28
target_temp_step: 0.5
preset_modes: none, frost, eco, comfort, boost
current_temperature: 21.7
temperature: 22
hvac_action: off
preset_mode: comfort
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 7
eco_temp: 18
boost_temp: 25
comfort_temp: 22
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
target_temperature_step: 0.5
ext_current_temperature: 4.4
ac_mode: false
saved_preset_mode: comfort
saved_target_temp: 22
saved_hvac_mode: heat
last_temperature_datetime: 2025-03-08T09:01:56.207853+01:00
last_ext_temperature_datetime: 2025-03-08T09:01:56.207853+01:00
minimal_activation_delay_sec: 10
minimal_deactivation_delay_sec: 0
total_energy: 282.85
last_update_datetime: 2025-03-08T09:01:56.263536+01:00
timezone: Europe/Warsaw
temperature_unit: °C
is_device_active: true
device_actives: number.bedroom_room_trv_valve_opening_degree
nb_device_actives: 1
ema_temp: 21.92
is_used_by_central_boiler: false
temperature_slope: -1.94
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: 2025-03-08T09:01:56.207900+01:00
presence_sensor_entity_id: null
presence_state: unavailable
is_presence_configured: false
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: 0.3
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: on
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.bedroom_window_sensor_contact
window_delay_sec: 15
window_off_delay_sec: 15
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: off
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.bedroom_room_trv
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: false
friendly_name: Bedroom vtherm
supported_features: 401
underlyings_valve_regulation: 
- - number.bedroom_room_trv_valve_opening_degree
  - number.bedroom_room_trv_valve_closing_degree
  - number.bedroom_room_trv_local_temperature_calibration

on_percent: 0.3
power_percent: 30
on_time_sec: 90
off_time_sec: 209
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.008
min_opening_degrees: 
valve_open_percent: 30
auto_regulation_dpercent: 1
auto_regulation_period_min: 5
last_calculation_timestamp: 2025-03-08T09:01:47.298022+01:00
```

**Comment by jmcollin78** [comment]
Hello @akopachov ,

The expected behavior is that the new preset should not memorized but not applied when you change a preset with an open window.
When the window is closed, the new preset will be restored.

I just make a test:

Comfort with window open (VTherm is off and preset is Comfort)
<img width="364" alt="Capture d’écran 2025-03-08 à 10 09 58" src="https://github.com/user-attachments/assets/61072add-1121-4db4-9ef8-ded0d8e538b3" />

I click on the Boost preset. Nothing visible happens.

I close the window and wait a few seconds, the VTherm turns on and the preset is restored to Boost:
<img width="382" alt="Capture d’écran 2025-03-08 à 10 13 24" src="https://github.com/user-attachments/assets/4ed45e5c-dd72-476c-b426-a200a351e4dd" />


So it is supposed to work in your configuration exactly the same.

How does your automation change the preset ?

> (part of the day, presence of people at home and etc.)

You kown that VTherm can natively handle the presence of people at home ? https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/feature-presence.md

**Comment by akopachov** [comment]
> You kown that VTherm can natively handle the presence of people at home ?

Yeah, I saw it. That my automation does it a little bit trickier to match my family's needs :) (Example: if wife is not at home, temp may be 1deg lower).

For now, all those switches are happening by running a similar sequence of actions:

Action 1 - turn on TRV:
```yaml
action: climate.turn_on
data: {}
metadata: {}
target:
  label_id: trv
```

Action 2 - set mode to heat:
```yaml
action: climate.set_hvac_mode
data:
  hvac_mode: heat
metadata: {}
target:
  label_id: trv
```

Action 3 - set preset ("comfort" in this case, but for other cases it might be "boost" or "eco" as well):
```yaml
action: climate.set_preset_mode
data:
  preset_mode: comfort
metadata: {}
target:
  label_id: vtherm
```

All the VTherm TRVs have "trv" and "vtherm" labels.

![image](https://github.com/user-attachments/assets/433536bf-b442-44d0-a063-87e58e71260e)
