### DISCUSSION TITLE
A service allowing to modify VTherm state

### DISCUSSION THREAD

**Discussion by akopachov** [jmcollin78/versatile_thermostat#942] [Ideas]
This is mostly continuation of [this discussion](https://github.com/jmcollin78/versatile_thermostat/discussions/939)

I reworked my automation to set HVAC mode only in case if window is closed. And ideally, if it is open, it would be great to update `saved_hvac_mode` attribute of VTherm state, to let it restore it when window close.

I tried to make this happen using [ps_hassio_entities](https://github.com/pmazz/ps_hassio_entities) and actually managed to confirm that appropriate attribute of a state is getting changed. However, it looks like VTherm is caching state values somewhere internally, as when I close the window it still restores the old hvac mode, and not the one which I set in entity state.

So, I wonder, do you think it would be useful to have some service or so, that allows to precisely update not just the state of VTherm, but also any internal cached values of it, like `saved_hvac_mode` in my case?

For reference purposes, here is the script I'm using for now to safely set HVAC mode in automation, making sure it will not force VTherm to heat when window is open:

```yaml
fields:
  vtherm_entities:
    selector:
      entity:
        multiple: true
        filter:
          - domain: climate
    name: vtherm_entities
    required: true
  hvac_mode:
    selector:
      select:
        options:
          - "off"
          - heat
          - auto
    name: hvac_mode
    required: true
alias: vtherm_hvac_mode_set_ex
description: ""
sequence:
  - repeat:
      for_each: "{{ vtherm_entities }}"
      sequence:
        - if:
            - condition: template
              value_template: >-
                {{ is_state_attr(repeat.item, 'window_state', 'off') or
                is_state_attr(repeat.item, 'is_window_configured', False) }}
            - condition: template
              value_template: >-
                {{ is_state_attr(repeat.item, 'safety_state', 'off') or
                is_state_attr(repeat.item, 'is_safety_configured', False) }}
            - condition: template
              value_template: >-
                {{ is_state_attr(repeat.item, 'presence_state', 'off') or
                is_state_attr(repeat.item, 'is_presence_configured', False) }}
          then:
            - action: climate.set_hvac_mode
              data:
                hvac_mode: "{{ hvac_mode }}"
              target:
                entity_id: "{{ repeat.item }}"
          else:
            - data:
                action: set_attributes
                entity_id: "{{ repeat.item }}"
                attributes:
                  - saved_hvac_mode: "{{ hvac_mode }}"
              action: python_script.hass_entities
```
