### DISCUSSION TITLE
Underlying Sonoff TRVZB not switching on for small temperature drops

### DISCUSSION THREAD

**Discussion by onurece** [jmcollin78/versatile_thermostat#992] [Q&A]
I'm using TRVZB via Zigbee2MQTT and have an external temperature sensor that sets overwrites the internal temperature of the TRV. Because of this, I'm not using any calibration.

![image](https://github.com/user-attachments/assets/1b86d526-18a3-4135-adaa-b6c4616711f8)

Here's my problem. My target temperature is set to 21.5. The TRV valve opens up, the room heats, then when target temp reaches (or maybe just before that), the valve opening degree drops to 0%. And it's all fine up to here.
Then, obviously the temperature drops, and VTherm tries to opens up the valves slightly and the opening degree changes, but the underlying TRV, "Study Room" below, stays off because the temp difference between the target and the current temp is less than 1C. So, nothing really happens on the TRV. Only after the temp difference becomes greater 1C, heating resumes. And this kills the whole purpose of Vtherm. 

<img width="518" alt="image" src="https://github.com/user-attachments/assets/2656bc3f-0b4f-48eb-a477-918bb0f7a94d" />

<details>
<summary>Underlying TRVZB entity</summary>

```yaml
hvac_modes:
  - "off"
  - auto
  - heat
min_temp: 4
max_temp: 35
target_temp_step: 0.5
current_temperature: 20.7
temperature: 21.5
hvac_action: idle
friendly_name: Sonoff Study Room TRV
supported_features: 385
```
</details>

<details>
<summary>VTherm entity</summary>

```yaml
hvac_modes:
  - "off"
  - auto
  - heat
min_temp: 4
max_temp: 35
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 20.9
temperature: 21.5
hvac_action: heating
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 4
eco_temp: 4
boost_temp: 4
comfort_temp: 4
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
target_temperature_step: 0.5
ext_current_temperature: 15.6
ac_mode: false
saved_preset_mode: none
saved_target_temp: 19
saved_hvac_mode: null
last_temperature_datetime: "2025-04-08T14:26:16.716872+01:00"
last_ext_temperature_datetime: "2025-04-08T16:15:17.491709+01:00"
minimal_activation_delay_sec: 10
minimal_deactivation_delay_sec: 0
total_energy: 347.3
last_update_datetime: "2025-04-08T16:19:41.864675+01:00"
timezone: Europe/London
temperature_unit: °C
is_device_active: true
device_actives:
  - number.sonoff_study_room_trv_valve_opening_degree
nb_device_actives: 1
ema_temp: 20.94
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: "2025-04-08T16:15:17.492572+01:00"
presence_sensor_entity_id: null
presence_state: unavailable
is_presence_configured: false
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: 0.42
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: unavailable
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: null
window_delay_sec: 30
window_off_delay_sec: 30
is_window_configured: false
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: "off"
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities:
  - climate.sonoff_study_room_trv
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: false
underlyings_valve_regulation:
  - - number.sonoff_study_room_trv_valve_opening_degree
on_percent: 0.42
power_percent: 42
on_time_sec: 125
off_time_sec: 174
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
min_opening_degrees: ""
valve_open_percent: 42
auto_regulation_dpercent: 1
auto_regulation_period_min: 1
last_calculation_timestamp: "2025-04-08T14:26:16.718649+01:00"
friendly_name: Study Room VT
supported_features: 401
```
</details>

What should I do to make Vtherm override the on/off status of the underlying climate entity? (I've already tried setting "Regulation minimum period" to 0, but nothing changed.)

**Comment by jmcollin78** [comment]
Hello, you should configure a opening degree AND the closing degree to force the valve position. You only configure the opening degree.

Moreover I never test with the external temperature sensor but only with the calibration offset. How do you set the external temperature of the TRVZB ?

**Reply by onurece** [reply]
I'm confused now. [Here](https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/quick-start.md#sonoff-trvzb-or-similar-trv-with-valve-control) under step 5, it says "Do not configure the closing_degree entity". That's why I didn't set it and left it blank, and closing degree has always stayed at 100%. Should I not?
<img width="593" alt="image" src="https://github.com/user-attachments/assets/ca9df480-0775-4e9f-a6c2-59432672732f" />

Also, I don't have a problem with VT updating the opening valve degree. It works just fine. It's the underlying entity that doesn't let water flow into the radiator when the temperature difference is less than 1.

External temperature for TRVZB is a new feature Sonoff released and is also possible with Z2M. You just need to upgrade firmware. However, I've always had the issue that I've described.
To answer your question, first you set the Temperature sensor to external in Z2M settings, then have an automation that updates the value of external_temperature_input. I have one automation for each room.

Here's an example.

```yaml
alias: Update Study Room TRV Temperature
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.study_room_ths_temperature
conditions: []
actions:
  - variables:
      external_temperature: "{{ states('sensor.study_room_ths_temperature') }}"
  - target:
      entity_id: number.sonoff_study_room_trv_external_temperature_input
    data:
      value: "{{ external_temperature }}"
    action: number.set_value
mode: single
```

**Reply by jmcollin78** [reply]
> [Here](https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/en/quick-start.md#sonoff-trvzb-or-similar-trv-with-valve-control) under step 5, it says "Do not configure the closing_degree entity"

You are right this is now wrong. You can safely configure the closing degree now. I will fix the documentation (done).

> Also, I don't have a problem with VT updating the opening valve degree. It works just fine. It's the underlying entity that doesn't let water flow into the radiator when the temperature difference is less than 1.

Yes this can be a consequence of not specifying closing degree or offset calibration. Because you use an automation force the external temp I think it is more related to the closing degree.

You have to try this before going further. Next step if it is still not good, deactivate your "Update Study Room TRV Temperature" and configure the offset calibration. I'm sure it is working with that configuration.

Let me know.

**Reply by onurece** [reply]
I've set closing degree and it's still the same.

Currently, underlying TRVZB is off because it has reached the desired temperature, but VT wants to keep the valve just 6% open so that the temperature wouldn't drop too much.
<img width="468" alt="image" src="https://github.com/user-attachments/assets/dd8afd9a-3ef8-41e0-a1a8-440535b3bff6" />

<img width="1369" alt="image" src="https://github.com/user-attachments/assets/fe3e6153-4758-4e8f-88a7-3c439061dfc0" />



Then, I've switched off the automation as suggested. By the way, this was my setup before this new TRVZB feature, but it's never worked and it still doesn't work as I expect it to.
<details>
<summary>New VT settings</summary>

```yaml
hvac_modes:
  - "off"
  - auto
  - heat
min_temp: 4
max_temp: 35
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 18.1
temperature: 18.5
hvac_action: heating
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 4
eco_temp: 4
boost_temp: 4
comfort_temp: 4
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
target_temperature_step: 0.5
ext_current_temperature: 8.4
ac_mode: false
saved_preset_mode: none
saved_target_temp: 18.5
saved_hvac_mode: null
last_temperature_datetime: "2025-04-09T10:53:38.976093+01:00"
last_ext_temperature_datetime: "2025-04-09T10:56:17.493356+01:00"
minimal_activation_delay_sec: 10
minimal_deactivation_delay_sec: 0
total_energy: 351.55
last_update_datetime: "2025-04-09T10:57:48.195670+01:00"
timezone: Europe/London
temperature_unit: °C
is_device_active: true
device_actives:
  - number.sonoff_study_room_trv_valve_opening_degree
nb_device_actives: 1
ema_temp: 18.35
is_used_by_central_boiler: false
temperature_slope: -0.25
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: "2025-04-09T10:56:57.412481+01:00"
presence_sensor_entity_id: null
presence_state: unavailable
is_presence_configured: false
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: 0.34
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: unavailable
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: null
window_delay_sec: 30
window_off_delay_sec: 30
is_window_configured: false
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: "off"
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities:
  - climate.sonoff_study_room_trv
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: false
friendly_name: Study Room VT
supported_features: 401
underlyings_valve_regulation:
  - - number.sonoff_study_room_trv_valve_opening_degree
    - number.sonoff_study_room_trv_valve_closing_degree
    - number.sonoff_study_room_trv_local_temperature_calibration
on_percent: 0.34
power_percent: 34
on_time_sec: 20
off_time_sec: 39
cycle_min: 1
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
min_opening_degrees: ""
valve_open_percent: 34
auto_regulation_dpercent: 1
auto_regulation_period_min: 1
last_calculation_timestamp: "2025-04-09T10:56:17.493556+01:00"
```
</details>

VT is telling that the TRV should allow water in and start heating, but underlying is still off.
<img width="466" alt="image" src="https://github.com/user-attachments/assets/629c58db-e01c-4723-846f-220aff899f58" />
