### ISSUE TITLE
Versatile Thermostat does not follow target temperature from underlying thermostat

### ISSUE THREAD

**Issue by diplix** [jmcollin78/versatile_thermostat#101]
### Is your feature request related to a problem? Please describe.
i’m using (tying to) use versatile thermostat to add features to my locally controlled tado thermostats. the underlying thermostats are integrated as homekit devices. if i manually change the (target) temperature at the physical thermostat, the homekit devices display the new target temperature (and also turn hvac_mode from `off` to `heat` if necessary).
however, if the target temperature changes at the underlying thermostat, it’s not changing in the versatile thermostat. only state changes (off/heat) are carried over. 

### Describe the solution you'd like
it would be nice if target temperature changes at the underlying thermostat could also be considerd by versatile thermostat

### Describe alternatives you've considered
i could work around this with an automation, but the whole point of VT — as i see it — is to use less automations.

### Additional context
i’m not sure if i made some kind of configuration error, but i tested it with serveral of my thermostats, but i can’t get VT to take the underlying thermostat’s target temperature.

**Comment by diplix** [comment]
turns out, it’s rather easy to automate:
```
alias: Heizung target temp. tado HK → VT
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.tado_smart_radiator_thermostat_va41327xxxxx
    attribute: temperature
    for:
      hours: 0
      minutes: 0
      seconds: 10
    id: bad
  - platform: state
    entity_id:
      - climate.tado_smart_radiator_thermostat_va02783xxxxx
    attribute: temperature
    for:
      hours: 0
      minutes: 0
      seconds: 10
    id: kuche
  - platform: state
    entity_id:
      - climate.tado_smart_thermostat_ru24849xxxxx
    attribute: temperature
    for:
      hours: 0
      minutes: 0
      seconds: 10
    id: kind
  - platform: state
    entity_id:
      - climate.tado_smart_radiator_thermostat_va31056xxxxx
    attribute: temperature
    for:
      hours: 0
      minutes: 0
      seconds: 10
    id: schlafzimmer
  - platform: state
    entity_id:
      - climate.tado_smart_radiator_thermostat_va33157xxxxx
    attribute: temperature
    for:
      hours: 0
      minutes: 0
      seconds: 10
    id: stube
condition:
  - condition: template
    value_template: "{{( state_attr(trigger.entity_id,\"temperature\") | int(-1) ) >0 }}"
action:
  - service: climate.set_temperature
    data:
      temperature: "{{state_attr(trigger.entity_id,\"temperature\")}}"
    target:
      entity_id: "{{ hvac }}"
mode: parallel
max: 10
variables:
  room: "{{trigger.id}}"
  hvac: >-
    {% if room == "kind" %}climate.kind_lokal {% elif room == "stube"
    %}climate.stube_local {% elif room == "schlafzimmer"
    %}climate.schlafzimmer_lokal {% elif room == "kuche" %}climate.kuche_lokal
    {% elif room == "bad" %}climate.bad_lokal {% endif %}
```
