### ISSUE TITLE
Radiator heating despite open window

### ISSUE THREAD

**Issue by lwndp** [jmcollin78/versatile_thermostat#1016]
# Read this carefully

## Version of the custom_component
7.2.7

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - "off"
  - heat
min_temp: 7
max_temp: 30
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 19.6
temperature: 19
hvac_action: heating
preset_mode: comfort
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 14
eco_temp: 18
boost_temp: 22
comfort_temp: 19
frost_away_temp: 14
eco_away_temp: 14.5
boost_away_temp: 17
comfort_away_temp: 17
target_temperature_step: 0.5
ext_current_temperature: 10.05
ac_mode: false
saved_preset_mode: comfort
saved_target_temp: 19
saved_hvac_mode: heat
last_temperature_datetime: "2025-04-25T10:00:04.191391+02:00"
last_ext_temperature_datetime: "2025-04-25T10:07:14.948406+02:00"
minimal_activation_delay_sec: 5
minimal_deactivation_delay_sec: 0
total_energy: 105.19
last_update_datetime: "2025-04-25T10:07:14.951040+02:00"
timezone: Europe/Berlin
temperature_unit: °C
is_device_active: true
device_actives:
  - climate.thermostat_schlafzimmer_thermostat
nb_device_actives: 1
ema_temp: 19.45
is_used_by_central_boiler: false
temperature_slope: 1.3
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
last_change_time_from_vtherm: "2025-04-25T10:00:00.191757+02:00"
presence_sensor_entity_id: binary_sensor.presence_virtual
presence_state: "on"
is_presence_configured: true
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: null
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: "on"
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.fenster_schlafzimmer_dusche
window_delay_sec: 0
window_off_delay_sec: 30
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
is_safety_configured: true
safety_state: "off"
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: "2025-04-25T10:04:23.124498+02:00"
underlying_entities:
  - climate.thermostat_schlafzimmer_thermostat
is_regulated: true
regulated_target_temperature: 18
auto_regulation_mode: auto_regulation_strong
regulation_accumulated_error: -12.07499999999999
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: false
friendly_name: Schlafzimmer
supported_features: 401
```

## Describe the bug
Heating on despite 

I'm trying to and I expect:
Keep window open overnight and switch on heating in the morning. If the window is open, the radiator valve should stay closed until I close the window in the morning.
2 windows are grouped in a sensor group. If one is open, the group is open too.

But I observe this ....
The valve opens (heating turns on) despite open window. Open window is also recognized by VT.

See screenshot:
<img width="506" alt="Image" src="https://github.com/user-attachments/assets/02906028-50c5-4531-a2c3-88e30e1f0ff4" />

I read the documentation on the README.md file and I don't find any relevant information about this issue.
