### ISSUE TITLE
Versatile Thermostat modifies visible target temperature when it should only adjust underlying thermostat silently

### ISSUE THREAD

**Issue by theyv** [jmcollin78/versatile_thermostat#1048]
## Version of the custom_component
7.3.2

## Configuration

My VTherm attributes are the following:
```yaml
climate.ac_pracownia_versatilethermostat
	hvac_modes: off, auto, cool, dry, heat, fan_only
min_temp: 17
max_temp: 30
target_temp_step: 0.1
fan_modes: silent, low, medium, high, full, auto
preset_modes: none, eco, comfort, boost
swing_modes: off, vertical, horizontal, both
current_temperature: 22.2
temperature: 24.5
fan_mode: auto
hvac_action: idle
preset_mode: none
swing_mode: both
is_on: true
hvac_mode: cool
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 30
eco_temp: 24
boost_temp: 22
comfort_temp: 23
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
target_temperature_step: 0.1
ext_current_temperature: 23.7
ac_mode: true
saved_target_temp: 23
saved_preset_mode: none
saved_hvac_mode: off
saved_preset_mod_central_modee: none
saved_hvac_mode_central_mode: null
last_temperature_datetime: 2025-06-18T20:39:45.933197+02:00
last_ext_temperature_datetime: 2025-06-18T20:31:01.586332+02:00
minimal_activation_delay_sec: 10
minimal_deactivation_delay_sec: 0
total_energy: 0
last_update_datetime: 2025-06-18T20:44:14.289228+02:00
timezone: Europe/Warsaw
temperature_unit: °C
is_device_active: false
device_actives: 
nb_device_actives: 0
ema_temp: 22.19
is_used_by_central_boiler: false
temperature_slope: -0.24
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
last_change_time_from_vtherm: 2025-06-18T20:36:42.689034+02:00
presence_sensor_entity_id: null
presence_state: unavailable
is_presence_configured: false
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: null
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: off
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.windowsensor_pracownia_contact
window_delay_sec: 10
window_off_delay_sec: 10
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: off
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: true
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_fast
auto_start_stop_dtmin: 7
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: 2
auto_start_stop_last_switch_date: null
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.ac_pracownia
is_regulated: true
regulated_target_temperature: 26
auto_regulation_mode: auto_regulation_medium
regulation_accumulated_error: 18.46875000000003
auto_fan_mode: auto_fan_medium
current_auto_fan_mode: auto_fan_medium
auto_activated_fan_mode: null
auto_deactivated_fan_mode: auto
auto_regulation_use_device_temp: false
follow_underlying_temp_change: true
friendly_name: AC Pracownia (VersatileThermostat)
supported_features: 441

```

```yaml
climate.ac_salon_versatilethermostat

hvac_modes: off, auto, cool, dry, heat, fan_only
min_temp: 7
max_temp: 35
target_temp_step: 0.1
fan_modes: silent, low, medium, high, full, auto
preset_modes: none, eco, comfort, boost
swing_modes: off, vertical, horizontal, both
current_temperature: 22.4
temperature: 23.5
fan_mode: auto
hvac_action: idle
preset_mode: none
swing_mode: both
is_on: false
hvac_mode: off
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 35
eco_temp: 24
boost_temp: 22
comfort_temp: 23
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
target_temperature_step: 0.1
ext_current_temperature: 23.7
ac_mode: true
saved_target_temp: 21.3
saved_preset_mode: comfort
saved_hvac_mode: cool
saved_preset_mod_central_modee: comfort
saved_hvac_mode_central_mode: null
last_temperature_datetime: 2025-06-18T20:34:02.381669+02:00
last_ext_temperature_datetime: 2025-06-18T20:34:02.381669+02:00
minimal_activation_delay_sec: 10
minimal_deactivation_delay_sec: 0
total_energy: 0
last_update_datetime: 2025-06-18T20:43:20.007455+02:00
timezone: Europe/Warsaw
temperature_unit: °C
is_device_active: false
device_actives: 
nb_device_actives: 0
ema_temp: 22.54
is_used_by_central_boiler: false
temperature_slope: -0.66
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
last_change_time_from_vtherm: 2025-06-18T20:34:02.381693+02:00
presence_sensor_entity_id: null
presence_state: unavailable
is_presence_configured: false
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: null
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: off
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.windowsensor_salon_contact
window_delay_sec: 10
window_off_delay_sec: 10
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: off
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: true
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_fast
auto_start_stop_dtmin: 7
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: 2
auto_start_stop_last_switch_date: null
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.ac_salon
is_regulated: true
regulated_target_temperature: 24.2
auto_regulation_mode: auto_regulation_medium
regulation_accumulated_error: 9.547656250000017
auto_fan_mode: auto_fan_medium
current_auto_fan_mode: auto_fan_medium
auto_activated_fan_mode: null
auto_deactivated_fan_mode: auto
auto_regulation_use_device_temp: false
follow_underlying_temp_change: true
friendly_name: AC Salon (VersatileThermostat)
supported_features: 441
```

## Describe the bug

I'm trying to:

Use two Versatile Thermostats (climate.ac_salon_versatilethermostat and climate.ac_pracownia_versatilethermostat) to control temperature in two separate rooms (living room and home office), with manual changes occasionally made via the Home Assistant UI. I expect that changes in the underlying thermostat temperature would be handled internally, without directly altering the target temperature set in the Versatile Thermostat entity.

And I expect:

That when a Versatile Thermostat reacts to something (e.g., internal climate logic, external condition, or “Follow underlying temp change”), it would adjust the real target of the physical thermostat internally, without visibly changing the target temperature of the Versatile Thermostat itself — unless I change it directly.

But I observe this:
![Image](https://github.com/user-attachments/assets/66d83f69-6fae-4b73-bd27-7239bcd2e896)
![Image](https://github.com/user-attachments/assets/5393d8d6-eaba-4881-82a0-1b3f865c5632)

#
Both thermostats behave unexpectedly:

At 19:36, I manually changed the temperature on the home office thermostat.

Just 4 minutes later, at 19:40, the living room thermostat — which was off — suddenly changed its target temperature to 25.5°C (climate.ac_salon_versatilethermostat), even though I hadn't interacted with it.

I turned it on, manually set it to 23°C and switched to cooling. It jumped back to 25.5°C after about 10 seconds. Only after setting it again did it stay at 23°C.

You can see this behavior in the first attached graph, where the yellow line (target temperature) jumps up and down between ~19:40 and ~19:46.

Similarly, in the second graph (climate.ac_pracownia_versatilethermostat), the home office thermostat, after I initially set it to 22.5°C, started automatically stepping up to 24.5°C without further input. This appears to contradict the expectation that such internal adjustments should not be visible on the Versatile Thermostat entity itself.

So my question is:
Am I right in thinking that these visible jumps in target temperature (of the Versatile Thermostat entity) shouldn't happen? Shouldn't the component only change the temperature of the physical thermostat “under the hood,” without reflecting that change back on the Versatile Thermostat itself?

For context:

The “Follow underlying temp change” option is enabled, but disabling it didn’t seem to change this behavior.
No physical remote controls were used.

## Debug log

I haven’t enabled debug logs yet, as I believe the issue is clearly illustrated by the behavior and the attached graphs.  
If needed, I’m happy to enable logging and provide detailed output upon request.
