### ISSUE TITLE
Set preset target temperature not updating in ac mode

### ISSUE THREAD

**Issue by MaxWaldorf** [jmcollin78/versatile_thermostat#119]
With the changes you have done, I have created the following script to update the comfort target in comfort mode:

```
service: versatile_thermostat.set_preset_temperature
data:
  temperature: "{{ state_attr('climate.thermostat_livingroom_2', 'temperature') | float }}"
  temperature_away: "27"
  preset: comfort_ac
target:
  entity_id: climate.livingroom_ac_2
```

It works great in heat mode but in AC mode I have to go to another preset and go back to comfort for it to take the new value into account...

Désolé, je suis ch... :)
