### ISSUE TITLE
Add an inversion button for "fil pilote"

### ISSUE THREAD

**Issue by apas2** [jmcollin78/versatile_thermostat#124]
hello
fine thermostat
but ( i think) some presets are missing:  sleep , away (hors gel)
could you add these ?
Again, missing (in France) : in your switchs is it possible to add an item to set 'direct' or 'pilote'. so in pilote the output is inverted...
thanks for your work

**Comment by jmcollin78** [comment]
Hello @apas2 ,

Away is available through the presence feature. See documentation for this.
Sleep is not usefull so it is not added to keep it simple. I use Comfort for sleep room and Eco for other room when nobody is there.

> in your switchs is it possible to add an item to set 'direct' or 'pilote'. so in pilote the output is inverted...

I don't understand pilote ? You mean with a pilot wired ? if yes, there is no need to invert the output. Some others users have it working without this. More explanations is needed for your case.

**Comment by apas2** [comment]
Hi
Pilote is for Pilote wire
So inverted output...
When heat is on , Pilote wire order is off.
I did not see this in the doc.
Thank for  your answers.
Fine implémentation anyway.

Le dim. 15 oct. 2023, 18:22, Jean-Marc Collin ***@***.***> a
écrit :

**Comment by jmcollin78** [comment]
Some others use VTherm with a pilot wired (fil pilote). I don't known how they manage to get the "inversion" for pilot.
If you are french may be you can ask here the question: https://forum.hacf.fr/t/nouveau-thermostat-type-proportionnel-avec-gestion-des-presets-portes-et-fenetres-detection-de-mouvement-gestion-de-presence-et-surconsommation/19160

I'm sure you will have an answer.

**Comment by apas2** [comment]
Thanks, I'll check it out.

Le mar. 17 oct. 2023, 23:41, Jean-Marc Collin ***@***.***> a
écrit :

**Comment by jmcollin78** [comment]
I close this question. Don't hesitate to reopen if you think it is relevant.

**Comment by jmcollin78** [comment]
Finally, the need of inversion seems legit. I reopen this.

You can add a virtual switch waiting for the feature to be implemented:
``` 
- platform: template
    switches:
      convecteur_salon:
        friendly_name: Convecteur Salon Inv
        value_template: "{{ is_state('switch.convecteur_salon', 'off') }}"
        turn_on:
          service: switch.turn_off
          data:
            entity_id: switch.convecteur_salon
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.convecteur_cuisine
        icon_template: "{% if is_state('switch.convecteur_salon', 'on') %}mdi:radiator-disabled{% else %}mdi:radiator{% endif %}"
```
