### ISSUE TITLE
Ability to limit virtual climates to heat + off only

### ISSUE THREAD

**Issue by lichtl** [jmcollin78/versatile_thermostat#126]
**Is your feature request related to a problem? Please describe.**
I run multiple types of Zigbee TVRs as well as some DECT ones. Some of them do offer beside off and heat also an automatic mode (this can be used for example to use them on some internal schedulers).

**Describe the solution you'd like**
It would be great having an option to limit the "virtual" climates over TVR to only report heat + off (probably via a checkbox during setup) to then have all versatile thermostat generated climates looking the same.

**Additional context**
Below a tile screenshot. The first 2 TVRs offer the auto mode (which is then passed through). It would be great if they only would offer the heat + off like the 3 ones below
![image](https://github.com/jmcollin78/versatile_thermostat/assets/1228155/ab7ff34c-a9f2-4b4d-b6a9-85a44c122bee)

**Comment by lichtl** [comment]
Below 2 different Zigbee TVRs data. 

```
hvac_modes:
  - 'off'
  - heat
min_temp: 5
max_temp: 30
target_temp_step: 0.5
preset_modes:
  - none
  - auto
  - manual
  - holiday
current_temperature: 20.7
temperature: 17
preset_mode: manual
battery_low: false
boost_timeset_countdown: 0
child_lock: UNLOCK
comfort_temperature: 21
current_heating_setpoint: 17
eco_temperature: 19
error_status: 0
frost_protection: 'OFF'
heating_stop: 'OFF'
holiday_start_stop: 2021/01/01 01:01 | 2021/01/01 01:01
holiday_temperature: 17
last_seen: '2023-10-19T07:36:31.282Z'
linkquality: 87
local_temperature: 20.7
local_temperature_calibration: 0
online: 'ON'
open_window: 'OFF'
open_window_temperature: 14
preset: manual
schedule:
  schedule: 06:00/19 18:00/19
  week_day: monday
schedule_friday: 06:00/19 18:00/19 24:00/18
schedule_monday: 06:00/19 18:00/19 24:00/18
schedule_saturday: 06:00/19 18:00/19 24:00/18
schedule_sunday: 06:00/19 18:00/19 24:00/18
schedule_thursday: 06:00/19 18:00/19 24:00/18
schedule_tuesday: 06:00/19 18:00/19 24:00/18
schedule_wednesday: 06:00/19 18:00/19 24:00/18
system_mode: heat
update:
  installed_version: -1
  latest_version: -1
  state: idle
update_available: null
working_day: mon_sun
friendly_name: Thermostat Carsten Zigbee
supported_features: 17
```


```
hvac_modes:
  - 'off'
  - heat
  - auto
min_temp: 5
max_temp: 30
target_temp_step: 0.5
current_temperature: 21.2
temperature: 17
anti_scaling: 'ON'
away_mode: 'OFF'
battery_low: false
child_lock: UNLOCK
current_heating_setpoint: 17
frost_detection: 'ON'
heating: null
last_seen: '2023-10-19T07:39:17.396Z'
linkquality: 102
local_temperature: 21.2
local_temperature_calibration: 0
system_mode: heat
window_detection: 'OFF'
friendly_name: Thermostat Bad Zigbee
supported_features: 1
```
