### ISSUE TITLE
Add a VTherm type to command directly the valve of a TRV

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#131]
This idea is to implement natively what is described here:

```
alias: TEST
description: >-
  Commande l'ouverture d'une vanne en fonction du pourcentage de chauffe calculé
trigger:
  - platform: numeric_state
    entity_id: climate.thermostat_bureau
    attribute: on_percent
condition: []
action:
  - service: number.set_value
    data:
      value: "{{ state_attr('climate.thermostat_bureau', 'on_percent') | float(0) * 100 }}"
    target:
      entity_id: number.portail_et_portillon_dooropenduration
mode: single
```

Sur changement du pourcentage de chauffe (l’attribut on_percent du VTherm), tu set la valeur de ta valve avec la valeur du on_percent.

Ce on_percent vaut 1 (100%) quand le radiateur doit chauffer à 100% (-> valve totalement ouverte) ou 0 (0%) quand il ne doit pas chauffer du tout.

C’est tellement parfait que je vais certainement l’implémenter nativement dans le VTherm dans une future version.
