### ISSUE TITLE
size of climate entities in database

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#137]
Using the following SQL statement to analyse my `home-assistant_v2.db` I realised that the 12 `climate` entities I've setup with versatile_thermostat make up 10% of my entire database (`LENGTH(state_attributes.shared_attrs) AS bytes`), which is a lot as I have many more devices unrelated to versatile_thermostat that need much less space in the recorder database.

I don't know what VTherm saves there, but I hope the necessary space in the db can be reduced.

```sql
SELECT 
  COUNT(state_id) AS cnt, 
  COUNT(state_id) * 100 / (
    SELECT 
      COUNT(state_id) 
    FROM 
      states
  ) AS cnt_pct, 
  SUM(
    LENGTH(state_attributes.shared_attrs)
  ) AS bytes, 
  SUM(
    LENGTH(state_attributes.shared_attrs)
  ) * 100 / (
    SELECT 
      SUM(
        LENGTH(state_attributes.shared_attrs)
      ) 
    FROM 
      states
  ) AS bytes_pct, 
  states_meta.entity_id 
FROM 
  states 
LEFT JOIN state_attributes ON (states.attributes_id=state_attributes.attributes_id)
LEFT JOIN states_meta ON (states.metadata_id=states_meta.metadata_id)
GROUP BY 
  states.metadata_id 
ORDER BY 
  cnt DESC;
```
(As the result is sorted by the count in the first column, they might not be visible at the top, but when exporting the result to Excel and sorting by the length column, they will be near to the top.)

**Comment by jmcollin78** [comment]
Hello,

interesting. Can you show me a result of the request ? (only the first one)

**Comment by jmcollin78** [comment]
I have a bad request when trying to execute your query:

`400: Bad Request`

**Comment by maia** [comment]
The current version of SQLite Web does not work, see: https://github.com/hassio-addons/addon-sqlite-web/issues/281 . You will need to downgrade or untar a HA backup with sqlite3 locally (it's preinstalled on MacOS). I now have a recorder config (see below), but I didn't until 2 days ago, when I realised by db is at 6GB, so I started to exclude the Aqara Smart Plug devices, set the commit_interval to 30 sec and the keep_days to 7. A reboot and purge&repack later I'm down by a lot, but I'm still seeing excluded entities in the db, will have to wait a week and see.
```
recorder:
  commit_interval: 30
  purge_keep_days: 7
  exclude:
    domains:
      - device_tracker
      - media_player
      - uptime
    entity_globs:
      - sensor.*_device_temperature
      - sensor.*_steckdose_power
      - sensor.*_steckdose_energy
      - switch.*_power_outage_memory
      - switch.*_led_disabled_night
      - switch.*_auto_off
      - switch.*_button_lock
      - number.*_overload_protection
      - binary_sensor.*_consumer_connected
      - update.*_steckdose
      - sensor.*_estimated_distance
      - sensor.*_geschatzte_entfernung
      - sensor.*_volts
```
Here are a few lines of the query result (the first few and then a few climate lines):

```
118873|3|59250113|100|sensor.schlafzimmer_aqara_steckdose_power
118831|3|59886501|100|sensor.wohnzimmer_regal_aqara_steckdose_power
117940|3|57851719|100|sensor.kuche_aqara_steckdose_power
103789|2|47601893|100|binary_sensor.schlafzimmer_aqara_steckdose_consumer_connected
103765|2|46750150|100|binary_sensor.kuche_aqara_steckdose_consumer_connected
103759|2|48140075|100|binary_sensor.wohnzimmer_regal_aqara_steckdose_consumer_connected
…
10035|0|16405287|100|climate.kuche_heizung
…
8995|0|14220206|100|climate.schlafzimmer_heizung
5198|0|8046658|100|climate.wohnzimmer_heizung
…
```
The percentage calculations don't work. But if you divide the bytes length (third column) by the first column (count) you'll see that e.g. the sensor.*_power saves about 500 bytes in state_attributes, where the vtherm climate devices save about 1.500 bytes per entry.
