### ISSUE TITLE
Add Preset Hors Gel

### ISSUE THREAD

**Issue by loicdeschamps** [jmcollin78/versatile_thermostat#147]
**Is your feature request related to a problem? Please describe.**
It's interesting to have this preset (likae Confort, Boost...)

Regards

**Comment by jmcollin78** [comment]
Hello, many people needs many preset.
I cannot implements all presets and what I suggest it to use the manuel preset for this.

You can also automatize switching to "hors gel" using the service which is here exactly for that specific needs:
```
service: climate.set_temperature
data:
  temperature: 12
target:
  device_id: <my device id>
```
