### ISSUE TITLE
Add more option for presence / occupancy

### ISSUE THREAD

**Issue by Julien-Decoen** [jmcollin78/versatile_thermostat#163]
**Is your feature request related to a problem? Please describe.**
I've created a group of person for my family but i can't use it as presence entity in versatile_thermostat.

**Describe the solution you'd like**
It could be useful to use a group entity or a list on entities as entity for presence configuration.

**Comment by jmcollin78** [comment]
The question have already be addressed. VTherm need a binary_sensor or an input_boolean for presence sensor.

Or a group of person is a `person` entity and cannot be used as presence sensor.

To do so, you must use a template like this:

```yaml
- binary_sensor:
    - name: someone_home
      unique_id: someone_home
      state: "{{is_state('person.jmc', 'home') or is_state('person.chr', 'home') or is_state('input_boolean.force_presence', 'on')}}"
      device_class: occupancy
```
