### ISSUE TITLE
Add multi-select person or binary_sensor or input_boolean for presence

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#166]
In fact groups can't be used for that need, I agree. And I understand that template binary_sensor are very useful for specific needs, specially if you want to combine other entities domains, entity's attributes values or making complex logic with OR and AND.

But your work with the config flow is great and it could be a shame to going away from the UI to answer to the simple question : which entities make my house occupied ?

A simple multi-select entities field (with binary_sensor and input_boolean of course) could be very useful, especially for people who's not familiar with yaml.

_Originally posted by @Julien-Decoen in https://github.com/jmcollin78/versatile_thermostat/issues/163#issuecomment-1793878736_

**Comment by Julien-Decoen** [comment]
Thanks for creating this new issue.

The **EntitySelectorConfig** method have a param to select multiple entities :) 

You can see an example [here](https://github.com/jseidl/hass-magic_areas/blob/master/custom_components/magic_areas/config_flow.py#L169)

**Comment by jmcollin78** [comment]
It seems you know how to do. I would love to have a PR from you 👍

**Comment by syberx** [comment]
Hello, I'm experiencing a similar issue where I have selected a group for presence detection (named jemandzuhause) which correctly identifies the home or not_home status in the device. However, it doesn't seem to trigger the ECO temperatures as it should. Is there a workaround or a fix that could help address this problem?

**Comment by jmcollin78** [comment]
> Hello, I'm experiencing a similar issue where I have selected a group for presence detection (named jemandzuhause) which correctly identifies the home or not_home status in the device. However, it doesn't seem to trigger the ECO temperatures as it should. Is there a workaround or a fix that could help address this problem?

Yes, @syberx,

The workaround is to have a template sensor like this (in the template section of your `configuration.yaml` file):

```
- binary_sensor:
    - name: someone_home
      unique_id: someone_home
      state: "{{is_state('person.jmc', 'home') or is_state('person.chr', 'home') or is_state('input_boolean.force_presence', 'on')}}"
      device_class: occupancy
```
