### ISSUE TITLE
Why doesn't VT turn off my AC when the set temperature is reached?

### ISSUE THREAD

**Issue by escamoteur** [jmcollin78/versatile_thermostat#182]
My VTherm attributes are the following:
```yaml
hvac_modes:
  - auto
  - cool
  - dry
  - heat
  - fan_only
  - "off"
min_temp: 15
max_temp: 23
target_temp_step: 1
fan_modes:
  - Auto
  - Full
  - High
  - Medium
  - Low
  - Silent
preset_modes:
  - none
  - eco
  - comfort
  - boost
swing_modes:
  - "Off"
  - Vertical
  - Horizontal
  - Both
current_temperature: 19.2
temperature: 23
fan_mode: Auto
preset_mode: none
swing_mode: Horizontal
hvac_action: null
hvac_mode: "off"
type: null
eco_temp: 17
boost_temp: 24
comfort_temp: 20
eco_away_temp: 17
boost_away_temp: 17
comfort_away_temp: 17
power_temp: 13
ext_current_temperature: 8.7
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 23
saved_hvac_mode: "off"
window_state: "off"
motion_state: null
overpowering_state: null
presence_state: null
window_auto_state: "off"
window_bypass_state: false
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2023-11-10T10:06:00.962124+01:00"
last_ext_temperature_datetime: "2023-11-10T10:08:28.677216+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2023-11-10T10:08:28.688305+01:00"
timezone: Europe/Berlin
window_sensor_entity_id: binary_sensor.balkonture_kuche_contact
window_delay_sec: 30
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: null
presence_sensor_entity_id: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.midea_ac_153931627969932
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
regulated_target_temperature: 25
regulation_accumulated_error: 20
friendly_name: Heizung_Wohnzimmer
supported_features: 57
```

## Describe the bug

I'm trying to control my AC for heating with an external temperature sensor. It seems to work in generally but I observed,n that after reaching the target temperature the ACs set temperature was reduced below my set temperature but the AC was not switched off.
I'm pretty sure I made some mistake in my config but don't know what's wrong.
