### ISSUE TITLE
switching from HEAT to COOL or viceversa does load the temperature preset on AC mode and ThermostatOverSwitch

### ISSUE THREAD

**Issue by muchasuerte** [jmcollin78/versatile_thermostat#185]
## Version of the custom_component
Version: 4.0.1

## Configuration

My VTherm attributes are the following:
```yaml
vac_modes: heat, cool, off
min_temp: 7
max_temp: 35
preset_modes: none, eco, comfort, boost
current_temperature: 19.5
temperature: 29
hvac_action: idle
preset_mode: eco
hvac_mode: cool
type: null
eco_temp: 16
boost_temp: 20
comfort_temp: 18
eco_away_temp: null
boost_away_temp: null
comfort_away_temp: null
power_temp: null
ext_current_temperature: 17.1
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 29
saved_hvac_mode: null
window_state: off
motion_state: null
overpowering_state: null
presence_state: null
window_auto_state: off
window_bypass_state: false
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2023-11-11T16:57:21.260861+01:00
last_ext_temperature_datetime: 2023-11-11T16:57:21.260861+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 2
mean_cycle_power: 0
total_energy: 0
last_update_datetime: 2023-11-11T16:57:21.341504+01:00
timezone: Europe/Rome
window_sensor_entity_id: null
window_delay_sec: null
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: null
presence_sensor_entity_id: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
is_over_switch: true
underlying_switch_0: switch.fancoil_camera_matrimoniale
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
friendly_name: Termostato Camera Matrimoniale
supported_features: 17
```

## Describe the bug
I'm trying to:
change  the hvac_mode: from cool to heat or vice versa

And I expect:
eco_temp: 16 if the hvac_mode is heat
eco_temp: 29 if the hvac_mode is cool

But I observe this ....
but  I'm always see 29 as target temperature
