### ISSUE TITLE
Thermostat continues heating while temperature exceed the target

### ISSUE THREAD

**Issue by FermedePommerieux** [jmcollin78/versatile_thermostat#192]
<img width="528" alt="Capture d’écran 2023-11-13 à 18 35 50" src="https://github.com/jmcollin78/versatile_thermostat/assets/82572754/e8ff240e-8f04-4e42-a5c5-8723771bfbf4">

## Version of the custom_component
4.0.4

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: heat, off
min_temp: 7
max_temp: 21
target_temp_step: 0.1
preset_modes: none, eco, comfort, boost
current_temperature: 22.2
temperature: 19
hvac_action: idle
preset_mode: comfort
is_on: true
hvac_mode: heat
type: null
eco_temp: 17
boost_temp: 21
comfort_temp: 19
eco_away_temp: 15
boost_away_temp: 17
comfort_away_temp: 17
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 16.44
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: comfort
saved_target_temp: 19
saved_hvac_mode: null
window_state: off
motion_state: null
overpowering_state: null
presence_state: on
window_auto_state: off
window_bypass_state: false
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2023-11-13T18:40:58.890757+01:00
last_ext_temperature_datetime: 2023-11-13T18:36:55.268198+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 3000
mean_cycle_power: 0
total_energy: 73644.17
last_update_datetime: 2023-11-13T18:40:58.996032+01:00
timezone: Europe/Paris
window_sensor_entity_id: null
window_delay_sec: 30
window_auto_open_threshold: 1
window_auto_close_threshold: 0.05
window_auto_max_duration: 60
motion_sensor_entity_id: null
presence_sensor_entity_id: input_boolean.homekit_rabatteurs_presence_switch
power_sensor_entity_id: null
max_power_sensor_entity_id: null
temperature_unit: °C
is_device_active: false
is_over_switch: true
is_inversed: false
underlying_switch_0: switch.rabatteurs_chauffage
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.05
friendly_name: Rabatteurs
supported_features: 17
```

## Describe the bug
In a small house, if the thermostat controls the electric heating and the wood stove is lit, and if logically the temperature exceeds the set temperature, the thermostat continues to activate the electric radiators

I'm trying to:

And I expect:

But I observe this ....

this also happens in another house, the switch ins't turn off while temperature exceed the target, I had to create a automation to avoid this. 

## Debug log

2023-11-12 21:39:18.441 WARNING (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Rabatteurs-switch.rabatteurs_chauffage - The hvac mode is ON, but the underlying device is not ON. Turning on device switch.rabatteurs_chauffage

```text

Add your logs here.

```
