### ISSUE TITLE
After changing coef_int or coef_ext the heaters continue to heat even if power_percent is 0

### ISSUE THREAD

**Issue by gael1980** [jmcollin78/versatile_thermostat#196]
Bonjour,

Ce matin, mon chauffage a continué de fonctionner alors que personne n'était à la maison.

Comme vous pouvez le voir sur ce graphique, la maison est bien "absente", le % power retombe bien à 0, la consigne passe bien à 16, mais les switchs continue de fonctionner.

<img width="1365" alt="Capture d’écran 2023-11-16 à 12 58 20" src="https://github.com/jmcollin78/versatile_thermostat/assets/35664315/ccc904ea-5ff9-4db1-9822-0341dc618bce">

Les 4 chauffages ont un cycle non cohérent, mais régulier. 
Ces 4 chauffages sont sur le même vtherm.

Non présent sur la capture, mais j'ai vérifié le security state, qui était bien sur off

## Version of the custom_component
Vtherm : 4.0.4

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: heat, off
min_temp: 7
max_temp: 25
target_temp_step: 0.1
preset_modes: none, eco, comfort, boost, activity
current_temperature: 18.6
temperature: 19
hvac_action: heating
preset_mode: activity
is_on: true
hvac_mode: heat
type: null
eco_temp: 16
boost_temp: 19
comfort_temp: 18
eco_away_temp: 16
boost_away_temp: 16
comfort_away_temp: 16
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 11.2
ac_mode: false
current_power: 2620
current_power_max: 10000
saved_preset_mode: activity
saved_target_temp: 19
saved_hvac_mode: null
window_state: off
motion_state: on
overpowering_state: false
presence_state: on
window_auto_state: off
window_bypass_state: false
security_delay_min: 240
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2023-11-16T13:01:28.684559+01:00
last_ext_temperature_datetime: 2023-11-16T12:41:28.671069+01:00
security_state: false
minimal_activation_delay_sec: 120
device_power: 3000
mean_cycle_power: 2250
total_energy: 1818651.51
last_update_datetime: 2023-11-16T13:01:59.538614+01:00
timezone: Europe/Paris
window_sensor_entity_id: binary_sensor.bas_ouvert
window_delay_sec: 30
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: input_boolean.fake_motion_sam
presence_sensor_entity_id: binary_sensor.maison_occupee
power_sensor_entity_id: sensor.lixee_papp
max_power_sensor_entity_id: input_number.p_max
temperature_unit: °C
is_device_active: true
is_over_switch: true
is_inversed: false
underlying_switch_0: switch.chauffage_cuisine
underlying_switch_1: switch.chauffage_salon
underlying_switch_2: switch.chauffage_manger
underlying_switch_3: switch.chauffage_couloir_entree
on_percent: 0.75
power_percent: 75
on_time_sec: 448
off_time_sec: 151
cycle_min: 10
function: tpi
tpi_coef_int: 0.7
tpi_coef_ext: 0.06
icon: mdi:fridge
friendly_name: Thermostat cuisine
supported_features: 17

```
