### ISSUE TITLE
le chauffage continue de chauffer alors qu'il est en mode Eco

### ISSUE THREAD

**Issue by Merangle** [jmcollin78/versatile_thermostat#198]
dernière version de Vtherm

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: heat, off
min_temp: 7
max_temp: 25
target_temp_step: 0.1
preset_modes: none, eco, comfort, boost
current_temperature: 19.8
temperature: 17
hvac_action: idle
preset_mode: eco
is_on: true
hvac_mode: heat
type: null
eco_temp: 17
boost_temp: 20
comfort_temp: 19
eco_away_temp: 17
boost_away_temp: 21
comfort_away_temp: 18.5
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 12.02
ac_mode: false
current_power: 1673.44
current_power_max: 12000
saved_preset_mode: eco
saved_target_temp: 17
saved_hvac_mode: null
window_state: off
motion_state: null
overpowering_state: false
presence_state: on
window_auto_state: off
window_bypass_state: false
security_delay_min: 120
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2023-11-17T14:36:59.951527+01:00
last_ext_temperature_datetime: 2023-11-17T14:40:55.467852+01:00
security_state: false
minimal_activation_delay_sec: 60
device_power: 1.68
mean_cycle_power: 0
total_energy: 43.11
last_update_datetime: 2023-11-17T14:40:55.553760+01:00
timezone: Europe/Paris
window_sensor_entity_id: null
window_delay_sec: 30
window_auto_open_threshold: 0.05
window_auto_close_threshold: 0
window_auto_max_duration: 60
motion_sensor_entity_id: null
presence_sensor_entity_id: binary_sensor.parents_home
power_sensor_entity_id: sensor.parents_power
max_power_sensor_entity_id: sensor.max_power
temperature_unit: °C
is_device_active: false
is_over_switch: true
is_inversed: false
underlying_switch_0: switch.parents_switch
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 600
cycle_min: 10
function: tpi
tpi_coef_int: 0.7
tpi_coef_ext: 0.01
friendly_name: Parents
supported_features: 17
```

![Vtherm](https://github.com/jmcollin78/versatile_thermostat/assets/19497834/bdbef65b-5107-4d6c-a11b-24df7450bc89)

## Describe the bug
Le chauffage continue alors que le mode Eco est actif.

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log

```
