### ISSUE TITLE
Uncessary heating started after Hass reboot

### ISSUE THREAD

**Issue by Merangle** [jmcollin78/versatile_thermostat#204]
My VTherm attributes are the following:
```yaml
hvac_modes: heat, off
min_temp: 7
max_temp: 25
target_temp_step: 0.1
preset_modes: none, eco, comfort, boost
current_temperature: 17.9
temperature: 17
hvac_action: idle
preset_mode: eco
friendly_name: Camille
supported_features: 17
is_on: true
hvac_mode: heat
eco_temp: 17
boost_temp: 20
comfort_temp: 19.5
eco_away_temp: 17
boost_away_temp: 21
comfort_away_temp: 18.5
power_temp: 13
target_temperature_step: 0.1
ac_mode: false
saved_preset_mode: eco
saved_target_temp: 17
window_state: off
window_auto_state: off
window_bypass_state: false
security_delay_min: 120
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2023-11-18T14:30:10.556049+01:00
last_ext_temperature_datetime: 2023-11-18T14:29:23.876292+01:00
security_state: false
minimal_activation_delay_sec: 60
device_power: 1
mean_cycle_power: 0
total_energy: 24.35
last_update_datetime: 2023-11-18T14:30:10.558754+01:00
timezone: Europe/Paris
window_delay_sec: 30
window_auto_open_threshold: 0.05
window_auto_close_threshold: 0
window_auto_max_duration: 60
presence_sensor_entity_id: binary_sensor.patricia_home
power_sensor_entity_id: sensor.camille_power
max_power_sensor_entity_id: sensor.max_power
temperature_unit: °C
is_device_active: false
is_over_switch: true
is_inversed: false
underlying_switch_0: switch.camille_switch
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 600
cycle_min: 10
function: tpi
tpi_coef_int: 0.75
tpi_coef_ext: 0.02
ext_current_temperature: 11.53
current_power: 1.3
current_power_max: 12000
presence_state: off
overpowering_state: false
```

## Describe the bug
Juste après un reboot, le chauffage est déclenché alors que ce n'est pas nécessaire.
And I expect:
le chauffage ne devrait pas se redéclencher après un reboot de Hass si ce n'est pas nécessaire.

I read the documentation on the README.md file and I don't find any relevant information about this issue.

![reboot](https://github.com/jmcollin78/versatile_thermostat/assets/19497834/d76283f9-9dd6-417a-b08b-4213f80a346f)

On voit Trois reboot (celui de ce matin pour mettre à jour en 4.1.0 et deux fois cet après-midi pour tester la remise à jour des coef-int et coef_ext
Ce problème existe sur tous les radiateurs.
