### ISSUE TITLE
Can't configure without outside sensor

### ISSUE THREAD

**Issue by mgoetze5** [jmcollin78/versatile_thermostat#246]
## Version of the custom_component
4.2

## Configuration

I couldn't make one

## Describe the bug
According to the README: "a temperature sensor entity giving the outside temperature. If you don't have an external sensor, you can use local weather integration"

However when I tried this I get the following error:

User input malformed: Entity weather.forecast_home belongs to domain weather, expected ['sensor', 'input_number'] for dictionary value @ data['external_temperature_sensor_entity_id']

And since "External temperature sensor entity id" is a required field I can't create a VTherm device.

**Comment by jmcollin78** [comment]
Hello,

The `weather` entity is not a temperature sensor. You have to find a sensor which gives a temperature like this one:

![Capture d’écran 2023-12-05 à 07 08 13](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/e7db4ad6-73f1-49cd-821b-be1f680c53dc)

In France, the Meteo France integration is giving this out of the box.

If you don't have this, you will have to find another meteo integration or create a virtual sensor which exposes the temperature of your `weather` entity.

**Comment by jmcollin78** [comment]
OpenWeatherMap gives you the external temperature as a sensor out of the box`sensor.openweathermap_temperature`

**Comment by jmcollin78** [comment]
I close because it is not an issue but we can continue the discussion if needed.

**Comment by ovizii** [comment]
Just to add some info, the integration "Meteorologisk institutt (Met.no)" also does not deliver the tempretaure as a "sensor". I guess I'll have to switch to OpenWeatherMap as suggested.

The entity `weather.forecast_myCity` has the following state attributes: 


```
temperature: 6.7
dew_point: 4.6
temperature_unit: °C
humidity: 87
cloud_coverage: 64.1
pressure: 1007.2
pressure_unit: hPa
wind_bearing: 253.3
wind_speed: 24.8
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast:
  - condition: rainy
    datetime: "2024-03-24T11:00:00+00:00"
    wind_bearing: 253.3
    temperature: 7.2
    templow: 4.2
    wind_speed: 24.8
    precipitation: 0.6
    humidity: 87
  - condition: cloudy
    datetime: "2024-03-25T11:00:00+00:00"
    wind_bearing: 234.8
    temperature: 10.6
    templow: 1.9
    wind_speed: 21.2
    precipitation: 0
    humidity: 50
  - condition: partlycloudy
    datetime: "2024-03-26T11:00:00+00:00"
    wind_bearing: 98.1
    temperature: 15.2
    templow: 1.5
    wind_speed: 19.1
    precipitation: 0
    humidity: 54
  - condition: rainy
    datetime: "2024-03-27T11:00:00+00:00"
    wind_bearing: 259.9
    temperature: 9.9
    templow: 5.5
    wind_speed: 14.8
    precipitation: 0.8
    humidity: 71
  - condition: cloudy
    datetime: "2024-03-28T11:00:00+00:00"
    wind_bearing: 228.6
    temperature: 15.2
    templow: 5
    wind_speed: 24.5
    precipitation: 1.2
    humidity: 45
  - condition: cloudy
    datetime: "2024-03-29T11:00:00+00:00"
    wind_bearing: 234.2
    temperature: 21.1
    templow: 7.9
    wind_speed: 12.6
    precipitation: 0.9
    humidity: 43
attribution: >-
  Weather forecast from met.no, delivered by the Norwegian Meteorological
  Institute.
friendly_name: Forecast myCity
supported_features: 3
```
