### ISSUE TITLE
Add into documentation for css around the thermostat front component

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#27]
.. so that it will be possible to immediatly see when a thermostat is i security mode or in power mode.

**Comment by jmcollin78** [comment]
here is a card-mod css code :

          card_mod:
            style: |
              {% if is_state('binary_sensor.thermostat_chambre_security_state', 'on') %}
              ha-card .body .sensor-heading ha-icon[icon="mdi:alert-outline"] {
                color: red;
              }
              {% endif %}
              {% if is_state('binary_sensor.thermostat_chambre_overpowering_state', 'on') %}
              ha-card .body .sensor-heading ha-icon[icon="mdi:flash"] {
                color: red;
              }
              {% endif %}

**Comment by jmcollin78** [comment]
Theme example to have colored binary_entities:

```
frontend:
  themes:
    versatile_thermostat_theme:
      state-binary_sensor-safety-on-color: "#FF0B0B"
      state-binary_sensor-power-on-color: "#FF0B0B"
      state-binary_sensor-window-on-color: "rgb(156, 39, 176)"
      state-binary_sensor-motion-on-color: "rgb(156, 39, 176)"
      state-binary_sensor-presence-on-color: "lightgreen"
```
