### ISSUE TITLE
Fix documentation about group of person in documentation

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#270]
Group of person don't work in the presence sensor.
Change the documentation and add the example with the template sensor:

```
- binary_sensor:
    - name: maison_occupee
      unique_id: maison_occupee
      state: "{{is_state('person.jmc', 'home') or is_state('person.chr', 'home') or is_state('input_boolean.force_presence', 'on')}}"
      device_class: occupancy
```
