### ISSUE TITLE
VTherm attempts to set a temperature below the min_temp causing to set the target temp to the max_temp 

### ISSUE THREAD

**Issue by gioele-antoci** [jmcollin78/versatile_thermostat#272]
## Version of the custom_component
4.3

## Configuration
versatile_thermostat:
     auto_regulation_expert:
         kp: 0.4
         ki: 0.08
         k_ext: 0.0
         offset_max: 12
         stabilization_threshold: 0.1
         accumulated_error_threshold: 50

## Describe the bug
You can see in the screenshot that I lower the temperature manually until I force the regulated temperature to be set below the min temperature. We don't see to have any guards in that respect and my Midea climate control wraps around and instead sets the max temperature 

![image](https://github.com/jmcollin78/versatile_thermostat/assets/18650836/76ed1003-6196-4e1c-8a26-55bb6abe5bf4)

My VTherm attributes are the following:
```yaml
hvac_modes: off, auto, cool, dry, heat, fan_only
min_temp: 17
max_temp: 35
target_temp_step: 0.5
preset_modes: none, eco, comfort, boost
current_temperature: 23.5
temperature: 18
preset_mode: none
friendly_name: Upstairs Versatile Thermostat
supported_features: 121
is_on: true
hvac_mode: heat
frost_temp: 0
eco_temp: 17
boost_temp: 24
comfort_temp: 21
frost_away_temp: 17
eco_away_temp: 17
boost_away_temp: 17
comfort_away_temp: 17
target_temperature_step: 0.5
ext_current_temperature: 2
ac_mode: false
saved_preset_mode: none
saved_target_temp: 18
window_state: off
window_auto_state: off
window_bypass_state: false
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2023-12-12T23:35:20.612277-05:00
last_ext_temperature_datetime: 2023-12-12T23:34:38.950651-05:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
total_energy: 0
last_update_datetime: 2023-12-12T23:35:43.374748-05:00
timezone: America/Toronto
window_auto_enabled: false
temperature_unit: °C
is_device_active: true
is_over_climate: true
underlying_climate_0: climate.150633093090947_climate
is_regulated: true
regulated_target_temperature: 15.5
auto_regulation_mode: auto_regulation_expert
regulation_accumulated_error: -5.5
auto_fan_mode: auto_fan_medium
fan_modes: Silent, Low, Medium, High, Full, Auto
swing_modes: Off, Vertical, Horizontal, Both
fan_mode: Low
swing_mode: Off
aux_heat: off
current_auto_fan_mode: auto_fan_medium
ema_temp: 23.5
```

## Debug log
I can paste the logs if needed
