### ISSUE TITLE
Strange behavior version 5.1.0

### ISSUE THREAD

**Issue by Bergoglio** [jmcollin78/versatile_thermostat#292]
## Version of the custom_component

5.1.0

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: heat, off
min_temp: 7
max_temp: 35
target_temp_step: 0.1
preset_modes: none, frost, eco, comfort, boost
current_temperature: 22.1
temperature: 22
hvac_action: idle
preset_mode: none
is_on: true
hvac_mode: heat
type: null
frost_temp: 0
eco_temp: 20
boost_temp: 23.5
comfort_temp: 22.5
frost_away_temp: 17
eco_away_temp: 19.5
boost_away_temp: 22.5
comfort_away_temp: 21.5
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 17.5
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: comfort
saved_target_temp: 22
saved_hvac_mode: null
window_state: off
motion_state: null
overpowering_state: null
presence_state: off
window_auto_state: off
window_bypass_state: false
security_delay_min: 60
security_min_on_percent: 0.7
security_default_on_percent: 0.25
last_temperature_datetime: 2023-12-22T13:32:58.639198+01:00
last_ext_temperature_datetime: 2023-12-22T13:30:14.910058+01:00
security_state: false
minimal_activation_delay_sec: 300
device_power: 0.1
mean_cycle_power: null
total_energy: 22.61
last_update_datetime: 2023-12-22T13:32:58.653874+01:00
timezone: Europe/Rome
window_sensor_entity_id: binary_sensor.finestra_letto_nonna_opposto
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: null
presence_sensor_entity_id: person.renata_busso
power_sensor_entity_id: null
max_power_sensor_entity_id: null
temperature_unit: °C
is_device_active: false
ema_temp: 22.1
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.letto_caldo_nonna
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
friendly_name: Riscaldamento letto Nonna
supported_features: 17
```

## Describe the bug
I have 5 Versatile Thermostats that are over 5 generic thermostats (one for one)
I created 5 cards in the dashboard (one for each Versatile Thermostat)
I also have Simple Scheduler component that change temp presets (comfort, eco or boost) on VTherm (time program)
All worked fine before yesterday that I made upgrade to Versatile 5.1.0 from series 4
Now all cards show me not comfort, eco or boost but manual and the target temperatures settled are different from the presets (22°C for all thermostats)
I changed (not only once) from manual to the right preset and after one or max two minutes, all Versatile Thermostats change them again in manual and 22°C

I read the documentation on the README.md file and I don't find any relevant information about this issue.
