### ISSUE TITLE
Logbook warning for underlying switch on restart of HA questionable

### ISSUE THREAD

**Issue by mleiber** [jmcollin78/versatile_thermostat#307]
## Version of the custom_component

5.5.1

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: heat, off
min_temp: 15
max_temp: 25
target_temp_step: 0.1
preset_modes: none
current_temperature: 22.3
temperature: 22.3
hvac_action: idle
preset_mode: none
is_on: true
hvac_mode: heat
type: null
frost_temp: 0
eco_temp: 0
boost_temp: 0
comfort_temp: 0
frost_away_temp: 15
eco_away_temp: 18
boost_away_temp: 18
comfort_away_temp: 18
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 9.5
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 22.3
saved_hvac_mode: null
window_state: off
motion_state: null
overpowering_state: null
presence_state: null
window_auto_state: off
window_bypass_state: false
security_delay_min: 120
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-01-02T15:42:32.135717+01:00
last_ext_temperature_datetime: 2024-01-02T16:12:32.166309+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 0
mean_cycle_power: null
total_energy: 29.26
last_update_datetime: 2024-01-02T16:18:17.315665+01:00
timezone: Europe/Berlin
window_sensor_entity_id: binary_sensor.verschluss_wohnhalle
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: null
presence_sensor_entity_id: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
temperature_unit: °C
is_device_active: false
ema_temp: 22.35
is_over_switch: true
is_inversed: false
underlying_switch_0: switch.heating_wohnhalle
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0.13
power_percent: 13
on_time_sec: 23
off_time_sec: 156
cycle_min: 3
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
friendly_name: Heizung Wohnhalle
supported_features: 17
icon: mdi:radiator
```

## Describe the bug

On restart f HA I keep getting warning messages which I believe are not entirely correct/approriete. Two observations:

- the log message says ``hvac mode is ON``, whereas the available modes are  ``heat and off``. Guess this is just a naming issue, the warning message should say ``heat`` and not `ON``.
- more questionable is the content of the message. As far as I understand, the``hvac_mode`` would not reflect weather the underlying switch is on or not. the ``hvac_action`` is actually reflecting the state of the switch. I checked the state changes for the underlying switch and believe it actually does NOT turn on switch, despite the warning message saying it does. 

Log message (I get his for all of the thermostat integrations):
```
[custom_components.versatile_thermostat.underlyings] VersatileThermostat-heating_elternbad-switch.heating_elternbad - The hvac mode is ON, but the underlying device is not ON. Turning on device switch.heating_elternbad
```
