### ISSUE TITLE
Re-configuration of a VTherm with window detection but no window sensor does not tick the box on first screen

### ISSUE THREAD

**Issue by HACS-bank** [jmcollin78/versatile_thermostat#324]
## Version of the custom_component
5.2.0

## Configuration
``` yaml
hvac_modes: heat, off
min_temp: 5
max_temp: 20
target_temp_step: 0.1
preset_modes: none, frost, eco, comfort, boost
current_temperature: 15.3
temperature: 10
hvac_action: idle
preset_mode: frost
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: Heat only
frost_temp: 10
eco_temp: 15
boost_temp: 20
comfort_temp: 18
frost_away_temp: 5
eco_away_temp: 12
boost_away_temp: 16
comfort_away_temp: 14
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 1.87
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: frost
saved_target_temp: 15
saved_hvac_mode: heat
window_state: off
motion_state: null
overpowering_state: null
presence_state: on
window_auto_state: off
window_bypass_state: false
security_delay_min: 180
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-01-07T10:42:25.053854+00:00
last_ext_temperature_datetime: 2024-01-07T11:49:01.003750+00:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 750
mean_cycle_power: 0
total_energy: 386.88
last_update_datetime: 2024-01-07T11:49:01.007234+00:00
timezone: Europe/London
window_sensor_entity_id: null
window_delay_sec: 30
window_auto_enabled: true
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 60
motion_sensor_entity_id: null
presence_sensor_entity_id: input_boolean.someone_is_home_or_will_be_soon
power_sensor_entity_id: null
max_power_sensor_entity_id: null
temperature_unit: °C
is_device_active: false
ema_temp: 15.15
is_over_switch: true
is_inversed: false
underlying_switch_0: switch.sonoff_ac080081ff
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 60
cycle_min: 1
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
friendly_name: Bedroom
supported_features: 17 
```

I'm trying to:
Reconfigue an unrelated detail of a VTherm which I previously configured with Window Detection but no sensor for the window.

And I expect:
The tickboxes which I ticked during the previous configuration should still be ticked, and I can just SAVE and move on to the screen where I want to make a change

But I observe this ....
The Window detection is unticked on the first screen, so that if I press SAVE without making any changes, the config is actually changed

I read the documentation on the README.md file and I don't find any relevant information about this issue.
