### ISSUE TITLE
Shelly TRV (thermostat over valve) - no change in valve position when opening window

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#341]
### Discussed in https://github.com/jmcollin78/versatile_thermostat/discussions/340

<div type='discussions-op-text'>

<sup>Originally posted by **nurunet** January 14, 2024</sup>
Hi, I have bought a Shelly TRV because it was recommended here for use with VT. I set it up as a _Thermostat over Valve_. I also created an automation to push the temperature value of an external sensor to the thermostat.

Heating seems to work well, I just have some oscillation above the set heat point - I guess I still have to tweak the TPI settings.

However, I realized I didn't hear the valve move when opening the window. I checked, and - as expected - the Versatile Thermostat UI card shows the open window with little to no delay. The detail page of the VT entity in Home Assistant also shows the valve position to be 0%.

The details of the Shelly TRV entity however show the valve to be still open (at x%), and so does the web UI of the Shelly TRV itself.

Confusingly, the valve then normally moves to 0% when I **close** the window again - at least for a while.

Is this behavior known? Did I misconfigure something? Should I open an issue?</div>

**Comment by nurunet** [comment]
Looks like I'm running version 5.2.1.

My VTherm attributes are the following:
```yaml
hvac_modes: heat, off
min_temp: 7
max_temp: 23
target_temp_step: 0.1
preset_modes: none, frost, eco, comfort, boost
current_temperature: 19
temperature: 18
hvac_action: idle
preset_mode: eco
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 5
eco_temp: 18
boost_temp: 21
comfort_temp: 19
frost_away_temp: 5
eco_away_temp: 18
boost_away_temp: 18
comfort_away_temp: 18
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 1.9
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 19
saved_hvac_mode: heat
window_state: off
motion_state: null
overpowering_state: null
presence_state: on
window_auto_state: off
window_bypass_state: false
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-01-14T22:26:47.799397+01:00
last_ext_temperature_datetime: 2024-01-14T21:34:59.615481+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: 0
total_energy: 0
last_update_datetime: 2024-01-14T22:33:22.809760+01:00
timezone: Europe/Berlin
window_sensor_entity_id: binary_sensor.bathroom_window_contact
window_delay_sec: 1
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: null
presence_sensor_entity_id: binary_sensor.anyone_home
power_sensor_entity_id: null
max_power_sensor_entity_id: null
temperature_unit: °C
is_device_active: false
ema_temp: 19.1
valve_open_percent: 0
is_over_valve: true
underlying_valve_0: number.bathroom_shelly_trv_valve_position
underlying_valve_1: null
underlying_valve_2: null
underlying_valve_3: null
on_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 0.5
tpi_coef_ext: 0.01
friendly_name: Bathroom Versatile Thermostat
supported_features: 17
```

This was earlier today.

I had opened the window, and VTherm showed that correctly:

![Screenshot_20240114-134953](https://github.com/jmcollin78/versatile_thermostat/assets/48185908/07f17e56-5069-4624-b5f1-9f7685a5eaea)

But, at the same time, the valve remained open at 15%:

![Screenshot_20240114-135000](https://github.com/jmcollin78/versatile_thermostat/assets/48185908/953447d6-b7d6-4121-9ae8-9d04dd69228e)

I'll try to provide logs tomorrow.
