### ISSUE TITLE
Add the possibility to disable the safety mode on outdoor temperature sensor failure

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#343]
When the outdoor temperature sensor is in failure, the safety mode is triggered.

Because the outdoor temperature has a limited influence on percent calculation, it should be possible to deactivate it if the user think it is acceptable.

To avoid adding more configuration parameters, an global option in expert mode (so in the configuration.yaml is the prefered way). This option is not activated by default (the outdoor temperature can trigger the safety mode).

**Comment by jmcollin78** [comment]
To use it just add into your configuration.yaml the following configuration:

```
versatile_thermostat:
...
    safety_mode:
        check_outdoor_sensor: false
```
