### ISSUE TITLE
changes on cycle parameter has no effect on activation time which is always around 5 minutes 

### ISSUE THREAD

**Issue by muchasuerte** [jmcollin78/versatile_thermostat#346]
## Version of the custom_component
VTherm: 5.2.2 
Home Assistant: 2024.1.3

## Configuration

VTherm attributes are the following:
```yaml
hvac_modes:
  - heat
  - cool
  - "off"
min_temp: 7
max_temp: 35
target_temp_step: 0.1
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 16.7
temperature: 17
hvac_action: heating
preset_mode: eco
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 7
eco_temp: 17
boost_temp: 19
comfort_temp: 18
frost_away_temp: 17
eco_away_temp: 17
boost_away_temp: 17
comfort_away_temp: 17
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 13.9
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 17
saved_hvac_mode: null
window_state: "off"
motion_state: null
overpowering_state: null
presence_state: null
window_auto_state: "off"
window_bypass_state: false
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-01-17T23:20:56.532070+01:00"
last_ext_temperature_datetime: "2024-01-18T00:10:06.021516+01:00"
security_state: false
minimal_activation_delay_sec: 60
device_power: 0.5
mean_cycle_power: 0.135
total_energy: 380.41
last_update_datetime: "2024-01-18T00:13:47.639880+01:00"
timezone: Europe/Rome
window_sensor_entity_id: null
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: null
presence_sensor_entity_id: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
temperature_unit: °C
is_device_active: true
ema_temp: 16.67
is_over_switch: true
is_inversed: false
underlying_switch_0: switch.fancoil_camera_matrimoniale
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0.27
power_percent: 27
on_time_sec: 243
off_time_sec: 656
cycle_min: 15
function: tpi
tpi_coef_int: 0.8
tpi_coef_ext: 0.01
friendly_name: "Termostato camera matrimoniale "
supported_features: 17
```

## Describe the bug
I have declared  a VTerm for each room (1 dedicated sensor + 1 relay to enable or disable the fancoil) , I guess the dynamic of my system is quite slow compare to other (the water temperature on the pipeline is around 40°). 

The target temperature set is 17° however the system never reach that temperature I see it always around the value of 16.4°.

what I have noticed is that VTerm is switching ON the fancoil and the AERMEC unit then the temperature does not change because the engine did not had time reach the temperature on the pipeline then the switch is set to OFF too quickly.

I have changed the cycle from 5 min to 15 min the system switch OFF too quickly, if the target temperature is not reached it should not switch off the engine, there is no way to get an activation time high of 5 mitry nutes .

![image](https://github.com/jmcollin78/versatile_thermostat/assets/1520216/a00567c5-d077-4e51-9a4e-20639836a65c)
![image](https://github.com/jmcollin78/versatile_thermostat/assets/1520216/ff6ded8c-722b-4bee-b3ee-8f01a255c19e)

## And I expect:
what I do expect is that the system is not switched off if the target temperature is not reached or at least find a way to have the activation time longer than 5 minutes. 

But I observe the fancoil switched off also if nothing has change on metered temperature.

Seems that the change on cycle is only considered for the OFF time window and not for the ON time windows.
