### ISSUE TITLE
Setting temperature manually no longer updates VTherm 

### ISSUE THREAD

**Issue by mwitkow** [jmcollin78/versatile_thermostat#359]
## Version of the custom_component
5.3.3

## Configuration

My VTherm attributes are the following:
```yaml
vac_modes: off, heat
min_temp: 7
max_temp: 35
target_temp_step: 0.5
preset_modes: none, frost, eco, comfort, boost
current_temperature: 21.6
temperature: 23
preset_mode: none
is_on: true
hvac_action: null
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 8
eco_temp: 18
boost_temp: 30
comfort_temp: 22
frost_away_temp: 10
eco_away_temp: 18
boost_away_temp: 30
comfort_away_temp: 22
power_temp: 13
target_temperature_step: 0.5
ext_current_temperature: 8.1
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 23
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-01-22T14:16:25.057974+01:00
last_ext_temperature_datetime: 2024-01-22T13:56:18.799202+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: 2024-01-22T14:16:25.063241+01:00
timezone: Europe/Zurich
temperature_unit: °C
is_device_active: true
ema_temp: 21.61
is_used_by_central_boiler: false
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.office_thermostat
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
is_regulated: true
regulated_target_temperature: 27.5
auto_regulation_mode: auto_regulation_strong
regulation_accumulated_error: 50
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
friendly_name: Versatile Office Thermostat
supported_features: 17
```

Underylying climate entity (MQTT TVR):

```yaml
hvac_modes: off, heat
min_temp: 5
max_temp: 30
target_temp_step: 0.5
preset_modes: none, auto, manual, holiday
current_temperature: 25.1
temperature: 25
preset_mode: manual
friendly_name: Office Thermostat
supported_features: 17

```

## If it is releveant to regulation performance or optimisation some curves are needed
To have a great curves demonstrating what you think is a problem, please install and configure what is described here: [Even better with Plotly to tune your Thermostat](#even-better-with-plotly-to-tune-your-thermostat)
Regulation STrong

## Describe the bug
I have a MQTT TVR connected underlying a Climate-backed VTherm. Previously in `5.2.2` I could change the setting on the underlying thermostat's physical buttons and it would get reflected in the VTherm setting. With `5.3.3` not anymore. 

Here's 

I'm trying to:
Change the Vtherm setting by using physical buttons to adjust VTherm setting.

And I expect:
Minimum: be able to adjust temperature up/down with physical button, but see the target temperature on the underlying thermostat 
Ideal: be able to adjust the temperature up/down with physical buttons but see the VTherm target temperature.

But I observe this ....
I see the target temperature of the underlying thermostat change, but not the VTherm thermostat. 
![Screenshot 2024-01-22 at 14 20 54](https://github.com/jmcollin78/versatile_thermostat/assets/9655971/c7f45fd4-cc4f-49c7-8d21-ab879dd5eb5c)

VTherm value doesn't get updated. 

Note: this changed since 5.2.2 because it worked then (not always, but most times).

I read the documentation on the README.md file and I don't find any relevant information about this issue.

Note: Better Thermostat actually used the `number.office_thermostat_local_temperature_calibration` to make the display of the TRV match the target temp of Better thermostat.

=
