### ISSUE TITLE
"nb device active for boiler" remains zero. My boiler won't turn on when vtherm ask for heat.

### ISSUE THREAD

**Issue by djiwhy** [jmcollin78/versatile_thermostat#386]
Hi everyone,

I have a problem with the control of my oil-fired boiler (switch.chaudiere).
When it's 17°C in the office (external sensor : sensor.temp_bureau), and I ask the Vtherm (climate.vtherm_bureau) for 22°C, the underlying thermostat is modified to heat to 22°C as well.
However, in the central configuration, "nb device active for boiler" remains at zero.

However, in the central configuration, the entities are correct, the services: switch.chaudiere/switch.turn_on and turn_off work, but as a result, my boiler won't start, even though my vtherm is set to "Heat" and the threshold is set to 1.

## Version of the custom_component
release : 5.4.2

## Configuration

My VTherm (climate.vtherm_bureau) attributes are the following:
```yaml
hvac_modes:
  - "off"
  - heat
min_temp: 7
max_temp: 35
target_temp_step: 0.1
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 16.7
temperature: 22
preset_mode: none
is_on: true
hvac_action: null
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: Heat only
frost_temp: 15
eco_temp: 17
boost_temp: 22
comfort_temp: 19
frost_away_temp: 15
eco_away_temp: 17
boost_away_temp: 17
comfort_away_temp: 17
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 11.4
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 7
saved_hvac_mode: "off"
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: binary_sensor.ouverture_fenetre_bureau
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 60
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.9
security_default_on_percent: 0
last_temperature_datetime: "2024-02-18T22:26:44.209366+01:00"
last_ext_temperature_datetime: "2024-02-18T22:33:20.569063+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2024-02-18T22:39:59.978562+01:00"
timezone: Europe/Paris
temperature_unit: °C
is_device_active: true
ema_temp: 16.73
is_used_by_central_boiler: true
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.bureau
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
friendly_name: VTherm Bureau
supported_features: 401
```
Error Logs:
`Cette erreur provient d'une intégration personnalisée

Logger: custom_components.versatile_thermostat.pi_algorithm
Source: custom_components/versatile_thermostat/pi_algorithm.py:60
Integration: Versatile Thermostat configuration (documentation, issues)
First occurred: 22:19:59 (3 occurrences)
Last logged: 22:22:43

Temporarily skipping the self-regulation algorithm while the configured sensor for room temperature is unavailable`

I'm trying to:
Activate the switch for the boiler with the service: switch.chaudiere/switch.turn_on when a Vtherm ask for heating

And I expect:
A solution =)

But I observe this ....
It didn't work :/

I read the documentation on the README.md file and I don't find any relevant information about this issue.

I need your help please :/

Thx
