### ISSUE TITLE
tpi_coef_ext and tpi_coef_int can't modify

### ISSUE THREAD

**Issue by cddu33** [jmcollin78/versatile_thermostat#397]
## Version of the custom_component
5.4.2
Core
2024.2.4
Supervisor
2024.02.0
Operating System
12.0
Interface utilisateur
20240207.1
## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 25
target_temp_step: 0.1
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
  - activity
friendly_name: Bureau
supported_features: 401
current_temperature: 19.3
temperature: 19.8
hvac_action: heating
preset_mode: activity
is_on: true
hvac_mode: heat
is_controlled_by_central_mode: false
frost_temp: 7
eco_temp: 15
boost_temp: 19.8
comfort_temp: 19.3
frost_away_temp: 7
eco_away_temp: 15
boost_away_temp: 15
comfort_away_temp: 15
target_temperature_step: 0.1
ext_current_temperature: 7
ac_mode: false
saved_preset_mode: activity
saved_target_temp: 19.8
motion_sensor_entity_id: binary_sensor.presence_bureau
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: binary_sensor.porte_bureau_contact
window_delay_sec: 30
window_auto_enabled: false
window_action: window_frost_temp
security_delay_min: 120
security_min_on_percent: 0.5
security_default_on_percent: 0
last_temperature_datetime: "2024-02-27T08:04:22.908998+01:00"
last_ext_temperature_datetime: "2024-02-27T07:23:00.677934+01:00"
security_state: false
minimal_activation_delay_sec: 120
device_power: 1000
mean_cycle_power: 450
total_energy: 12093.33
last_update_datetime: "2024-02-27T08:30:52.379014+01:00"
timezone: Europe/Paris
temperature_unit: °C
is_device_active: true
ema_temp: 19.26
is_used_by_central_boiler: false
is_over_switch: true
is_inversed: false
underlying_switch_0: switch.chauffage_bureau
on_percent: 0.45
power_percent: 45
on_time_sec: 271
off_time_sec: 328
cycle_min: 10
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
motion_state: "on"
```

## Describe the bug
Modifying the tpi_coef_ext is impossible because it only wants 1 digit instead of 3: 0.02 gives 2, I also tried 0,02

I'm trying to:
Modifying the tpi_coef_ext 0.01 to 0.02

And I expect:
**0.02**
But I observe this .... **2**

It's same with tpi_coef_int

https://github.com/jmcollin78/versatile_thermostat/assets/59371705/53d982bf-dd33-4c84-a586-9c1cddfe4618

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log
No log fo this  problem
