### ISSUE TITLE
Some switch are not visible in the list of radiators

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#40]
A switch created by this template is not visible in the list of switch

```
- platform: template
  switches:
    pilote_sdb_rdc:
        friendly_name: "Pilote chauffage SDB RDC"
        value_template: "{{ is_state_attr('switch_seche_serviettes_sdb_rdc', 'sensor_state', 'on') }}"
        turn_on:
          service: select.select_option
          data:
            option: comfort
          target:
            entity_id: select.seche_serviettes_sdb_rdc_cable_outlet_mode

        turn_off:
          service: select.select_option
          data:
            option: comfort-2
          target:
            entity_id: select.seche_serviettes_sdb_rdc_cable_outlet_mode
```
