### ISSUE TITLE
Presence AC temps not showing

### ISSUE THREAD

**Issue by Crow2525-pp** [jmcollin78/versatile_thermostat#406]
## Version of the custom_component
Version 5.4.2
 

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - "off"
  - cool
  - heat
  - dry
  - fan_only
min_temp: 7
max_temp: 45
target_temp_step: 0.5
fan_modes:
  - auto
  - low
  - mid
  - high
  - highest
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 20.5
temperature: 22
fan_mode: auto
preset_mode: eco
is_on: true
hvac_action: null
hvac_mode: cool
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 16
eco_temp: 19
boost_temp: 24
comfort_temp: 22
frost_away_temp: 17
eco_away_temp: 17
boost_away_temp: 17
comfort_away_temp: 17
power_temp: 13
target_temperature_step: 0.5
ext_current_temperature: 18.06
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 19
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: input_boolean.home_presence
presence_state: "on"
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: binary_sensor.master_door_sensor_magnet_opening_2
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
window_action: window_eco_temp
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-03-12T23:22:18.098195+11:00"
last_ext_temperature_datetime: "2024-03-12T22:52:32.498291+11:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2024-03-12T23:22:18.124372+11:00"
timezone: Australia/Sydney
temperature_unit: °C
is_device_active: true
ema_temp: 20.51
is_used_by_central_boiler: false
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.masterbed_ac
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
is_regulated: true
regulated_target_temperature: 23.5
auto_regulation_mode: auto_regulation_strong
regulation_accumulated_error: 9.181416666666557
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: high
auto_deactivated_fan_mode: auto
auto_regulation_use_device_temp: false
friendly_name: Masterbed Versatile Thermostate
supported_features: 409

```

## If it is releveant to regulation performance or optimisation some curves are needed
To have a great curves demonstrating what you think is a problem, please install and configure what is described here: [Even better with Plotly to tune your Thermostat](#even-better-with-plotly-to-tune-your-thermostat)

## Describe the bug
AC temperatures settings don't exist for away. Only see heat.

I'm trying to: adjust the AC temps when I leave the house. Heat works fine.

And I expect: to be able to adjust the temps like I do for the home temps.

Further, these temps should be shown in the state yaml, noted above but aren't.

But I observe only the heater settings. It should include both AC and heat.

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log

```yaml
logger:
    default: info
    logs:
        custom_components.versatile_thermostat: info
```

```text

Add your logs here.

```
