### ISSUE TITLE
[Feature Request] Support for external Setpoint and Mode management

### ISSUE THREAD

**Issue by alexus1211** [jmcollin78/versatile_thermostat#413]
Hi,

I would like to propose adding the support for external Wall Thermostats, which not only they provide temperature, but also provide the ability to set the Setpoint (target temperature) and Modes (Heat, Cool, etc..) directly on these dievices.
I use for example the Danfoss Room Sensor 014G0160: https://manual.zwave.eu/backend/make.php?lang=EN&sku=DAN_RS-Z&cert=ZC08-14070002

It is battery operated and with it I can control the setpoint in my room. I achieve that today using the following rule in HASS:
```
alias: Sync Setpoint - LR
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.room_sensor
    attribute: temperature
  - platform: state
    entity_id:
      - climate.vthermo_living_room
    attribute: temperature
condition:
  - condition: template
    value_template: >-
      {{ state_attr('climate.room_sensor', 'temperature')|float !=
      state_attr('climate.vthermo_living_room', 'temperature')|float }}
action:
  - service: climate.set_temperature
    metadata: {}
    data:
      temperature: "{{ trigger.to_state.attributes.temperature }}"
    target:
      entity_id: climate.vthermo_living_room
  - service: climate.set_temperature
    metadata: {}
    data:
      temperature: "{{ trigger.to_state.attributes.temperature }}"
    target:
      entity_id: climate.room_sensor
mode: single
```
Furthermore, there are some similar Wall Thermostats (either WLAN or Zigbee) that offer the same functionality and some additional functionalities like the ability to change the modes. Since modes are not always mapped correctly between manufacturers, here it would be great if you can provide a menu where the user can setup a king of modes-mapping between the wall thermostat and VThermo modes.

Looking forward to your reply
