### ISSUE TITLE
vtherm over dummy/template switch not working. 

### ISSUE THREAD

**Issue by tbrasser** [jmcollin78/versatile_thermostat#414]
## Version of the custom_component
latest

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 15
max_temp: 25
target_temp_step: 0.1
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
  - activity
current_temperature: 21.1
temperature: 15
hvac_action: idle
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: Auto
frost_temp: 7
eco_temp: 18
boost_temp: 22
comfort_temp: 20
frost_away_temp: 7
eco_away_temp: 7
boost_away_temp: 7
comfort_away_temp: 7
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 11.07
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 15
saved_hvac_mode: null
motion_sensor_entity_id: binary_sensor.area_eetkamer
motion_state: "on"
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: binary_sensor.area_interior
presence_state: "on"
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-03-19T10:40:46.745511+01:00"
last_ext_temperature_datetime: "2024-03-19T10:56:10.304835+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: 0
total_energy: 0
last_update_datetime: "2024-03-19T10:59:49.124897+01:00"
timezone: Europe/Amsterdam
temperature_unit: °C
is_device_active: false
ema_temp: 21.05
is_used_by_central_boiler: true
is_over_switch: true
is_inversed: false
underlying_switch_0: input_boolean.dummy_eetkamer_trv
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: null
tpi_coef_ext: null
friendly_name: Eetkamer
supported_features: 401

```

## If it is releveant to regulation performance or optimisation some curves are needed
To have a great curves demonstrating what you think is a problem, please install and configure what is described here: [Even better with Plotly to tune your Thermostat](#even-better-with-plotly-to-tune-your-thermostat)

## Describe the bug

I'm trying to:

Use vtherm over switch on input boolean to spoof smart TRVs on radiators/areas where I have none yet. 

And I expect:

It to toggle the template switch 

But I observe this ....

![Screenshot_2024-03-19-10-26-35-618_io.homeassistant.companion.android.jpg](https://github.com/jmcollin78/versatile_thermostat/assets/2816560/7b1bd9b8-a07b-4a6d-9e70-d2df2d6919d5)

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log

```yaml
logger:
    default: info
    logs:
        custom_components.versatile_thermostat: info
```

```text

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Bron: custom_components/versatile_thermostat/prop_algorithm.py:81
integratie: Versatile Thermostat (documentation, issues)
First occurred: 10:40:46 (8 gebeurtenissen)
Laatst gelogd: 11:06:14

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1436, in _async_temperature_changed
    self.recalculate()
  File "/config/custom_components/versatile_thermostat/thermostat_switch.py", line 182, in recalculate
    self._prop_algorithm.calculate(
  File "/config/custom_components/versatile_thermostat/prop_algorithm.py", line 81, in calculate
    self._tpi_coef_int * delta_temp
    ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
 

```
