### ISSUE TITLE
Wrong energy consumption reported by Versatile Thermostat

### ISSUE THREAD

**Issue by nicolinuxfr** [jmcollin78/versatile_thermostat#438]
## Version of the custom_component

Latest version (6.2.1)

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: heat, off
min_temp: 7
max_temp: 22
target_temp_step: 0.5
friendly_name: Salle de bain - chauffage
supported_features: 401
hvac_action: idle
preset_modes: none, frost, eco, comfort, boost, activity
temperature: 7
preset_mode: frost
is_on: true
hvac_mode: heat
is_controlled_by_central_mode: true
frost_temp: 7
eco_temp: 15
boost_temp: 19.5
comfort_temp: 17
frost_away_temp: 7
eco_away_temp: 11
boost_away_temp: 19
comfort_away_temp: 15
power_temp: 13
target_temperature_step: 0.5
ac_mode: false
saved_preset_mode: frost
saved_target_temp: 7
motion_sensor_entity_id: binary_sensor.salle_de_bains_mouvements
presence_sensor_entity_id: binary_sensor.maison_presence
window_state: off
window_auto_state: off
window_bypass_state: false
window_delay_sec: 30
window_auto_enabled: false
window_action: window_turn_off
security_delay_min: 120
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-04-05T13:32:22.558287+02:00
last_ext_temperature_datetime: 2024-04-05T13:36:40.894506+02:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 2
mean_cycle_power: 0
total_energy: 142.8
last_update_datetime: 2024-04-05T13:36:40.897637+02:00
timezone: Europe/Paris
temperature_unit: °C
is_device_active: false
is_used_by_central_boiler: false
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_switch_0: switch.salle_de_bain_radiateur
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
current_temperature: 20.1
ext_current_temperature: 15.8
presence_state: on
ema_temp: 20.1
```

## Describe the bug

The energy consumption reported by Versatile Thermostat is wrong several times a day, for several days. I'm not sure when it began, but it seems to be regular now.

Here's what happens on the energy dashboard : 
<img width="1575" alt="Capture d’écran 2024-04-05 à 13 30 20" src="https://github.com/jmcollin78/versatile_thermostat/assets/2078386/e5315925-0bbb-454b-b57e-bd66ad269335">

In the statistic tools, the wrong value is easily findable now and it's always around 140 kWh, which seems to be around the total consumption of the device :

<img width="561" alt="Capture d’écran 2024-04-05 à 11 26 05" src="https://github.com/jmcollin78/versatile_thermostat/assets/2078386/9d3399c8-7bcc-4f16-b83a-72876997e4b2">

Looking at the entity's history, I noticed some drop to 0, which coincides with the wrong value showing on the energy dashboard : 

<img width="1861" alt="Capture d’écran 2024-04-05 à 12 06 26" src="https://github.com/jmcollin78/versatile_thermostat/assets/2078386/1ae009a2-a629-4463-8a12-862c3080de37">

Let me know if you need more information.
