### ISSUE TITLE
Détection de mouvement ne fonctionne pas en mode AC

### ISSUE THREAD

**Issue by cddu33** [jmcollin78/versatile_thermostat#470]
## Version of the custom_component
6.2.3

## Configuration
My VTherm attributes are the following:
```yaml
hvac_modes:
  - "off"
  - fan_only
  - cool
  - heat
  - dry
min_temp: 7
max_temp: 35
target_temp_step: 0.5
preset_modes:
  - none
  - eco
  - comfort
  - boost
  - activity
current_temperature: 20.7
temperature: 26
hvac_action: idle
preset_mode: comfort
is_on: true
hvac_mode: cool
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 7
eco_temp: 17
boost_temp: 22
comfort_temp: 20
frost_away_temp: 7
eco_away_temp: 17
boost_away_temp: 17
comfort_away_temp: 17
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: 24.1
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: comfort
saved_target_temp: 24
saved_hvac_mode: null
motion_sensor_entity_id: binary_sensor.presence_bureau
motion_state: "on"
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: input_boolean.presence
presence_state: "on"
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: binary_sensor.porte_bureau_contact
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-06-13T10:16:43.563140+02:00"
last_ext_temperature_datetime: "2024-06-13T10:16:43.563140+02:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0.49
last_update_datetime: "2024-06-13T10:19:09.405997+02:00"
timezone: Europe/Paris
temperature_unit: °C
is_device_active: false
ema_temp: 20.61
is_used_by_central_boiler: false
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.bureau
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: true
friendly_name: Bureau
supported_features: 401
```

## Describe the bug
Lors de la détection de mouvement, le mode confort est activé au lieu de confort clim et pareil pour le moment ou la détection n'est plus présente

```
