### ISSUE TITLE
AC Mode uses Heating Preset instead of Boost AC preset

### ISSUE THREAD

**Issue by petwri** [jmcollin78/versatile_thermostat#481]
## Version of the custom_component

6.2.3

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: off, auto, cool, heat, dry, fan_only
min_temp: 18
max_temp: 30
target_temp_step: 0.1
fan_modes: Auto, Quiet, Low, Medium Low, Medium, Medium High, High
preset_modes: none, frost, eco, comfort, boost
swing_modes: Off, Swing Vertical, Fixed 1, Fixed 2, Fixed 3, Fixed 4, Fixed 5
current_temperature: 24.3
temperature: 30
fan_mode: Auto
preset_mode: boost
swing_mode: Off
is_on: false
hvac_action: null
hvac_mode: off
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 15
eco_temp: 22
boost_temp: 30
comfort_temp: 23
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 19.8
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: boost
saved_target_temp: 30
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-07-02T09:38:33.605110+02:00
last_ext_temperature_datetime: 2024-07-02T09:38:33.605110+02:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: 2024-07-02T09:38:33.605358+02:00
timezone: Europe/Vienna
temperature_unit: °C
is_device_active: false
ema_temp: 24.3
is_used_by_central_boiler: false
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.ac_unit_2
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
is_regulated: true
regulated_target_temperature: 22
auto_regulation_mode: auto_regulation_medium
regulation_accumulated_error: 6.949999999999999
auto_fan_mode: auto_fan_medium
current_auto_fan_mode: auto_fan_medium
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
friendly_name: AC Kids Bedroom
supported_features: 441
```

## Describe the bug

Despite being in AC mode, the VTherm sets the temperature target for any mode to the heating mode.
When e.g. running the Boost Preset, VTherm sets the target to 30C instead of 22C (when `number.central_configuration_preset_boost_ac_temp` being `22`).

Behavior is the same for both Central Config as well as individual preset configs.

## Debug log

```text
2024-07-02 07:29:30.737 DEBUG (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-AC Living Room - Calling update_custom_attributes: {'is_on': True, 'hvac_action': None, 'hvac_mode': 'cool', 'preset_mode': 'eco', 'type': None, 'is_controlled_by_central_mode': True, 'last_central_mode': None, 'frost_temp': 15.0, 'eco_temp': 22.0, 'boost_temp': 30.0, 'comfort_temp': 23.0, 'frost_away_temp': 15.0, 'eco_away_temp': 19.0, 'boost_away_temp': 25.0, 'comfort_away_temp': 21.0, 'power_temp': 13.0, 'target_temperature_step': 0.1, 'ext_current_temperature': 19.57, 'ac_mode': True, 'current_power': 289.5, 'current_power_max': 1200.0, 'saved_preset_mode': 'eco', 'saved_target_temp': 25.0, 'saved_hvac_mode': None, 'motion_sensor_entity_id': None, 'motion_state': None, 'power_sensor_entity_id': 'sensor.ac_power', 'max_power_sensor_entity_id': 'input_number.max_ac_power', 'overpowering_state': False, 'presence_sensor_entity_id': 'binary_sensor.at_home', 'presence_state': 'on', 'window_state': 'off', 'window_auto_state': 'off', 'window_bypass_state': False, 'window_sensor_entity_id': None, 'window_delay_sec': None, 'window_auto_enabled': False, 'window_auto_open_threshold': None, 'window_auto_close_threshold': None, 'window_auto_max_duration': None, 'window_action': 'window_turn_off', 'security_delay_min': 60, 'security_min_on_percent': 0.5, 'security_default_on_percent': 0.1, 'last_temperature_datetime': '2024-07-02T08:52:51.793762+02:00', 'last_ext_temperature_datetime': '2024-07-02T09:27:43.239342+02:00', 'security_state': False, 'minimal_activation_delay_sec': 10, 'device_power': 1.0, 'mean_cycle_power': None, 'total_energy': 0, 'last_update_datetime': '2024-07-02T09:29:30.735125+02:00', 'timezone': 'Europe/Vienna', 'temperature_unit': <UnitOfTemperature.CELSIUS: '°C'>, 'is_device_active': False, 'ema_temp': 24.67, 'is_used_by_central_boiler': False, 'is_over_climate': True, 'start_hvac_action_date': None, 'underlying_climate_0': 'climate.ac_unit_1', 'underlying_climate_1': None, 'underlying_climate_2': None, 'underlying_climate_3': None, 'is_regulated': True, 'regulated_target_temperature': 25.0, 'auto_regulation_mode': 'auto_regulation_medium', 'regulation_accumulated_error': -9.7, 'auto_fan_mode': 'auto_fan_medium', 'current_auto_fan_mode': 'auto_fan_medium', 'auto_activated_fan_mode': None, 'auto_deactivated_fan_mode': None, 'auto_regulation_use_device_temp': False}
```
