### ISSUE TITLE
HA 2024.08 - Vtherm can no longer change underlying climate temperature - Provided temperature is not valid

### ISSUE THREAD

**Issue by ssorgatem** [jmcollin78/versatile_thermostat#489]
## Version of the custom_component
6.2.9 and 6.2.8
Home Assistant 2024.8.1 on HAOS

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - "off"
  - heat_cool
  - cool
  - heat
  - fan_only
  - dry
min_temp: 15
max_temp: 26
target_temp_step: 0.1
fan_modes:
  - auto
  - low
  - medium
  - high
  - silent
  - turbo
preset_modes:
  - none
  - eco
  - comfort
  - boost
swing_modes:
  - "off"
  - vertical
current_temperature: 26.6
temperature: 25
fan_mode: low
preset_mode: eco
swing_mode: "off"
is_on: true
hvac_action: null
hvac_mode: cool
type: null
is_controlled_by_central_mode: true
last_central_mode: Auto
frost_temp: 0
eco_temp: 15
boost_temp: 23
comfort_temp: 20
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 25.9
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 25
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-08-11T22:12:35.835184+02:00"
last_ext_temperature_datetime: "2024-08-11T22:09:04.144376+02:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2024-08-11T22:14:14.305072+02:00"
timezone: Europe/Madrid
temperature_unit: °C
is_device_active: true
ema_temp: 27.6
is_used_by_central_boiler: false
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.despatx
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
is_regulated: true
regulated_target_temperature: 23
auto_regulation_mode: auto_regulation_strong
regulation_accumulated_error: -7.944375457500068
auto_fan_mode: auto_fan_low
current_auto_fan_mode: auto_fan_low
auto_activated_fan_mode: low
auto_deactivated_fan_mode: auto
auto_regulation_use_device_temp: false
friendly_name: AC Despatx vt
supported_features: 441
```
Second Vtherm:

```yaml
hvac_modes:
  - "off"
  - heat_cool
  - cool
  - heat
  - fan_only
  - dry
min_temp: 15
max_temp: 26
target_temp_step: 0.1
fan_modes:
  - auto
  - low
  - medium
  - high
  - silent
  - turbo
preset_modes:
  - none
  - eco
  - comfort
  - boost
swing_modes:
  - "off"
  - vertical
current_temperature: 25.5
temperature: 25
fan_mode: low
preset_mode: eco
swing_mode: "off"
is_on: true
hvac_action: null
hvac_mode: cool
type: null
is_controlled_by_central_mode: true
last_central_mode: Auto
frost_temp: 0
eco_temp: 15
boost_temp: 23
comfort_temp: 20
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 25.9
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 16.900000000000002
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: binary_sensor.finestra_habitacio_obrint
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-08-11T22:14:05.839298+02:00"
last_ext_temperature_datetime: "2024-08-11T22:14:05.839298+02:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2024-08-11T22:14:14.303201+02:00"
timezone: Europe/Madrid
temperature_unit: °C
is_device_active: true
ema_temp: 25.09
is_used_by_central_boiler: false
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.habitacio
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
is_regulated: true
regulated_target_temperature: 24.5
auto_regulation_mode: auto_regulation_medium
regulation_accumulated_error: -10.495166666666599
auto_fan_mode: auto_fan_low
current_auto_fan_mode: auto_fan_low
auto_activated_fan_mode: low
auto_deactivated_fan_mode: auto
auto_regulation_use_device_temp: false
icon: mdi:air-conditioner
friendly_name: AC Habitació vt
supported_features: 441
```

## Describe the bug
Underlying climate temperature does not change

I'm trying to:
Change the target temperature

And I expect:
The target temperature to be changed in the underlying climate entity (I know it will not be an exact match to what is shown on the Vtherm climate)

But I observe this ....
The underlying climate temperature does not change.

Before, when setting a manual temperature, or when changing between climate presets, i could see the temperature of the underlying climate entity changed. This was also reflected on the AC unit's display. The displayed temperature did not match exactly Vtherm's temperature, but that was expected. Now, however, the temperature doesn't change. I can manually change it from the Esphome integration, and whatever value I set there is left unchanged regardless of any change I do from Vtherm, and so is the actual functioning of the AC unit.
his is happening with 2 different AC units, both controlled through Esphome.

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log

```
2024-08-11 22:34:16.947 DEBUG (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-AC Despatx vt - The device offset temp for regulation is 0.00 - internal temp is 0.00. New target is 20.50
2024-08-11 22:34:16.948 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.set_temperature (c:01J51JC77K4GNQWDH94KHXXJ04): entity_id=['climate.despatx'], temperature=20.5, target_temp_high=26.0, target_temp_low=15.0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2783, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 939, in async_service_temperature_set
    raise ServiceValidationError(
homeassistant.exceptions.ServiceValidationError: Provided temperature 15.0 is not valid. Accepted range is 16.0 to 30.0
```
