### ISSUE TITLE
last_seen and "…the configured sensor for room temperature is unavailable"

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#496]
## Version of the custom_component

Version: 6.2.9 (latest)

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - "off"
  - heat
min_temp: 14
max_temp: 26
target_temp_step: 0.5
preset_modes:
  - none
  - eco
  - comfort
  - boost
current_temperature: 22.9
temperature: 19.5
preset_mode: comfort
is_on: false
hvac_action: null
hvac_mode: "off"
type: null
is_controlled_by_central_mode: true
last_central_mode: Auto
frost_temp: 0
eco_temp: 19.5
boost_temp: 23
comfort_temp: 19.5
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: 13
target_temperature_step: 0.5
ext_current_temperature: 7.9594858575244665
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: comfort
saved_target_temp: 19.5
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: 120
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-09-14T10:40:09.080166+02:00"
last_ext_temperature_datetime: "2024-09-14T10:52:00.102638+02:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2024-09-14T10:52:00.112424+02:00"
timezone: Europe/Vienna
temperature_unit: °C
is_device_active: false
ema_temp: 22.85
is_used_by_central_boiler: false
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.wohnzimmer_eve_trv_thermostat
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
is_regulated: true
regulated_target_temperature: 19.5
auto_regulation_mode: auto_regulation_slow
regulation_accumulated_error: -576
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: true
friendly_name: Wohnzimmer Heizung
supported_features: 401
```

## Describe the bug
https://github.com/jmcollin78/versatile_thermostat/issues/398 added a `last_seen` for room temperature sensors. My Aqara temperature devices do not offer such a value. It might be available as an attribute somewhere, but I cannot enter that into the config. See:
<img width="1018" alt="Bildschirmfoto 2024-09-14 um 10 48 07" src="https://github.com/user-attachments/assets/66cb042b-ed3a-450e-ba74-f8c6f76a791f">

My logs are full of messages like: `WARNING (MainThread) [custom_components.versatile_thermostat.pi_algorithm] Temporarily skipping the self-regulation algorithm while the configured sensor for room temperature is unavailable` , so it seems I won't have a self-regulation until this is fixed or I can find an alternative solution. Thanks!
