### ISSUE TITLE
Controlling 230 V valve over switch

### ISSUE THREAD

**Issue by martin131** [jmcollin78/versatile_thermostat#498]
Hi, is there any better way how can I control my thermostat? I am using 230 V valves (https://www.elektrobock.cz/termoelektricky-pohon/p1734) controlled by the Sonoff board.

It takes a few minutes to open valves and vtherm is controlling switches too often, I think.

![image](https://github.com/user-attachments/assets/fabc973e-31aa-4c8d-b4be-5ef27ee71f90)

config:
```yaml
hvac_modes: heat, off
min_temp: 15
max_temp: 27
target_temp_step: 0.1
preset_modes: none, eco, comfort, boost
current_temperature: 23.9
temperature: 24
hvac_action: idle
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 0
eco_temp: 18
boost_temp: 25
comfort_temp: 23
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 17.131989
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 24
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: binary_sensor.0xa4c13810e6f2f587_contact
window_delay_sec: 5
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.2
security_default_on_percent: 0.1
last_temperature_datetime: 2024-09-16T10:59:55.598320+02:00
last_ext_temperature_datetime: 2024-09-16T11:00:12.394970+02:00
security_state: false
minimal_activation_delay_sec: 300
device_power: 0
mean_cycle_power: null
total_energy: 0
last_update_datetime: 2024-09-16T11:00:12.441464+02:00
timezone: Europe/Prague
temperature_unit: °C
is_device_active: false
ema_temp: 23.84
is_used_by_central_boiler: false
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_switch_0: switch.sonoff_dualr3_relay_2
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0.45
power_percent: 45
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 3
tpi_coef_ext: 0
friendly_name: Ložnice
supported_features: 401
```
