### ISSUE TITLE
HVAC Never Resets Back to Heat When Restarting Home Assistant With a Window Open

### ISSUE THREAD

**Issue by rjosborne** [jmcollin78/versatile_thermostat#504]
## Version of the custom_component

6.2.9

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: heat, off
min_temp: 10
max_temp: 32
target_temp_step: 0.5
preset_modes: none, frost, eco, comfort, boost
current_temperature: 20.8
temperature: 19
hvac_action: idle
preset_mode: comfort
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 10
eco_temp: 15
boost_temp: 22
comfort_temp: 19
frost_away_temp: 10
eco_away_temp: 10
boost_away_temp: 10
comfort_away_temp: 10
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: 10.9
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: comfort
saved_target_temp: 19
saved_hvac_mode: heat
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: binary_sensor.home_is_occupied
presence_state: on
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: binary_sensor.doors_and_windows
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-09-24T21:41:30.172966+01:00
last_ext_temperature_datetime: 2024-09-24T22:01:02.831758+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: 2024-09-24T22:01:26.150432+01:00
timezone: Europe/London
temperature_unit: °C
is_device_active: false
ema_temp: 20.76
is_used_by_central_boiler: false
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.lounge
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
friendly_name: Home Thermostat
supported_features: 401
```

## Describe the bug

I'm trying to:
- Ensure that the HVAC mode is set to heat
- Open a window
- Confirm that the HVAC mode has changed to off due to the window being open
- Restart home assistant
- After restarting home assistant, close the window

And I expect:
- the HVAC mode should change back to heat

But I observe this ....
- the HVAC mode stays off

I read the documentation on the README.md file and I don't find any relevant information about this issue.

I have taken a quick look at the code and can see the attribute "saved_hvac_mode" being written to / read from when a window opens and. closes. 

I suspect the value of this may be getting reset to "off" as a result of the home assistant restart, meaning when the window is closed, the VTherm restores the incorrect "off" value.
