### ISSUE TITLE
New Thermostat Installation / Configuration changes fail (and crash HA!)

### ISSUE THREAD

**Issue by Jadefalcon100** [jmcollin78/versatile_thermostat#506]
Hi there,

when I crate a new VTherm Home Assistant crashes. Vtherm shows the next step popup, but never finished. 
Instead HA as a whole becomes inresponsive/crashes after 10 seconds and never recovers.
![image](https://github.com/user-attachments/assets/82bb8314-e37b-43a3-9a7d-e385cf06322c)

The Instance can only be brought back with a VM restart.

After the restart the VTherm is despite it fuctional, but when I change the configuration it returns to a failed state.
Wohnzimmer - Hinten: functional after restart
![image](https://github.com/user-attachments/assets/74715a59-13b9-484f-932f-98c9f59cc28a)

Wohnzimmer - Vorner: functional after restart - just did a pseudo change by altering cycle time => Error
![image](https://github.com/user-attachments/assets/30fb1c99-9f3d-48ee-af7a-8a39d8bea13e)

## Configuration

My VTherm attributes are the following (both VTherms above are identical except for switch and sensor)
```yaml
hvac_modes: heat, off
min_temp: 10
max_temp: 30
target_temp_step: 0.1
current_temperature: 22.2
temperature: null
hvac_action: idle
is_on: null
hvac_mode: null
preset_mode: none
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 0
eco_temp: 0
boost_temp: 0
comfort_temp: 0
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: null
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: none
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-09-27T06:30:31.933001+02:00
last_ext_temperature_datetime: 2024-09-27T06:30:29.479694+02:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: 0
total_energy: null
last_update_datetime: 2024-09-27T06:30:36.516055+02:00
timezone: Europe/Berlin
temperature_unit: °C
is_device_active: false
ema_temp: 22.2
is_used_by_central_boiler: false
is_over_switch: true
is_inversed: true
keep_alive_sec: 0
underlying_switch_0: switch.schalter_eg_heizung_l1
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: null
tpi_coef_ext: null
friendly_name: Wohnzimmer - Hinten
supported_features: 385
```

## Debug log
2024-09-27 06:30:40.445 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/versatile_thermostat/__init__.py", line 110, in _async_startup_internal
    await api.init_vtherm_links()
  File "/config/custom_components/versatile_thermostat/vtherm_api.py", line 178, in init_vtherm_links
    await entity.async_startup(self.find_central_configuration())
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 665, in async_startup
    await self.init_presets(central_configuration)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 2808, in init_presets
    await self._async_set_preset_mode_internal(self._attr_preset_mode, True)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1341, in _async_set_preset_mode_internal
    self.recalculate()
  File "/config/custom_components/versatile_thermostat/thermostat_switch.py", line 182, in recalculate
    self._prop_algorithm.calculate(
  File "/config/custom_components/versatile_thermostat/prop_algorithm.py", line 87, in calculate
    self._tpi_coef_int * delta_temp

2024-09-27 07:11:24.669 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1495, in _async_temperature_changed
    self.recalculate()
  File "/config/custom_components/versatile_thermostat/thermostat_switch.py", line 182, in recalculate
    self._prop_algorithm.calculate(
  File "/config/custom_components/versatile_thermostat/prop_algorithm.py", line 87, in calculate
    self._tpi_coef_int * delta_temp
    ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

2024-09-27 10:45:39.967 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Wohnzimmer - Vorne for versatile_thermostat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/__init__.py", line 165, in async_setup_entry
    await api.init_vtherm_links()
  File "/config/custom_components/versatile_thermostat/vtherm_api.py", line 178, in init_vtherm_links
    await entity.async_startup(self.find_central_configuration())
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 665, in async_startup
    await self.init_presets(central_configuration)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 2808, in init_presets
    await self._async_set_preset_mode_internal(self._attr_preset_mode, True)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1341, in _async_set_preset_mode_internal
    self.recalculate()
  File "/config/custom_components/versatile_thermostat/thermostat_switch.py", line 182, in recalculate
    self._prop_algorithm.calculate(
  File "/config/custom_components/versatile_thermostat/prop_algorithm.py", line 87, in calculate
    self._tpi_coef_int * delta_temp
    ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
