### ISSUE TITLE
window open detection  do not got back to eco.

### ISSUE THREAD

**Issue by cpktmpkt** [jmcollin78/versatile_thermostat#521]
## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - heat
min_temp: 7
max_temp: 26
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 21.3
temperature: 18
preset_mode: eco
is_on: true
hvac_action: null
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: Heat only
frost_temp: 7
eco_temp: 18
boost_temp: 7
comfort_temp: 21
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: null
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 21
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: binary_sensor.fenstersensor_schlafzimmer_status
window_delay_sec: 5
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_frost_temp
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-10-04T05:40:54.449183+02:00"
last_ext_temperature_datetime: "2024-10-03T20:07:19.438856+02:00"
security_state: false
minimal_activation_delay_sec: 300
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2024-10-04T06:30:18.984811+02:00"
timezone: Europe/Berlin
temperature_unit: °C
is_device_active: true
ema_temp: 21.36
is_used_by_central_boiler: false
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.heizkorperthermostat_schlafzimmer
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
is_regulated: true
regulated_target_temperature: 18
auto_regulation_mode: auto_regulation_light
regulation_accumulated_error: -2.3406250000000357
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
friendly_name: VTherm Schlafzimmer
supported_features: 401
```

## If it is releveant to regulation performance or optimisation some curves are needed
---

## Describe the bug
During night I use the eco preset (17°C). If I open the window the Vterm goes to 7°C as I expected, but after closing the window again Vtherm's target temperature set to 21°C (= comfort preset). But the climate card still shows eco as selected preset.

My configuration/setting:
- using an sensor for window state detection, not the Vterm algorithm
- using Scheduler-Card for changing the Vtherm presets (but i think it doesn't affect the bug)
- using frost-preset on window open, because my TRV don't have an off mode.

I'm trying to:
---

And I expect:
after closing the window Vtherm should go bat to 17°C / eco preset

But I observe this ....
---

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log
---
