### ISSUE TITLE
Current temperature of Avatto TRV06 not read properly

### ISSUE THREAD

**Issue by tttopuz** [jmcollin78/versatile_thermostat#535]
I have recently added Avatto TRV06 to my setup. When I try to control them by Versatile Thermostat in a climate, it does control the TRV to open or closes. The issue is that the set temperature does not take the current temperature of the TRV into account. 

This causes the TRV to be heating while it should not (see photo). In this case the set temperature of the TRV should be set lower than the current temperature (around 16 degrees).

![image](https://github.com/user-attachments/assets/e3e524d0-5ca1-44c2-990d-da6fc80d2005)

Maybe it has something to do with the regulation parameters, but I have tried several combinations and they all show not success. Let me know if you need more information. 

## Version of the custom_component
6.3.0

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: off, heat
min_temp: 7
max_temp: 35
target_temp_step: 0.5
friendly_name: Versatile Thermostat
supported_features: 401
current_temperature: 19.5
temperature: 19
preset_modes: none, frost, eco, comfort, boost
preset_mode: none
is_on: true
hvac_action: heating
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 10
eco_temp: 12
boost_temp: 20
comfort_temp: 19
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: 12.8
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 19.5
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-10-10T12:48:55.874397+02:00
last_ext_temperature_datetime: 2024-10-10T12:31:52.116929+02:00
security_state: false
minimal_activation_delay_sec: 299
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: 2024-10-10T12:48:59.214801+02:00
timezone: Europe/Amsterdam
temperature_unit: °C
is_device_active: true
ema_temp: 19.6
is_used_by_central_boiler: false
is_over_climate: true
start_hvac_action_date: 2024-10-10T12:39:28.015626+02:00
underlying_climate_0: climate.trv_slaapkamer_achter_thermostat
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
is_regulated: true
regulated_target_temperature: 18
auto_regulation_mode: auto_regulation_strong
regulation_accumulated_error: -8.699999999999996
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
```

## If it is releveant to regulation performance or optimisation some curves are needed
To have a great curves demonstrating what you think is a problem, please install and configure what is described here: [Even better with Plotly to tune your Thermostat](#even-better-with-plotly-to-tune-your-thermostat)

## Describe the bug

I'm trying to set the temperature on the thermostat to lower than actual temperature of the room, but the temperature of the TRV is set higher than the actual temperature of the TRV.

**Comment by tttopuz** [comment]
So I did some more testing, and it seems that VT does not read out the current temp of the TRV in the right way. Disabling the option "use internal temp of underlying" does somehow provide better results, because it ignores the current temp. I want to test what current temp VT is using in its calculations, but I'm not sure how to.

**Comment by jmcollin78** [comment]
If I look at your attribute, I see that you don't use the internal temp of the underlying: `auto_regulation_use_device_temp: false`.
But you tells in your last post that : "when turned off, it is better". But it is already off.

When reading the first post, I would tell: "turn the use of internal temp" to on.
Maybe I don't understand exactly what you mean.

In a general manner, when you need to tune your VTherm, I need some regulation curve like explain in the template of the issue. Without it I can't do anything.

```
If it is releveant to regulation performance or optimisation some curves are needed
To have a great curves demonstrating what you think is a problem, please install and configure what is described here: [Even better with Plotly to tune your Thermostat](https://github.com/jmcollin78/versatile_thermostat/issues/535#even-better-with-plotly-to-tune-your-thermostat)
```

**Comment by tttopuz** [comment]
Thank you for your answer and your time. 

These new TRV's have an internal temperature that are a lot (4 degrees or more) lower than the real temperature. In some way it seems that the VTherm has a hard time with this.

![image](https://github.com/user-attachments/assets/b021f631-114f-490a-bc39-9554ef5b7330) In this example and the example in the first post, the heating should be off because the actual room temperature is 19.2 and the set temperature is 18.2. However, the value that is given to the underlying TRV is 17,5, which is higher than the internal temperature of 16. At the end of the post I will write the attributes, to see that I am using the option of use internal temperature.



```yaml
hvac_modes: off, heat
min_temp: 7
max_temp: 35
target_temp_step: 0.2
preset_modes: none, frost, eco, comfort, boost
current_temperature: 19.2
temperature: 18.2
hvac_action: heating
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 7
eco_temp: 12
boost_temp: 7
comfort_temp: 18
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.2
ext_current_temperature: 10.7
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: comfort
saved_target_temp: 17.90000000000001
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-10-13T20:47:38.784299+02:00
last_ext_temperature_datetime: 2024-10-13T20:40:34.173843+02:00
security_state: false
minimal_activation_delay_sec: 299
device_power: 1
mean_cycle_power: null
total_energy: 15.41
last_update_datetime: 2024-10-13T20:49:08.475747+02:00
timezone: Europe/Amsterdam
temperature_unit: °C
is_device_active: true
ema_temp: 18.86
is_used_by_central_boiler: false
is_over_climate: true
start_hvac_action_date: 2024-10-13T20:44:57.738837+02:00
underlying_climate_0: climate.trv_kinderkamer_thermostat
underlying_climate_1: climate.trv_kinderkamer_voor_thermostat
underlying_climate_2: null
underlying_climate_3: null
is_regulated: true
regulated_target_temperature: 17.5
auto_regulation_mode: auto_regulation_strong
regulation_accumulated_error: -7.298828124999986
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: true
friendly_name: Kinderkamer Thermostaat
supported_features: 401
```

Luckily, I have found an option to change the offset of the current temperature in the entity of the TRV in Home Assistant itself. Now the current temperature shows as an higher value, closer to the real room temperature. VTherm handles this better somehow and the TRV is off when it should be off. See picture below.

![image](https://github.com/user-attachments/assets/4366c050-dfcf-4d7b-a10b-f3dffa10f331)

Still, there is an additional problem that the TRV is not heating if the set temperature is only a little bit above the current temperature. As you can see in the picture below, the Vtherm does set the TRV set temperature, at around 00:00, 2:00 and 5:00. However, the TRV itself is not heating. This is maybe because the difference is too low? Is there a way to increase/exaggerate this value to force the TRV to heat?

![image](https://github.com/user-attachments/assets/eaf2ae70-c3a3-44ba-b547-02419c4b2174)

An additional problem here, is that there are two TRV's in this room, and I would like to either have them both on or both off, to increase efficiency of the heating system. Is there a way to enforce this? Because in this example, the other TRV was heating at the times that the difficult TRV was not. 

![image](https://github.com/user-attachments/assets/7ba940ab-da48-4f4d-95ac-f1ea1d465e8d)

This is the history of the VTherm itself:

![image](https://github.com/user-attachments/assets/0d1096fe-091a-44e1-af9b-49bfa3443f42)
