### ISSUE TITLE
Thermostat continue its heating cycle whatever the setpoint is,  even when disabled. 

### ISSUE THREAD

**Issue by KipK** [jmcollin78/versatile_thermostat#538]
## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 23
target_temp_step: 0.5
friendly_name: Thermostat SdB
supported_features: 401
current_temperature: 19.6
temperature: 7
hvac_action: heating
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
preset_mode: frost
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 7
eco_temp: 18
boost_temp: 21
comfort_temp: 19
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: 15
target_temperature_step: 0.5
ext_current_temperature: 16.05
ac_mode: false
current_power: 400
current_power_max: 9000
saved_preset_mode: frost
saved_target_temp: 7
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: sensor.linky_puissance_inst_no_evse
max_power_sensor_entity_id: sensor.linky_pcoup_marge_evse
overpowering_state: false
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: binary_sensor.ouverture_sdb
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
window_action: window_frost_temp
security_delay_min: 30
security_min_on_percent: 0.1
security_default_on_percent: 0
last_temperature_datetime: "2024-10-11T14:44:19.356048+02:00"
last_ext_temperature_datetime: "2024-10-11T14:35:32.771625+02:00"
security_state: false
minimal_activation_delay_sec: 60
device_power: 560
mean_cycle_power: 0
total_energy: 71.86
last_update_datetime: "2024-10-11T14:49:12.189119+02:00"
timezone: Europe/Paris
temperature_unit: °C
is_device_active: true
ema_temp: 19.58
is_used_by_central_boiler: false
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_switch_0: switch.switch_rad_sdb
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 420
cycle_min: 7
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.02
```
I got this problem 3 times with 3 different thermostat this week. ( I have only started to test Versatile Therm this week ) 

Sometime, the thermostat still continue the heating cycle and never stop. 
When it's in this bugged state, I try to put the setpoint to a really low temperature, or set anti frost mode, the thermostat instantely cut off the heating. But a few mn later, I can see the heater is back on. 
It's the same if I set it to OFF. Heating continue in cycling state to a previously setted temperature ( on the example below it was 19.5°C )

Here on the screenshot below you can see at the beginning it was already still maintaining a 19.5°C temp on the room with a 18°C setpoint on the thermostat. ( it was already in this bugged state ) .
At 13h20 I set the thermostat to anti-frost mode. 
But the heating cycle continue whatever the temperature was set.

Disabling the integration and enabling it don't solve the problem. 
But restarting Home assistant does.

## Debug log

The related thermosatt is "thermosatt_sdb"

Complete log for the timeframe  here:
[home-assistant_versatile_thermostat_2024-10-11T12-39-35.156Z.txt](https://github.com/user-attachments/files/17342952/home-assistant_versatile_thermostat_2024-10-11T12-39-35.156Z.txt)
