### ISSUE TITLE
Heating when not required

### ISSUE THREAD

**Issue by Sceptorrh** [jmcollin78/versatile_thermostat#606]
## Version of the custom_component
6.6.0 (Also had the Issue on 6.5.0)

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: auto, heat, off
min_temp: 7
max_temp: 35
target_temp_step: 0.1
preset_modes: none, frost, eco, comfort, boost
current_temperature: 17.5
temperature: 7
hvac_action: heating
preset_mode: none
is_on: true
hvac_mode: auto
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 7
eco_temp: 18
boost_temp: 21
comfort_temp: 19.5
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 8.9
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 7.5
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-11-05T13:07:59.036263+01:00
last_ext_temperature_datetime: 2024-11-05T13:07:57.574518+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 6.68
last_update_datetime: 2024-11-05T13:09:57.105373+01:00
timezone: Europe/Amsterdam
temperature_unit: °C
is_device_active: true
ema_temp: 16.59
is_used_by_central_boiler: true
temperature_slope: 9.94
hvac_off_reason: null
is_over_climate: true
start_hvac_action_date: 2024-11-05T13:05:03.077612+01:00
underlying_entities: climate.z2m_trv_livingroom_small, climate.z2m_trv_livingroom_large
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
friendly_name: Vertsatile - Livingroom
supported_features: 401
```

## Describe the bug
My Versatile - Livingroom (As seen in the picture) Keeps heating. Even when the temperature is set to 7 degrees

I'm trying to:
Stop the livingroom from heating when I set the temperature below the current temperature

And I expect:
The thermostat to stop heating

But I observe this ....
![image](https://github.com/user-attachments/assets/5e6a2e36-bdbb-438f-a9c5-8dc4979c9729)

I read the documentation on the README.md file and I don't find any relevant information about this issue.
