### ISSUE TITLE
re-démarage home assistant et plantage thermostat 

### ISSUE THREAD

**Issue by Davxci** [jmcollin78/versatile_thermostat#64]
Bonjour,

encore mon problème de perte de thermostat.

j'ai avancer sur la problématique :
En faite au re-démarrage de home assistant sur certain thermostat j'ai ce message d'erreur

Échec d'appel du service climate/set_temperature. 'NoneType' object has no attribute 'calculate'

De ce que je vois les thermostat crée avec Versatile_thermostat n'arrive pas a mettre a jour les valeur les sensors :
sensor.xxxx_last_external_temperature_date
sensor.xxxxxx_last_temperature_date

j'ai essayé de changer la valeur de minimal_activation_delay_sec par un petit nombre et par un très grand nombre cela ne changer rien a chaque re-démmarage cela plante le thermostat

**Comment by Davxci** [comment]
alors petite avancée sur comment solutionné mon problème (je ne suis pas assez compétent pour me plongé dans votre code)

si je lance le script 
```
alias: test verssa 2
sequence:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      device_id: 719b5f7bc995a90fca6457043fe349a8
mode: single
```

Cela permet de faire fonctionné de nouveau le thermostat je ne sais pas si cela peut vous aidé pour améliorer le script
