### ISSUE TITLE
Incorrect Temperature Reversion on Window Close

### ISSUE THREAD

**Issue by LennardPlay** [jmcollin78/versatile_thermostat#683]
## Version of the custom_component
6.7.0

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: off, heat
min_temp: 5
max_temp: 30
target_temp_step: 0.1
current_temperature: 16.6
temperature: 19
friendly_name: Schlafzimmer
supported_features: 401
is_on: true
hvac_action: heating
hvac_mode: heat
preset_mode: eco
type: null
is_controlled_by_central_mode: true
last_central_mode: Heat only
frost_temp: 10
eco_temp: 19
boost_temp: 25
comfort_temp: 20.5
frost_away_temp: 10
eco_away_temp: 12
boost_away_temp: 18
comfort_away_temp: 16
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 7.4
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: frost
saved_target_temp: 10
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: binary_sensor.schlafzimmer_fenster
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_frost_temp
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-12-03T14:50:14.661347+01:00
last_ext_temperature_datetime: 2024-12-03T14:50:14.661347+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 164.89
last_update_datetime: 2024-12-03T14:50:44.504844+01:00
timezone: Europe/Berlin
temperature_unit: °C
is_device_active: true
ema_temp: 16.6
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
is_over_climate: true
start_hvac_action_date: 2024-12-03T14:50:44.485509+01:00
underlying_entities: climate.schlafzimmer_heizkorper
is_regulated: true
regulated_target_temperature: 20.5
auto_regulation_mode: auto_regulation_medium
regulation_accumulated_error: -7.600000000000001
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
follow_underlying_temp_change: false
preset_modes: none, frost, eco, comfort, boost
```

## Describe the bug

When closing the window, the vtherm entity reverts to the last manually set temperature instead of applying the expected preset (e.g., frost).

I'm trying to:
Use automation to manage thermostat presets throughout the day:

    Evening: Set to comfort for warmth.
    Night: Switch to eco for sleeping.
    Morning: Transition to frost, as I don’t need heating during the day.

Vent the room in the morning after waking up -> radiator turns off and back on automatically 

I Occasionally, I manually raise the temperature (e.g., ~24°C) in the evening for extra comfort. The issue only occurs when I raised the temperature manually the evening before. 

And I expect:
The radiator should turn off when the window is opened.
Upon closing the window, the thermostat should return to the active preset (frost in the morning).

But I observe this ....
The radiator turns off when the window is opened (correct behavior).
When the window is closed, the thermostat reverts to the last manually set temperature (~24°C) instead of the expected preset.

Additional Context:
I rely on the preset functionality for automation, which works great otherwise. My schedule uses comfort in the evening, eco at night, and frost during the day. Occasionally, I manually increase the temperature for extra comfort, which triggers this issue when windows are opened and closed the following day.

## Debug log
I will upload it tomorrow after logging this event.
