### ISSUE TITLE
Beta12 - TRVZB disabled?

### ISSUE THREAD

**Issue by hilburn** [jmcollin78/versatile_thermostat#684]
## Version of the custom_component

6.8.0.beta12

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - "off"
  - auto
  - heat
min_temp: 7
max_temp: 32
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 16
temperature: 17
hvac_action: idle
preset_mode: eco
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: Auto
frost_temp: 7
eco_temp: 17
boost_temp: 23
comfort_temp: 18
frost_away_temp: 7
eco_away_temp: 7
boost_away_temp: 7
comfort_away_temp: 10
power_temp: 13
target_temperature_step: 0.5
ext_current_temperature: 3.3
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 17
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: binary_sensor.home_occupied
presence_state: "on"
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: 30
window_auto_enabled: true
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-12-04T05:09:02.652439+00:00"
last_ext_temperature_datetime: "2024-12-04T04:57:02.548785+00:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 15.82
last_update_datetime: "2024-12-04T05:15:28.502174+00:00"
timezone: Europe/London
temperature_unit: °C
is_device_active: false
nb_device_actives: 0
ema_temp: 15.06
is_used_by_central_boiler: true
temperature_slope: 5.66
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities:
  - climate.bedroom_trv_1
  - climate.bedroom_trv_2
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
follow_underlying_temp_change: true
friendly_name: Bedroom
supported_features: 401
```

## Describe the bug
Since updating to beta12 - all TRVZB attributes have been stripped from the vtherms attributes and the services are showing the entities it added in the service as unavailable:
![image](https://github.com/user-attachments/assets/8647b4d8-98b9-40f3-8c5c-ecea59513dd4)
Anbd the tick box is missing in the config flow
![image](https://github.com/user-attachments/assets/13863942-34a5-4b94-8e8c-36c0e2a61bff)

Reverting to beta11 does not fix this issue

## Debug log

```text

No relevant logs seen

```
