### ISSUE TITLE
Strange behaviour with climate over climate (on Koolnova BMS integration)

### ISSUE THREAD

**Issue by ChrysMa** [jmcollin78/versatile_thermostat#689]
> Please read carefuly this instructions and fill this form before writing an issue. It helps me to help you.

## Version of the custom_component

6.8.0

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - "off"
  - cool
  - heat
min_temp: 15
max_temp: 35
target_temp_step: 0.5
fan_modes:
  - auto
  - "off"
  - low
  - medium
  - high
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 18
temperature: 19
fan_mode: auto
hvac_action: heating
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 15
eco_temp: 18.5
boost_temp: 20
comfort_temp: 19.5
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: 13
target_temperature_step: 0.5
ext_current_temperature: 8
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: comfort
saved_target_temp: 35
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-12-08T08:31:19.883017+01:00"
last_ext_temperature_datetime: "2024-12-08T08:34:13.735925+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1000
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2024-12-08T08:41:40.951122+01:00"
timezone: Europe/Paris
temperature_unit: °C
is_device_active: true
nb_device_actives: 1
ema_temp: 18
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities:
  - climate.koolnova_chambre_marion
is_regulated: true
regulated_target_temperature: 20
auto_regulation_mode: auto_regulation_light
regulation_accumulated_error: 10
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: true
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
follow_underlying_temp_change: true
friendly_name: VTH Ch Marion
supported_features: 409

```

## If it is releveant to regulation performance or optimisation some curves are needed
Nope

## Describe the bug

I'm trying to:

set the temperature (heat mode) of the underlying climate.

And I expect:

When temperature set , the underlying climate should next share the same temperature to go.

But I observe this ....

Two strange behaviours :
- when setting to pre-configure temperature (eg Comfort mode, preset 19.5) the koolnova is set either to 20° or to 19°
- when manually modifying (+ - ) the temperature, set by step the koolnova temp is set to +1, then +1.5°, +2° difference

I read the documentation on the README.md file and I don't find any relevant information about this issue.

Having a discuss about this here (in French sorry) : https://forum.hacf.fr/t/integration-climatisation-gainable-koolnova-via-le-port-bms-rs485/37543/77

## Debug log

Whatever mode set there's no reported line from versatile package (I've got many from others) sorry... Will try to see why...

```

Log empty

logger:
  default: info
  logs:
    custom_components.versatile_thermostat: debug
    custom_components.koolnova_bms: debug
```
