### ISSUE TITLE
2x Sonoff TRVZB in the same room using direct valve control doesn't control both properly

### ISSUE THREAD

**Issue by pipje2001** [jmcollin78/versatile_thermostat#697]
## Version of the custom_component
6.8.0 according to manifest, HACS says 6.8.1?

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: off, heat
min_temp: 7
max_temp: 35
target_temp_step: 0.1
current_temperature: 20
temperature: 16
hvac_action: off
friendly_name: House Climate
supported_features: 401
is_on: true
hvac_mode: heat
preset_mode: none
type: null
is_controlled_by_central_mode: true
last_central_mode: Auto
frost_temp: 7
eco_temp: 17
boost_temp: 23
comfort_temp: 20
frost_away_temp: 7
eco_away_temp: 17
boost_away_temp: 17
comfort_away_temp: 17
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 5.4
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 16
saved_hvac_mode: off
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: binary_sensor.occupied_house
presence_state: on
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: binary_sensor.windowsensor_front_door_opening
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 60
window_action: window_frost_temp
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-12-10T10:07:51.084401+01:00
last_ext_temperature_datetime: 2024-12-10T10:04:41.168376+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 49.38
last_update_datetime: 2024-12-10T10:07:51.085155+01:00
timezone: Europe/Amsterdam
temperature_unit: °C
is_device_active: false
nb_device_actives: 0
ema_temp: 20.13
is_used_by_central_boiler: false
temperature_slope: -1.36
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.office_radiator_thermostat, climate.living_room_radiator_thermostat
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 5.14637832641602
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: true
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
auto_start_stop_last_switch_date: null
follow_underlying_temp_change: true
preset_modes: none, frost, eco, comfort, boost
underlyings_valve_regulation: 
- - number.office_radiator_valve_opening_degree
  - number.office_radiator_valve_closing_degree
  - number.office_radiator_local_temperature_offset
- - number.living_room_radiator_valve_opening_degree
  - number.living_room_radiator_valve_closing_degree
  - number.living_room_radiator_local_temperature_offset

on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
valve_open_percent: 0
auto_regulation_dpercent: 0.05
auto_regulation_period_min: 1
last_calculation_timestamp: 2024-12-10T10:04:41.169395+01:00
```

## Describe the bug
It's not necessarily a bug more of a feature limitation.
I have two TRVZB's in the same room (this room is basically my whole apartment XD) Since 6.8.0 now supports direct valve control, I figured I would give it a shot but quickly found out that the two radiators respond differently. For example, 10% open (90% closed) will allow water to flow in one (office) but not in the other (living room). I can hear the motor moving in the living room TRVZB, but it only starts flowing water at 40% open (60% closed).

So, there is nothing wrong with the feature itself but for some reason the valves itself respond differently, which is a bummer since the one that only works at min 40% open, is the bigger one of the two.

Would it be possible to add some valve offset per underlaying?
