### ISSUE TITLE
nb_device_active_for_boiler not updating

### ISSUE THREAD

**Issue by SellArtApp** [jmcollin78/versatile_thermostat#698]
## Version of the custom_component
6.8.0

## Configuration

I'm posting only one VTherm but i check all of them and they have all those settings at the moment which i think are relevant to calculate nb_device_active_for_boiler.
 

```yaml
hvac_action: heating
hvac_mode: heat
```

My VTherm attributes are the following:
```yaml
hvac_modes:
  - "off"
  - heat
min_temp: 7
max_temp: 35
target_temp_step: 0.1
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 18
temperature: 22
hvac_action: heating
preset_mode: boost
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: Heat only
frost_temp: 14
eco_temp: 16
boost_temp: 22
comfort_temp: 19
frost_away_temp: 12
eco_away_temp: 14
boost_away_temp: 20
comfort_away_temp: 17
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 5.38
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: boost
saved_target_temp: 14
saved_hvac_mode: heat
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: binary_sensor.home_occupied
presence_state: "on"
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-12-10T11:53:02.557579+01:00"
last_ext_temperature_datetime: "2024-12-10T11:41:59.608620+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 250.6
last_update_datetime: "2024-12-10T11:56:59.833112+01:00"
timezone: Europe/Brussels
temperature_unit: °C
is_device_active: true
nb_device_actives: 1
ema_temp: 18.44
is_used_by_central_boiler: true
temperature_slope: -0.51
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities:
  - climate.eve_thermo_chambre_1_thermostat_2
is_regulated: true
regulated_target_temperature: 22
auto_regulation_mode: auto_regulation_strong
regulation_accumulated_error: -21
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
auto_start_stop_last_switch_date: null
follow_underlying_temp_change: false
friendly_name: Chambre 1
supported_features: 401


```

Underlying climate entity:
```yaml
hvac_modes:
  - "off"
  - heat
min_temp: 10
max_temp: 30
current_temperature: 18
temperature: 22
friendly_name: Eve Thermo Chambre 1
supported_features: 385
```

## If it is releveant to regulation performance or optimisation some curves are needed
<img width="2260" alt="Screenshot 2024-12-10 at 12 02 02" src="https://github.com/user-attachments/assets/8b2b5b0c-0ddf-498b-9a54-411b2c15ac49">

## Describe the bug
Since the lastest release, nb_device_active_for_boiler is not updating. The only way to update the value is to reboot home assistant. Then when starting, it has the correct value but it's not going to change after that.

I'm using EveHome Thermo which don't have an hvac_action. I started using Versatile thermostat when you implemented the simulated hvac_action in version 6.3.0 and it was working correctly. I'm using a Central Configuration with VTherm over climate.

I'm trying to:
I'm trying to heat my house by setting boost preset on some Vtherm.

And I expect:
My boiler to turn on as soon as the nb_device_active_for_boiler is above my threshold.

But I observe this ....
nb_device_active_for_boiler stay at 0.
My Vtherm hvac_action are heating.

## Debug log

[home-assistant_2024-12-10T11-04-58.840Z.log](https://github.com/user-attachments/files/18078321/home-assistant_2024-12-10T11-04-58.840Z.log)
