### ISSUE TITLE
hvac_off_reason is not saved / restored after VTherm restart.

### ISSUE THREAD

**Issue by TTLucian** [jmcollin78/versatile_thermostat#754]
> Please read carefuly this instructions and fill this form before writing an issue. It helps me to help you.

## Version of the custom_component
6.8.4

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - "off"
  - auto
  - heat
min_temp: 7
max_temp: 26
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 15.7
temperature: 7
hvac_action: "off"
preset_mode: none
is_on: false
hvac_mode: "off"
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 7
eco_temp: 18
boost_temp: 23
comfort_temp: 21
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: 2.58
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 7
saved_hvac_mode: "off"
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: binary_sensor.study_windows
window_delay_sec: 60
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_frost_temp
security_delay_min: 60
security_min_on_percent: 50
security_default_on_percent: 25
last_temperature_datetime: "2024-12-27T16:28:58.474321+02:00"
last_ext_temperature_datetime: "2024-12-27T16:28:58.474321+02:00"
security_state: false
minimal_activation_delay_sec: 600
device_power: 0
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2024-12-27T16:28:58.474718+02:00"
timezone: Europe/Bucharest
temperature_unit: °C
is_device_active: false
device_actives: []
nb_device_actives: 0
ema_temp: 15.71
is_used_by_central_boiler: true
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: "2024-12-27T16:28:58.474340+02:00"
is_over_climate: true
start_hvac_action_date: null
underlying_entities:
  - climate.sonoff_trv_study_left
  - climate.sonoff_trv_study_right
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
auto_start_stop_last_switch_date: null
follow_underlying_temp_change: true
icon: mdi:radiator
friendly_name: Study heating
supported_features: 401
underlyings_valve_regulation:
  - - number.sonoff_valve_opening_degree_trv_study_left
    - number.sonoff_valve_closing_degree_trv_study_left
    - number.sonoff_local_temperature_calibration_trv_study_left
  - - number.sonoff_valve_opening_degree_trv_study_right
    - number.sonoff_valve_closing_degree_trv_study_right
    - number.sonoff_local_temperature_calibration_trv_study_right
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 1800
cycle_min: 30
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.008
min_opening_degrees: null
valve_open_percent: 0
auto_regulation_dpercent: 15
auto_regulation_period_min: 0
last_calculation_timestamp: "2024-12-27T04:09:12.959319+02:00"
```

## If it is releveant to regulation performance or optimisation some curves are needed
To have a great curves demonstrating what you think is a problem, please install and configure what is described here: [Even better with Plotly to tune your Thermostat](#even-better-with-plotly-to-tune-your-thermostat)

## Describe the bug
I've set this vtherm to off last night and the following attributes didn't change at all:
current_temperature
ext_current_temperature
last_temperature_datetime
last_ext_temperature_datetime
All my themperature sensors were showing about 15 deg but vtherm was showing 18 deg (last temperature reading before setting it to "off")
The temperature readings were updated as soon as I turned on the vtherm.

I'm trying to:

And I expect:

But I observe this ....
![image](https://github.com/user-attachments/assets/87c89e21-b8b2-4d9f-9581-0d25bc59da48)

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log

```yaml
logger:
    default: info
    logs:
        custom_components.versatile_thermostat: info
```

```text

Add your logs here.

```
