### ISSUE TITLE
hvac_action stuck

### ISSUE THREAD

**Issue by TTLucian** [jmcollin78/versatile_thermostat#757]
> Please read carefuly this instructions and fill this form before writing an issue. It helps me to help you.

## Version of the custom_component
 6.8.4

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - "off"
  - auto
  - heat
min_temp: 7
max_temp: 26
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 20.2
temperature: 20
hvac_action: heating
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: Heat only
frost_temp: 7
eco_temp: 16
boost_temp: 23
comfort_temp: 20
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: 3
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: comfort
saved_target_temp: 16
saved_hvac_mode: heat
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: binary_sensor.living_windows
window_delay_sec: 60
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_frost_temp
security_delay_min: 60
security_min_on_percent: 50
security_default_on_percent: 25
last_temperature_datetime: "2024-12-28T20:31:33.878280+02:00"
last_ext_temperature_datetime: "2024-12-28T20:31:34.107642+02:00"
security_state: false
minimal_activation_delay_sec: 600
device_power: 0
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2024-12-28T20:31:39.396162+02:00"
timezone: Europe/Bucharest
temperature_unit: °C
is_device_active: false
device_actives: []
nb_device_actives: 0
ema_temp: 20.22
is_used_by_central_boiler: true
temperature_slope: 0.2
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: "2024-12-28T20:31:39.395676+02:00"
is_over_climate: true
start_hvac_action_date: null
underlying_entities:
  - climate.sonoff_trv_living_left
  - climate.sonoff_trv_living_right
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
auto_start_stop_last_switch_date: null
follow_underlying_temp_change: true
icon: mdi:radiator
friendly_name: Living heating
supported_features: 401
underlyings_valve_regulation:
  - - number.sonoff_valve_opening_degree_trv_living_left
    - number.sonoff_valve_closing_degree_trv_living_left
    - number.sonoff_local_temperature_calibration_trv_living_left
  - - number.sonoff_valve_opening_degree_trv_living_right
    - number.sonoff_valve_closing_degree_trv_living_right
    - number.sonoff_local_temperature_calibration_trv_living_right
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 1800
cycle_min: 30
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.007
min_opening_degrees: null
valve_open_percent: 0
auto_regulation_dpercent: 20
auto_regulation_period_min: 0
last_calculation_timestamp: "2024-12-28T20:31:39.389741+02:00"

```

## Describe the bug
Sometimes hvac_action gets stuck or has long delays in updating after changing target temperature. Even though the TRVs are closed and boiler is off, the hvac_action is stuck on previous value or has very long delays in updating it's value and vtherm shows wrong state.

I'm trying to:
Change target temp so vtherm turns off

And I expect:
"State" should be "off (heat)"

But I observe this ....
![image](https://github.com/user-attachments/assets/242fe6ca-9bbb-4599-8953-75618d4e2eaf)

I read the documentation on the README.md file and I don't find any relevant information about this issue.
