### ISSUE TITLE
Frost temperature setpoint doesn't update with presence

### ISSUE THREAD

**Issue by TenoriTrigger** [jmcollin78/versatile_thermostat#759]
## Version of the custom_component
Latest version (installed via HACS)

## Configuration
My VTherm attributes are the following:
```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 35
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 22.9
temperature: 22
hvac_action: idle
preset_mode: boost
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 16
eco_temp: 18
boost_temp: 22
comfort_temp: 20
frost_away_temp: 10
eco_away_temp: 10
boost_away_temp: 10
comfort_away_temp: 10
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: 4
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: boost
saved_target_temp: 22
saved_hvac_mode: heat
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: input_boolean.absent
presence_state: "on"
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: 30
window_auto_enabled: true
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-12-28T23:43:58.861042+01:00"
last_ext_temperature_datetime: "2024-12-28T23:01:43.063142+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 800
mean_cycle_power: 0
total_energy: 59616.66
last_update_datetime: "2024-12-29T00:06:42.996370+01:00"
timezone: Europe/Paris
temperature_unit: °C
is_device_active: false
device_actives: []
nb_device_actives: 0
ema_temp: 23
is_used_by_central_boiler: false
temperature_slope: -0.19
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
last_change_time_from_vtherm: "2024-12-28T23:29:47.204150+01:00"
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_entities:
  - switch.chauffage_bureau_commutateur
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 0.9
tpi_coef_ext: 0.01
calculated_on_percent: 0
friendly_name: Bureau
supported_features: 401
```

## If it is releveant to regulation performance or optimisation some curves are needed
No Plotly curves in use.

## Describe the bug

I'm trying to:
Switch my presence sensor from absent to present while the thermostat is in a “frost” or “security/hors gel” mode.

And I expect:
The thermostat’s setpoint to automatically switch from the “absent” frost temperature to the “standard” frost temperature (because presence changed to on).

But I observe this ....
It doesn't update the setpoint. I have to manually change the mode away from frost and then back to frost to get the correct setpoint.

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log

```yaml
logger:
    default: info
    logs:
        custom_components.versatile_thermostat: info
```

```text
[home-assistant_versatile_thermostat_2024-12-28T23-06-43.151Z.log](https://github.com/user-attachments/files/18267984/home-assistant_versatile_thermostat_2024-12-28T23-06-43.151Z.log)

```
