### ISSUE TITLE
vtherm entity loses sync with underlying TRV

### ISSUE THREAD

**Issue by EPicLURcher** [jmcollin78/versatile_thermostat#768]
> Please read carefuly this instructions and fill this form before writing an issue. It helps me to help you.

## Version of the custom_component
7.0.0
I did notice this in previous versions but data collected from v7

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: off, heat
min_temp: 5
max_temp: 23
target_temp_step: 0.5
preset_modes: none, frost, eco, comfort, boost
current_temperature: 18.5
temperature: 19
current_humidity: 57
hvac_action: idle
preset_mode: comfort
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 2
eco_temp: 2
boost_temp: 21
comfort_temp: 19
frost_away_temp: 2
eco_away_temp: 2
boost_away_temp: 2
comfort_away_temp: 2
target_temperature_step: 0.5
ext_current_temperature: 2.8
ac_mode: false
saved_preset_mode: comfort
saved_target_temp: 19
saved_hvac_mode: null
last_temperature_datetime: 2025-01-02T15:59:18.960869+00:00
last_ext_temperature_datetime: 2025-01-02T15:32:45.871547+00:00
minimal_activation_delay_sec: 10
total_energy: 226.22
last_update_datetime: 2025-01-02T15:59:18.961907+00:00
timezone: Europe/London
temperature_unit: °C
is_device_active: false
device_actives: 
nb_device_actives: 0
ema_temp: 18.63
is_used_by_central_boiler: false
temperature_slope: -1.32
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
last_change_time_from_vtherm: 2025-01-02T12:44:53.458304+00:00
presence_sensor_entity_id: input_boolean.athome
presence_state: on
is_presence_configured: true
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: null
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: unavailable
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: null
window_delay_sec: null
is_window_configured: false
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: off
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.tado_smart_radiator_thermostat_va3631295232
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: false
friendly_name: Conservatory
supported_features: 401
```

## If it is releveant to regulation performance or optimisation some curves are needed
To have a great curves demonstrating what you think is a problem, please install and configure what is described here: [Even better with Plotly to tune your Thermostat](#even-better-with-plotly-to-tune-your-thermostat)

## Describe the bug
The underlying TRV and the vTherm entity that use it seem to go out of sync, and into an idle state

When i set the vTherm to say 20c, the underlying entity is set to 20. but after a period of time, the underlying for some reason goes to a different temperature (normally 5c), and vtherm does not reflect this. the heating goes into an idle state and the room cools down

I'm trying to:
maintain a constant room temp

And I expect:
the vtherm to be the main control point

But I observe this ....
the vtherm entity and underlying lose sync, and switch off

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log

I do not see anything related to this in the logs
