### ISSUE TITLE
Auto-fan seems not work with MelCloud

### ISSUE THREAD

**Issue by Gamso** [jmcollin78/versatile_thermostat#787]
I configured a thermostat over_climate with a Mitsubishi AC.
I used the MelCloud integration to control my AC.

The temperature control works, but I've noticed that the auto-ventilation doesn't work. It usually takes me 2 hours to gain 2-3°C in my living room, and I guess that's because the fan speed never changes. 
By default, the fan is in automatic mode (I have 5 fan speed levels: 1 to 5 + automatic mode) and it never blows hard.
Tonight, I manually changed the fan speed to 4 and the temperature rose much faster.

I have the impression that auto-fan doesn't work with MelCloud integration, but I could be wrong.

My VTherm attributes are the following:
```yaml
hvac_modes: off, heat, dry, cool, fan_only, heat_cool
min_temp: 7
max_temp: 30
target_temp_step: 0.1
fan_modes: auto, 1, 2, 3, 4, 5
preset_modes: none, frost, eco, comfort, boost
swing_modes: auto, 1_up, 2, 3, 4, 5_down, swing
current_temperature: 19
temperature: 19
fan_mode: 1
hvac_action: heating
preset_mode: comfort
swing_mode: swing
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 7.5
eco_temp: 16
boost_temp: 22
comfort_temp: 19
frost_away_temp: 7.5
eco_away_temp: 16
boost_away_temp: 19
comfort_away_temp: 18
target_temperature_step: 0.1
ext_current_temperature: 11.7
ac_mode: true
saved_preset_mode: comfort
saved_target_temp: 19
saved_hvac_mode: heat
last_temperature_datetime: 2025-01-06T19:32:19.434308+01:00
last_ext_temperature_datetime: 2025-01-06T19:05:30.053289+01:00
minimal_activation_delay_sec: 10
total_energy: 0
last_update_datetime: 2025-01-06T19:32:37.629445+01:00
timezone: Europe/Paris
temperature_unit: °C
is_device_active: true
device_actives: climate.mitsubishi
nb_device_actives: 1
ema_temp: 18.74
is_used_by_central_boiler: false
temperature_slope: 2.92
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
last_change_time_from_vtherm: 2025-01-06T19:04:40.418711+01:00
presence_sensor_entity_id: binary_sensor.maison_occupee
presence_state: on
is_presence_configured: true
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 3.5
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: null
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: unavailable
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: null
window_delay_sec: null
is_window_configured: false
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: off
safety_delay_min: 120
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: true
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_fast
auto_start_stop_dtmin: 7
auto_start_stop_accumulated_error: -2
auto_start_stop_accumulated_error_threshold: 2
auto_start_stop_last_switch_date: 2025-01-06T17:55:25.180913+01:00
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.mitsubishi
is_regulated: true
regulated_target_temperature: 19.8
auto_regulation_mode: auto_regulation_medium
regulation_accumulated_error: 3.0906250000000037
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: auto
auto_regulation_use_device_temp: true
follow_underlying_temp_change: false
friendly_name: Salon
supported_features: 441
```

**Comment by jmcollin78** [comment]
Hello @Gamso,

it is possible that Melcloud doesn't works as expected by VTherm (which is normally the standard).
To be sure, you can try to change fan speed with action directly (Developement Tools / Actions).
Tell me if it is working like that what are the accepted values as fan speed.

If there is an issue like that you should some error logs when Vtherm tries to change the fan speed.

**Comment by Gamso** [comment]
I can change fan speed with action, or from versatile-thermostat-ui-card. But fan speed didn't change automatically with the regulation tempurature like the documentation said.

My attributes are always like that :
```yaml
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: auto
```

Does “auto_fan_high” mean that the fan should have a high speed ? Because it's not true and i had select fan speed 4 manually.
