### ISSUE TITLE
When previously set to frost mode, Vtherm switches to eco when the window is open and closed

### ISSUE THREAD

**Issue by Willy2406** [jmcollin78/versatile_thermostat#846]
## Version of the custom_component
--> "version": "7.1.4",

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: heat, off
min_temp: 7
max_temp: 25
target_temp_step: 0.5
friendly_name: vtherm_loic
supported_features: 401
current_temperature: 17.2
temperature: 16.5
hvac_action: idle
preset_modes: none, frost, eco, comfort, boost
preset_mode: comfort
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 7
eco_temp: 15
boost_temp: 18
comfort_temp: 16.5
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
target_temperature_step: 0.5
ext_current_temperature: -0.4
ac_mode: false
saved_preset_mode: comfort
saved_target_temp: 16.5
saved_hvac_mode: heat
last_temperature_datetime: 2025-01-19T20:07:56.592822+01:00
last_ext_temperature_datetime: 2025-01-19T20:13:53.953983+01:00
minimal_activation_delay_sec: 10
total_energy: 32.64
last_update_datetime: 2025-01-19T20:56:21.796068+01:00
timezone: Europe/Paris
temperature_unit: °C
is_device_active: false
device_actives: 
nb_device_actives: 0
ema_temp: 17.2
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
last_change_time_from_vtherm: 2025-01-19T20:56:21.783426+01:00
presence_sensor_entity_id: null
presence_state: unavailable
is_presence_configured: false
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: 0
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: off
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.sonoff_chambreloic_contact_contact
window_delay_sec: 5
window_off_delay_sec: 5
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: off
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_entities: input_boolean.virtualswitch_chambreloic_commandefp
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
calculated_on_percent: 0
```

## Describe the bug
Frost mode switch to Eco when i open and close the window, or when i switch off and then switch on the heater with the CVC button

I'm trying to:
I switch the heater off with the CVC button or a window detection, the heater switch  off 
Then i close the window or switch it back on with the CVC button

And I expect:
the Vtherm to switch on at the previous temperature

But I observe this ....
if the vtherm is set to "Frost" previously,  the Vtherm will be set  to "Eco" when i switch the CVC or close the window
It does behave correctly when the "Eco" or "Comfort" Mode is set up, or if the temperature was set up manually

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log
[custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-vtherm_loic - Set preset_mode: comfort force=False
2025-01-19 21:14:14.299 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-vtherm_loic - find preset temp: comfort
2025-01-19 21:14:14.300 INFO (MainThread) [custom_components.versatile_thermostat.const] VersatileThermostat-vtherm_loic - Sending event EventType.PRESET_EVENT with data: {'preset': 'comfort'}
2025-01-19 21:14:14.317 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-vtherm_loic-input_boolean.virtualswitch_chambreloic_commandefp - start heating for 0 min 17 sec
2025-01-19 21:14:14.320 INFO (MainThread) [homeassistant.components.automation.chambreloic_filpilote_on] chambreloic_filpilote_on: Running automation actions
2025-01-19 21:14:14.321 INFO (MainThread) [homeassistant.components.automation.chambreloic_filpilote_on] chambreloic_filpilote_on: Executing step device automation
2025-01-19 21:14:15.251 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-vtherm_loic - Set hvac mode: off
2025-01-19 21:14:15.254 INFO (MainThread) [custom_components.versatile_thermostat.const] VersatileThermostat-vtherm_loic - Sending event EventType.HVAC_MODE_EVENT with data: {'hvac_mode': <HVACMode.OFF: 'off'>}
2025-01-19 21:14:15.261 INFO (MainThread) [homeassistant.components.automation.chambreloic_filpilote_off] chambreloic_filpilote_OFF: Running automation actions
2025-01-19 21:14:15.261 INFO (MainThread) [homeassistant.components.automation.chambreloic_filpilote_off] chambreloic_filpilote_OFF: Executing step device automation
2025-01-19 21:14:16.538 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-vtherm_loic - Set hvac mode: heat
2025-01-19 21:14:16.538 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-vtherm_loic - Set preset_mode: comfort force=True
2025-01-19 21:14:16.538 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-vtherm_loic - find preset temp: comfort
2025-01-19 21:14:16.543 INFO (MainThread) [custom_components.versatile_thermostat.const] VersatileThermostat-vtherm_loic - Sending event EventType.HVAC_MODE_EVENT with data: {'hvac_mode': <HVACMode.HEAT: 'heat'>}
2025-01-19 21:14:16.556 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-vtherm_loic-input_boolean.virtualswitch_chambreloic_commandefp - start heating for 0 min 17 sec
2025-01-19 21:14:16.572 INFO (MainThread) [homeassistant.components.automation.chambreloic_filpilote_on] chambreloic_filpilote_on: Running automation actions
2025-01-19 21:14:16.573 INFO (MainThread) [homeassistant.components.automation.chambreloic_filpilote_on] chambreloic_filpilote_on: Executing step device automation
2025-01-19 21:14:18.697 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-vtherm_loic - Set preset_mode: frost force=False
2025-01-19 21:14:18.697 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-vtherm_loic - find preset temp: frost
2025-01-19 21:14:18.698 INFO (MainThread) [custom_components.versatile_thermostat.const] VersatileThermostat-vtherm_loic - Sending event EventType.PRESET_EVENT with data: {'preset': 'frost'}
2025-01-19 21:14:18.702 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-vtherm_loic-input_boolean.virtualswitch_chambreloic_commandefp - stop heating (2) for 5 min 0 sec
2025-01-19 21:14:18.710 INFO (MainThread) [homeassistant.components.automation.chambreloic_filpilote_off] chambreloic_filpilote_OFF: Running automation actions
2025-01-19 21:14:18.710 INFO (MainThread) [homeassistant.components.automation.chambreloic_filpilote_off] chambreloic_filpilote_OFF: Executing step device automation
2025-01-19 21:14:19.669 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-vtherm_loic - Set hvac mode: off
2025-01-19 21:14:19.671 INFO (MainThread) [custom_components.versatile_thermostat.const] VersatileThermostat-vtherm_loic - Sending event EventType.HVAC_MODE_EVENT with data: {'hvac_mode': <HVACMode.OFF: 'off'>}
2025-01-19 21:14:20.893 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-vtherm_loic - Set hvac mode: heat
2025-01-19 21:14:20.894 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-vtherm_loic - Set preset_mode: eco force=True
2025-01-19 21:14:20.894 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-vtherm_loic - find preset temp: eco
2025-01-19 21:14:20.896 INFO (MainThread) [custom_components.versatile_thermostat.const] VersatileThermostat-vtherm_loic - Sending event EventType.PRESET_EVENT with data: {'preset': 'eco'}
2025-01-19 21:14:20.902 INFO (MainThread) [custom_components.versatile_thermostat.const] VersatileThermostat-vtherm_loic - Sending event EventType.HVAC_MODE_EVENT with data: {'hvac_mode': <HVACMode.HEAT: 'heat'>}

Thank you for this wonderfull integration, btw !
