### ISSUE TITLE
Min Opening Degrees Parameter Not Respected in Direct Valve Control mode

### ISSUE THREAD

**Issue by joshua-lehmann** [jmcollin78/versatile_thermostat#862]
# Issue Description
I am using the versatile thermostat integration with the Sonoff TRVZB and over climate vTherm (self-regulation with direct valve type). I set the "Min Opening Degrees" parameter to 50, expecting the valve to never open below this value during heating. However, the thermostat still opens the valve to values below 50%, such as 20%.

I have also tested other values for "Min Opening Degrees" (e.g., 40%), but the issue persists. The behavior does not align with the configured "Min Opening Degrees."

## Expected Behaviour
The valve should not open below the configured "Min Opening Degrees" value (e.g., 50%) when heating.
## Observed Behaviour
The valve opens below the configured minimum value. For example:
Valve opening: 20% despite "Min Opening Degrees" being set to 50%.

![Image](https://github.com/user-attachments/assets/f71cbd71-e106-4c5e-8ebf-ea92039885a6)

## Version of the custom_component
I am using version 7.1.4 of the integration, but this issue has also existed in previous versions.

# Configuration

My VTherm attributes are as follows:
```yaml
hvac_modes: off, auto, heat
min_temp: 7
max_temp: 25
target_temp_step: 0.2
preset_modes: none, frost, eco, comfort, boost
current_temperature: 19.7
temperature: 19.6
hvac_action: off
preset_mode: eco
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 7
eco_temp: 19.6
boost_temp: 20.5
comfort_temp: 20
frost_away_temp: 7
eco_away_temp: 18
boost_away_temp: 7
comfort_away_temp: 18.5
target_temperature_step: 0.2
ext_current_temperature: 4.9
ac_mode: false
saved_preset_mode: eco
saved_target_temp: 20.5
saved_hvac_mode: heat
last_temperature_datetime: 2025-01-23T10:56:41.980373+01:00
last_ext_temperature_datetime: 2025-01-23T11:11:45.956154+01:00
minimal_activation_delay_sec: 300
total_energy: 0.07
last_update_datetime: 2025-01-23T11:11:45.956552+01:00
timezone: Europe/Zurich
temperature_unit: °C
is_device_active: false
device_actives: 
nb_device_actives: 0
ema_temp: 19.69
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: 2025-01-23T11:02:43.904309+01:00
presence_sensor_entity_id: person.joshua
presence_state: on
is_presence_configured: true
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: 0.08
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: off
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.fenster_schlafzimmer_contact
window_delay_sec: 20
window_off_delay_sec: 900
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
is_safety_configured: true
safety_state: off
safety_delay_min: 240
safety_min_on_percent: 0.7
safety_default_on_percent: 0.4
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.heizung_schlafzimmer
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: false
friendly_name: Heizung Schlafzimmer VT
supported_features: 401
underlyings_valve_regulation: 
- - number.heizung_schlafzimmer_valve_opening_degree
  - number.heizung_schlafzimmer_valve_closing_degree
  - number.heizung_schlafzimmer_local_temperature_calibration

on_percent: 0.08
power_percent: 8
on_time_sec: 0
off_time_sec: 1500
cycle_min: 25
function: tpi
tpi_coef_int: 0.66
tpi_coef_ext: 0.01
min_opening_degrees: 50
valve_open_percent: 0
auto_regulation_dpercent: 15
auto_regulation_period_min: 10
last_calculation_timestamp: 2025-01-23T08:41:44.955691+01:00
```
I currently do not have debug logs enabled but can provide them if needed. Please let me know if this is required to analyse the issue.
