### ISSUE TITLE
Frost preset not restored after HA restart

### ISSUE THREAD

**Issue by TTLucian** [jmcollin78/versatile_thermostat#865]
## Version of the custom_component
7.1.4

## Configuration

My VTherm attributes are the following:
**Before HA restart:**
```yaml
hvac_modes:
  - "off"
  - auto
  - heat
min_temp: 7
max_temp: 26
target_temp_step: 0.5
current_temperature: 20.9
temperature: 7
hvac_action: "off"
icon: mdi:radiator
friendly_name: Bedroom heating
supported_features: 401
is_on: true
hvac_mode: heat
preset_mode: frost
type: null
is_controlled_by_central_mode: true
last_central_mode: Heat only
frost_temp: 7
eco_temp: 16
boost_temp: 23
comfort_temp: 20
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
target_temperature_step: 0.5
ext_current_temperature: 11.5
ac_mode: false
saved_preset_mode: frost
saved_target_temp: 7
saved_hvac_mode: null
last_temperature_datetime: "2025-01-24T12:32:13.950065+02:00"
last_ext_temperature_datetime: "2025-01-24T12:32:13.950065+02:00"
minimal_activation_delay_sec: 600
total_energy: 0
last_update_datetime: "2025-01-24T12:32:13.950213+02:00"
timezone: Europe/Bucharest
temperature_unit: °C
is_device_active: false
device_actives: []
nb_device_actives: 0
ema_temp: 21.35
is_used_by_central_boiler: true
temperature_slope: -3.5
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: "2025-01-24T12:32:13.950053+02:00"
presence_sensor_entity_id: null
presence_state: unavailable
is_presence_configured: false
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 0
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: null
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 30
motion_off_delay_sec: 300
motion_preset: comfort
no_motion_preset: eco
window_state: "off"
window_auto_state: unavailable
window_action: window_frost_temp
is_window_bypass: false
window_sensor_entity_id: binary_sensor.sonoff_window_bedroom_contact
window_delay_sec: 600
window_off_delay_sec: 30
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: "off"
safety_delay_min: 60
safety_min_on_percent: 50
safety_default_on_percent: 25
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities:
  - climate.sonoff_trv_bedroom
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: true
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
underlyings_valve_regulation:
  - - number.sonoff_valve_opening_degree_trv_bedroom
    - number.sonoff_valve_closing_degree_trv_bedroom
    - number.sonoff_local_temperature_calibration_trv_bedroom
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 1800
cycle_min: 30
function: tpi
tpi_coef_int: 0.7
tpi_coef_ext: 0.006
min_opening_degrees: ""
valve_open_percent: 0
auto_regulation_dpercent: 15
auto_regulation_period_min: 0
last_calculation_timestamp: "2025-01-24T12:25:12.305334+02:00"

```
**After HA restart**

```yaml
hvac_modes:
  - "off"
  - auto
  - heat
min_temp: 7
max_temp: 26
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 20.8
temperature: 16
hvac_action: "off"
preset_mode: eco
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: Heat only
frost_temp: 7
eco_temp: 16
boost_temp: 23
comfort_temp: 20
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
target_temperature_step: 0.5
ext_current_temperature: 12.02
ac_mode: false
saved_preset_mode: frost
saved_target_temp: 7
saved_hvac_mode: null
last_temperature_datetime: "2025-01-24T12:44:09.303833+02:00"
last_ext_temperature_datetime: "2025-01-24T12:44:14.396638+02:00"
minimal_activation_delay_sec: 600
total_energy: 0
last_update_datetime: "2025-01-24T12:44:14.428386+02:00"
timezone: Europe/Bucharest
temperature_unit: °C
is_device_active: false
device_actives: []
nb_device_actives: 0
ema_temp: 21.05
is_used_by_central_boiler: true
temperature_slope: -2.36
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: "2025-01-24T12:44:09.334573+02:00"
presence_sensor_entity_id: null
presence_state: unavailable
is_presence_configured: false
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 0
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: null
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 30
motion_off_delay_sec: 300
motion_preset: comfort
no_motion_preset: eco
window_state: "off"
window_auto_state: unavailable
window_action: window_frost_temp
is_window_bypass: false
window_sensor_entity_id: binary_sensor.sonoff_window_bedroom_contact
window_delay_sec: 600
window_off_delay_sec: 30
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: "off"
safety_delay_min: 60
safety_min_on_percent: 50
safety_default_on_percent: 25
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities:
  - climate.sonoff_trv_bedroom
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: true
underlyings_valve_regulation:
  - - number.sonoff_valve_opening_degree_trv_bedroom
    - number.sonoff_valve_closing_degree_trv_bedroom
    - number.sonoff_local_temperature_calibration_trv_bedroom
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 1800
cycle_min: 30
function: tpi
tpi_coef_int: 0.7
tpi_coef_ext: 0.006
min_opening_degrees: ""
valve_open_percent: 0
auto_regulation_dpercent: 15
auto_regulation_period_min: 0
last_calculation_timestamp: "2025-01-24T12:40:07.688534+02:00"
icon: mdi:radiator
friendly_name: Bedroom heating
supported_features: 401
```

## Describe the bug

I'm trying to:
Keep frost preset activated after HA restart

And I expect:
Frost preset after HA restart

But I observe this ....
Eco preset is activated after HA restart. I'm not sure if this is intended or not but it shouldn't be!

I read the documentation on the README.md file and I don't find any relevant information about this issue.
