### ISSUE TITLE
VT does not check Valve open degree after HA Core update

### ISSUE THREAD

**Issue by TallDaikon** [jmcollin78/versatile_thermostat#871]
## Version of the custom_component

VT 7.1.4+6
HA Core 2025.1.3+4
Z2M2.0.0

## Configuration

My VTherm attributes are the following:

```yaml
hvac_modes: off, auto, heat
min_temp: 18
max_temp: 22
target_temp_step: 0.1
preset_modes: none, frost, eco, comfort, boost
current_temperature: 19.4
temperature: 19.2
hvac_action: off
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 16
eco_temp: 19
boost_temp: 20.5
comfort_temp: 20
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
target_temperature_step: 0.1
ext_current_temperature: null
ac_mode: false
saved_preset_mode: none
saved_target_temp: 19.2
saved_hvac_mode: heat
last_temperature_datetime: 2025-01-25T22:45:57.629165+01:00
last_ext_temperature_datetime: 2025-01-25T23:35:34.766699+01:00
minimal_activation_delay_sec: 10
total_energy: 24.3
last_update_datetime: 2025-01-25T23:55:34.303788+01:00
timezone: Europe/Berlin
temperature_unit: °C
is_device_active: false
device_actives: 
nb_device_actives: 0
ema_temp: 19.4
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: true
last_change_time_from_vtherm: 2025-01-25T23:50:34.305346+01:00
presence_sensor_entity_id: null
presence_state: unavailable
is_presence_configured: false
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: 0
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: off
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.terassentur_contact
window_delay_sec: 30
window_off_delay_sec: 30
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: off
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities: climate.heizwz, climate.heizez
is_regulated: true
regulated_target_temperature: null
auto_regulation_mode: auto_regulation_valve
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: true
underlyings_valve_regulation: 
- - input_number.ez_virtual_valve
- - input_number.wz_virtual_valve

on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 0.5
tpi_coef_ext: 0.013
min_opening_degrees: 
valve_open_percent: 0
auto_regulation_dpercent: 0.5
auto_regulation_period_min: 5
last_calculation_timestamp: 2025-01-25T23:35:34.766730+01:00
friendly_name: VTWohnzimmer
supported_features: 401
```

## Describe the bug

I have HA with Z2M & Sonoff TRVZB + external temp sensor etc.
I had allowed 2 updates of HA core last week.
In both cases I noticed that VT does not seem to check the current status of Valve Open Degree of TRVZB after restart/reload or sets it for safety reasons.
This is not a problem if the actual temperature is below the set temperature. In other words, heating is required. 
Conversely, VT does not switch down because the Power percent entity is already at zero percent. Then it gets hotter and hotter + opening the windows does not switch off the heating.

## Debug log
I cannot reproduce this without Core Update

![Image](https://github.com/user-attachments/assets/7d2b532b-ca55-4de5-9b29-0c49710077db)
