### ISSUE TITLE
Release 7.2.0- Heating is inverted on `over_switch` with inverted commands ?

### ISSUE THREAD

**Issue by rogor** [jmcollin78/versatile_thermostat#889]
Hi!

## Version of the custom_component
7.2.0

## Configuration

<details>
<summary>My VTherm attributes are the following:</summary>

```yaml
hvac_modes: heat, off
min_temp: -10
max_temp: 50
target_temp_step: 0.1
preset_modes: none, frost, eco, comfort, boost
current_temperature: 20.6
temperature: 15
hvac_action: heating
preset_mode: eco
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 1
eco_temp: 15
boost_temp: 19.2
comfort_temp: 18.4
frost_away_temp: 1
eco_away_temp: 14
boost_away_temp: 14
comfort_away_temp: 14
target_temperature_step: 0.1
ext_current_temperature: 8
ac_mode: false
saved_preset_mode: eco
saved_target_temp: 18.4
saved_hvac_mode: heat
last_temperature_datetime: 2025-02-05T19:20:52.475578+01:00
last_ext_temperature_datetime: 2025-02-05T19:17:23.788958+01:00
minimal_activation_delay_sec: 10
total_energy: 32.56
last_update_datetime: 2025-02-05T19:20:52.478081+01:00
timezone: Europe/Paris
temperature_unit: °C
is_device_active: true
device_actives: switch.0xa4c1380fb2c0ed3e
nb_device_actives: 1
ema_temp: 20.73
is_used_by_central_boiler: false
temperature_slope: -1.41
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
last_change_time_from_vtherm: 2025-02-05T19:14:21.939028+01:00
presence_sensor_entity_id: person.thomas
presence_state: on
is_presence_configured: true
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1.5
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: 0
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: off
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.fenetre_thomas_contact
window_delay_sec: 30
window_off_delay_sec: 30
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: off
safety_delay_min: 60
safety_min_on_percent: 0.7
safety_default_on_percent: 0.2
is_over_switch: true
is_inversed: true
keep_alive_sec: 0
underlying_entities: switch.0xa4c1380fb2c0ed3e
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 600
cycle_min: 10
function: tpi
tpi_coef_int: 0.56
tpi_coef_ext: 0.014
calculated_on_percent: 0
vswitch_on_commands: 
vswitch_off_commands: 
friendly_name: VTherm Thomas
supported_features: 401
```
</details>

## Describe the bug
I updated to the new version 7.2.0 a few hours ago, and I noticed the temperature in my room kept rising, the heater was on, even though according to vtherm it was off:
![Image](https://github.com/user-attachments/assets/7ba381e4-01a3-4e16-8d8a-a2f58272be99)

The display icon in the versatile-thermostat-ui-card is also inverted, it turns red when the heater is off.

Hopefully this is just a simple fix :p
