### ISSUE TITLE
TRZVB not fully closed when heating is off in valve control mode

### ISSUE THREAD

**Issue by PokePango** [jmcollin78/versatile_thermostat#927]
## Version of the custom_component
7.2.3

## Configuration

My VTherm attributes are the following:

```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 26
target_temp_step: 0.1
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 13.5
temperature: 7
hvac_action: idle
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: Heat only
frost_temp: 7
eco_temp: 13
boost_temp: 17
comfort_temp: 15
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
target_temperature_step: 0.1
ext_current_temperature: 9.7
ac_mode: false
saved_preset_mode: eco
saved_target_temp: 13
saved_hvac_mode: heat
last_temperature_datetime: "2025-02-22T06:50:38.114152+01:00"
last_ext_temperature_datetime: "2025-02-22T07:34:19.439278+01:00"
minimal_activation_delay_sec: 30
minimal_deactivation_delay_sec: 0
total_energy: 45.89
last_update_datetime: "2025-02-22T08:01:19.699825+01:00"
timezone: Europe/Paris
temperature_unit: °C
is_device_active: false
device_actives: []
nb_device_actives: 0
ema_temp: 13.52
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
last_change_time_from_vtherm: "2025-02-22T06:31:24.071865+01:00"
presence_sensor_entity_id: null
presence_state: unavailable
is_presence_configured: false
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 1
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: null
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 30
motion_off_delay_sec: 300
motion_preset: comfort
no_motion_preset: eco
window_state: unavailable
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: null
window_delay_sec: null
window_off_delay_sec: null
is_window_configured: false
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: "off"
safety_delay_min: 60
safety_min_on_percent: 0.7
safety_default_on_percent: 0.4
is_auto_start_stop_configured: false
is_over_climate: true
start_hvac_action_date: null
underlying_entities:
  - climate.vtherm_switch_bureau
  - climate.vtherm_valve_bureau
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
follow_underlying_temp_change: false
friendly_name: VTherm Central bureau
supported_features: 401

```

## Describe the bug

Since last update my SONOFF trzvb receive the following configuration when heating is off:

* Opening degree: 0
* Closing degree: 99

I have 10 TRZVB at home and on at least 2 of them (not all) this configuration allows water to flow in the radiator, heating empty rooms.

I saw a recent update that might have induced this behavior, currently in my setup it seems that unless closing degree reaches 100% my radiators aren't closed.

I don't see parameters that would allow me to bypass this feature.

In the following example temperature increased by 3 degrees although temperature requirements were lower:

![Image](https://github.com/user-attachments/assets/3c738120-afc4-4594-b018-e9c3b7be4b01)
