### ISSUE TITLE
Configuring thermostat via YAML in configuration.yaml or packages

### ISSUE THREAD

**Issue by nicola-spreafico** [jmcollin78/versatile_thermostat#933]
Hi,
Is it possible to configure/add a Thermostat entry via YAML in Home Assistant config.yaml instead of using the UI?

Because I have a lot of TRV to manage, I am auto-generating part of my configuration and I would like to add the Thermostat to it. Basically I have some sort of yaml-template that I render with the needed input to bulk update them.

Right now I have to do all via interface which is not very quick when you have multiple thermostat to update.

Thank you

**Comment by jmcollin78** [comment]
No it is no more possible since the UI. You are the first one which request for configuration in yaml and not through UI.
Do you use the central configuration ? All configurations can be configuerd only once through the central config.

Else, there is no way to configure through a yaml.

**Comment by hacscred** [comment]
I wanted to define multiple independent thermostats via YAML but that seems to be impossible. 

Without YAML a large Home Assistant configuration becomes impossible to maintain. My configuration.yaml is 10,000 lines of generated code. Do you expect me to point and click all of that whenever there's a system failure or to depend on "backups"? 

Please implement feature parity in YAML and support multiple. Singletons are an awful design practice.

**Comment by jmcollin78** [comment]
Hello @hacscred,

I do not intend to rewrite the integration. Sorry but I pass a large part of the year to implement the Config Flow through UI and I will not reverse it.

I don't understand your point about singleton. You can create as many Vtherm as you want. What is the point here ?

**Comment by hacscred** [comment]
I didn't ask you to reverse anything. Every sane program in the world allows for configuration via some specified text format. Ever heard of Terraform? If you can't comprehend that some people might have systems with hundreds of thermostats, there's little to discuss. 

Just rename your thermostat to my_toy_thermostat. 

Just because the person who came up with the UI based configuration decided one day to go back to the 1990s, doesn't mean you had to follow him.

**Comment by jmcollin78** [comment]
@hacscred  You are fucking crazy. Please go to hell and never use my integrations anymore. You are now blocked.

**Comment by wohfab** [comment]
Ah, shame, I was moving away from Better Thermostat because of this limitation and hoped, I could use config files for my thermostats as well. As @nicola-spreafico, I also auto generate my config files and setting up via UI is just to tedious. I play around a lot with my setup and having it all set up via a config I can version control in a git repo is mandatory.

For example setting up my window groups looks like this:

```yaml
{% set rooms = {
  "kitchen": ["kitchen_window_contact", "kitchen_balcony_door_contact"],
  "bath": ["bath_window_contact"],
  "child": ["child_window_contact"],
  "master": ["master_window_contact", "master_balcony_door_contact"],
  "office": ["office_window_contact"],
  "living": ["living_window_contact"],
  "dining": ["dining_window_contact"]
} %}
{%- for room, sensors in rooms.items() %}
- name: "{{ room.title() }} Window Group"
  unique_id: {{ room }}_window_group
  platform: group
  device_class: window
  entities:
  {% for sensor in sensors %}
    - binary_sensor.{{ sensor }}
  {%- endfor %}
{% endfor %}
```

Setting these up individually or even via mouse click galore in the UI, it would be so time consuming.
