### ISSUE TITLE
Issue with respecting minimal_activation_delay_sec and minimal_deactivation_delay_sec

### ISSUE THREAD

**Issue by FermedePommerieux** [jmcollin78/versatile_thermostat#937]
## Version of the custom_component
7.2.3

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: heat, off
min_temp: 17
max_temp: 24
target_temp_step: 0.5
preset_modes: none, frost, eco, comfort, boost
current_temperature: 20.6
temperature: 21
hvac_action: heating
preset_mode: comfort
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 17
eco_temp: 19
boost_temp: 24
comfort_temp: 21
frost_away_temp: 17
eco_away_temp: 17
boost_away_temp: 17
comfort_away_temp: 17
target_temperature_step: 0.5
ext_current_temperature: -2.3
ac_mode: false
saved_preset_mode: comfort
saved_target_temp: 19
saved_hvac_mode: off
last_temperature_datetime: 2025-03-03T08:48:06.664036+01:00
last_ext_temperature_datetime: 2025-03-03T08:11:05.194778+01:00
minimal_activation_delay_sec: 1200
minimal_deactivation_delay_sec: 1200
total_energy: 226600
last_update_datetime: 2025-03-03T08:48:06.666360+01:00
timezone: Europe/Paris
temperature_unit: °C
is_device_active: true
device_actives: switch.solognote_poele_salon_switch_0
nb_device_actives: 1
ema_temp: 20.57
is_used_by_central_boiler: false
temperature_slope: -0.01
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
last_change_time_from_vtherm: 2025-03-02T22:41:23.079451+01:00
presence_sensor_entity_id: binary_sensor.solognote_presence
presence_state: on
is_presence_configured: true
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 11000
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: 8360
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: off
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: binary_sensor.solognote_doors
window_delay_sec: 300
window_off_delay_sec: 300
is_window_configured: true
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: off
safety_delay_min: 6000000
safety_min_on_percent: 0
safety_default_on_percent: 0
is_over_switch: true
is_inversed: false
keep_alive_sec: 0
underlying_entities: switch.solognote_poele_salon_switch_0
on_percent: 0.76
power_percent: 76
on_time_sec: 900
off_time_sec: 0
cycle_min: 15
function: tpi
tpi_coef_int: 0.4
tpi_coef_ext: 0.025
calculated_on_percent: 0.76
vswitch_on_commands: 
vswitch_off_commands: 
friendly_name: Solognote salon poele
supported_features: 401
```

## Describe the bug

What I am trying to do
Configure a minimal activation delay (minimal_activation_delay_sec) and a minimal deactivation delay (minimal_deactivation_delay_sec) of 1200 seconds (20 minutes). This delay is meant to prevent the heating system from cycling on and off too frequently.

Expected behavior
The thermostat should:

Not allow the heater to turn back on before 20 minutes have passed after it turned off.
Not allow the heater to turn off before 20 minutes have passed after it turned on.
Observed behavior
The thermostat ignores these settings and changes the state of switch.solognote_poele_salon_switch_0 without respecting these delays.
As a result, the heater is switched off and back on several times within a period much shorter than the configured 20 minutes.

## Debug log

```text
2025-03-03 08:22:06.687 DEBUG (MainThread) [custom_components.versatile_thermostat.thermostat_switch] VersatileThermostat-Solognote salon poele - recalculate all
2025-03-03 08:22:06.687 INFO (MainThread) [custom_components.versatile_thermostat.prop_algorithm] Solognote salon poele - No heating period due to heating period too small (635.850000 < 1200.000000)
2025-03-03 08:22:06.687 INFO (MainThread) [custom_components.versatile_thermostat.prop_algorithm] Solognote salon poele - Force 100% heating cycle since the off duration (900.000000) is shorter than minimal_deactivation_delay (1200.000000)
2025-03-03 08:22:06.687 DEBUG (MainThread) [custom_components.versatile_thermostat.prop_algorithm] Solognote salon poele - heating percent calculated for current_temp 20.7, ext_current_temp -2.3 and target_temp 21.0 is 0.71, on_time is 900 (sec), off_time is 0 (sec)
```

Interpretation
The thermostat correctly detects that the required heating period (592 seconds) is shorter than the configured minimal activation delay (1200 seconds).
However, instead of respecting the minimal deactivation delay (minimal_deactivation_delay_sec), it forces a 100 percent heating cycle.

Problem
This behavior may be a protective logic (perhaps useful for other types of systems), but it is not suitable for a pellet stove or any device requiring a strict cooling period between cycles. This leads to frequent restarts, which defeats the purpose of minimal_activation_delay_sec and minimal_deactivation_delay_sec.
